# Verilated -*- Makefile -*-
# DESCRIPTION: Verilator output: Make include file with class lists
#
# This file lists generated Verilated files, for including in higher level makefiles.
# See Vfalco_top.mk for the caller.

### Switches...
# C11 constructs required?  0/1 (always on now)
VM_C11 = 1
# Timing enabled?  0/1
VM_TIMING = 0
# Coverage output mode?  0/1 (from --coverage)
VM_COVERAGE = 0
# Parallel builds?  0/1 (from --output-split)
VM_PARALLEL_BUILDS = 1
# Tracing output mode?  0/1 (from --trace/--trace-fst)
VM_TRACE = 1
# Tracing output mode in VCD format?  0/1 (from --trace)
VM_TRACE_VCD = 1
# Tracing output mode in FST format?  0/1 (from --trace-fst)
VM_TRACE_FST = 0

### Object file lists...
# Generated module classes, fast-path, compile with highest optimization
VM_CLASSES_FAST += \
	Vfalco_top \
	Vfalco_top___024root__DepSet_h744eb8a2__0 \
	Vfalco_top___024root__DepSet_h41dce0d6__0 \
	Vfalco_top_falco_top__DepSet_h7004b4a5__0 \
	Vfalco_top_core_top__DepSet_h5f8baf9f__0 \
	Vfalco_top_falco_mem_model__DepSet_haa8b30a1__0 \
	Vfalco_top_falco_mem_model__DepSet_h1b1f68d9__0 \
	Vfalco_top_int_issue_queue__DepSet_h11b3fb1b__0 \
	Vfalco_top_reorder_buffer__DepSet_hb2d9aca3__0 \
	Vfalco_top_reorder_buffer__DepSet_hb2d9aca3__1 \
	Vfalco_top_reorder_buffer__DepSet_hb2d9aca3__2 \
	Vfalco_top_reorder_buffer__DepSet_h036dccd7__0 \
	Vfalco_top_register_read__DepSet_h3966aaf5__0 \
	Vfalco_top_RNDS_stage__DepSet_h3c179c1b__0 \
	Vfalco_top_IF_stage__DepSet_h78b7e58e__0 \
	Vfalco_top_IF_stage__DepSet_hba038ea3__0 \
	Vfalco_top_store_buffer__DepSet_h7dc1272a__0 \
	Vfalco_top_store_buffer__DepSet_h4a65534e__0 \
	Vfalco_top_alu_csr_bc_execute_group__DepSet_hea0d174a__0 \
	Vfalco_top_load_buffer__DepSet_h8352be79__0 \
	Vfalco_top_committed_map_table__DepSet_hc06fec98__0 \
	Vfalco_top_AGU__DepSet_h3781a8cf__0 \
	Vfalco_top_ID_stage__DepSet_h78676f51__0 \
	Vfalco_top_mem_access__DepSet_h030e78f4__0 \
	Vfalco_top_pipeline_control_recovery__DepSet_hd16300d7__0 \
	Vfalco_top_load_store_unit__DepSet_ha7c8e8f0__0 \
	Vfalco_top_alu_muldiv_execute_group__DepSet_h65f17e61__0 \
	Vfalco_top_alu_muldiv_execute_group__DepSet_h52959a19__0 \
	Vfalco_top_csr_file__DepSet_h3a721662__0 \
	Vfalco_top_mem_issue_queue__DepSet_h7c8226d2__0 \
	Vfalco_top_int_rob_tag_replay_unit__DepSet_h8d57ac4c__0 \
	Vfalco_top_empty_entry_finder8_wrapper__DepSet_h8da49ea1__0 \
	Vfalco_top_combine_data_unit__DepSet_hcf243edc__0 \
	Vfalco_top_mem_replay_unit__DepSet_h53d672e4__0 \
	Vfalco_top_ALU__DepSet_h6ff0c63d__0 \
	Vfalco_top_ID_stage_io__DepSet_h70e5b910__0 \
	Vfalco_top_exe_stage_io__DepSet_h947ef0f1__0 \
	Vfalco_top_register_map_table__DepSet_ha6cb98b4__0 \
	Vfalco_top_AGU_io__DepSet_h680a9b34__0 \
	Vfalco_top_load_forward_unit__DepSet_h05c9d4bb__0 \
	Vfalco_top_pipeline_control_recovery_io__DepSet_h5cad465a__0 \
	Vfalco_top_fast_mul__DepSet_h9816b2ac__0 \
	Vfalco_top_int_iq_ctr_rob_tag_balance_selector__DepSet_he3f43a27__0 \
	Vfalco_top_int_iq_ctr_rob_tag_balance_selector__DepSet_hd4925e5b__0 \
	Vfalco_top_divider__DepSet_hb7d88140__0 \
	Vfalco_top_gshare_branch_predictor__DepSet_hc8bcb4b1__0 \
	Vfalco_top_gshare_branch_predictor__DepSet_hc8bcb4b1__1 \
	Vfalco_top_gshare_branch_predictor__DepSet_hc8bcb4b1__2 \
	Vfalco_top_gshare_branch_predictor__DepSet_hc8bcb4b1__3 \
	Vfalco_top_gshare_branch_predictor__DepSet_hc8bcb4b1__4 \
	Vfalco_top_load_store_unit_io__DepSet_haec949d4__0 \
	Vfalco_top_int_issue_queue_io__DepSet_hab4d3158__0 \
	Vfalco_top_physical_register_file__DepSet_h2360a7be__0 \
	Vfalco_top_load_buffer_io__DepSet_h7931cc9a__0 \
	Vfalco_top_mem_iq_balance_selector_wo_store__DepSet_h96563263__0 \
	Vfalco_top_mem_iq_balance_selector_wo_store__DepSet_h1ff46617__0 \
	Vfalco_top_last_fetch_store_table__DepSet_h17cb72dd__0 \
	Vfalco_top_last_fetch_store_table__DepSet_h17cb72dd__1 \
	Vfalco_top_prf_freelist__DepSet_h52449ecb__0 \
	Vfalco_top_prf_freelist__DepSet_h63e2ba6f__0 \
	Vfalco_top_prf_freelist__DepSet_h63e2ba6f__1 \
	Vfalco_top_busy_list__DepSet_h694cf72b__0 \
	Vfalco_top_rename_dispatch_io__DepSet_hffd1a5ea__0 \
	Vfalco_top_decoder__DepSet_h7f0be334__0 \
	Vfalco_top_mem_issue_queue_io__DepSet_hfbf17cb1__0 \
	Vfalco_top_program_counter__DepSet_hbf983b8a__0 \
	Vfalco_top_IF_stage_io__DepSet_ha1851d16__0 \
	Vfalco_top_commit_stage_io__DepSet_hb3dd7363__0 \
	Vfalco_top_branch_unit__DepSet_ha183d5be__0 \
	Vfalco_top_store_buffer_io__DepSet_h96f8146b__0 \
	Vfalco_top_csr_io__DepSet_hb10f2992__0 \
	Vfalco_top_mem_access_io__DepSet_h11b55dd5__0 \
	Vfalco_top_store_set_id_table__DepSet_h548cd758__0 \
	Vfalco_top_store_set_id_table__DepSet_h611b0300__0 \
	Vfalco_top_register_read_io__DepSet_hb2d3f3b0__0 \
	Vfalco_top_BTB__DepSet_h6405303b__0 \
	Vfalco_top_BTB__DepSet_hf4df5923__0 \
	Vfalco_top_Picker8_1__DepSet_ha7d79143__0 \
	Vfalco_top_Picker8_2__DepSet_h1ead16b1__0 \
	Vfalco_top_empty_entry_finder8__DepSet_h6f48586e__0 \
	Vfalco_top_empty_entry_finder8__DepSet_hd35f8bb1__0 \
	Vfalco_top_empty_entry_finder8__DepSet_h857e01df__0 \
	Vfalco_top_Latest_Picker_2_1__DepSet_he92b4e73__0 \
	Vfalco_top_LS_wo_store_Picker8_1__DepSet_h5929b292__0 \
	Vfalco_top_distri_ram2r1w__E200_A9_D1e__DepSet_h9f5d1189__0 \
	Vfalco_top_distri_ram2r1w__E200_A9_D15__DepSet_h5994d19a__0 \
	Vfalco_top_sram_dual_port__R8_RBb__DepSet_h62b2fcb7__0 \
	Vfalco_top_Picker2_1__DepSet_hc4741880__0 \
	Vfalco_top_Picker2_2__DepSet_h45a2d301__0 \
	Vfalco_top_Picker4_2__DepSet_hef6072c6__0 \
	Vfalco_top_emptry_entry_finder2__DepSet_ha5f5f610__0 \
	Vfalco_top_emptry_entry_finder4__DepSet_he1700a35__0 \
	Vfalco_top_LS_wo_store_Picker2_1__DepSet_h1332a6e5__0 \

# Generated module classes, non-fast-path, compile with low/medium optimization
VM_CLASSES_SLOW += \
	Vfalco_top__ConstPool_0 \
	Vfalco_top___024root__Slow \
	Vfalco_top___024root__DepSet_h744eb8a2__0__Slow \
	Vfalco_top___024root__DepSet_h41dce0d6__0__Slow \
	Vfalco_top_falco_top__Slow \
	Vfalco_top_falco_top__DepSet_h7004b4a5__0__Slow \
	Vfalco_top_falco_top__DepSet_h45a2e4dd__0__Slow \
	Vfalco_top___024unit__Slow \
	Vfalco_top___024unit__DepSet_hb9d7fe43__0__Slow \
	Vfalco_top_core_top__Slow \
	Vfalco_top_core_top__DepSet_h5f8baf9f__0__Slow \
	Vfalco_top_core_top__DepSet_h681fcbc3__0__Slow \
	Vfalco_top_falco_mem_model__Slow \
	Vfalco_top_falco_mem_model__DepSet_h1b1f68d9__0__Slow \
	Vfalco_top_Falco_pkg__Slow \
	Vfalco_top_Falco_pkg__DepSet_h9dbf8640__0__Slow \
	Vfalco_top_int_issue_queue__Slow \
	Vfalco_top_int_issue_queue__DepSet_h11b3fb1b__0__Slow \
	Vfalco_top_int_issue_queue__DepSet_ha6581f3f__0__Slow \
	Vfalco_top_L1_cache_pkg__Slow \
	Vfalco_top_L1_cache_pkg__DepSet_h9a6566f2__0__Slow \
	Vfalco_top_reorder_buffer__Slow \
	Vfalco_top_reorder_buffer__DepSet_hb2d9aca3__0__Slow \
	Vfalco_top_reorder_buffer__DepSet_h036dccd7__0__Slow \
	Vfalco_top_register_read__Slow \
	Vfalco_top_register_read__DepSet_h3966aaf5__0__Slow \
	Vfalco_top_register_read__DepSet_h8f04cead__0__Slow \
	Vfalco_top_RNDS_stage__Slow \
	Vfalco_top_RNDS_stage__DepSet_h886f3f14__0__Slow \
	Vfalco_top_RNDS_stage__DepSet_h3c179c1b__0__Slow \
	Vfalco_top_IF_stage__Slow \
	Vfalco_top_IF_stage__DepSet_h78b7e58e__0__Slow \
	Vfalco_top_IF_stage__DepSet_hba038ea3__0__Slow \
	Vfalco_top_store_buffer__Slow \
	Vfalco_top_store_buffer__DepSet_h7dc1272a__0__Slow \
	Vfalco_top_store_buffer__DepSet_h4a65534e__0__Slow \
	Vfalco_top_alu_csr_bc_execute_group__Slow \
	Vfalco_top_alu_csr_bc_execute_group__DepSet_hea0d174a__0__Slow \
	Vfalco_top_alu_csr_bc_execute_group__DepSet_hdb9942ee__0__Slow \
	Vfalco_top_load_buffer__Slow \
	Vfalco_top_load_buffer__DepSet_h8352be79__0__Slow \
	Vfalco_top_load_buffer__DepSet_h34f8da21__0__Slow \
	Vfalco_top_committed_map_table__Slow \
	Vfalco_top_committed_map_table__DepSet_hf5fc0cc0__0__Slow \
	Vfalco_top_AGU__Slow \
	Vfalco_top_AGU__DepSet_hbb9a9e04__0__Slow \
	Vfalco_top_AGU__DepSet_h3781a8cf__0__Slow \
	Vfalco_top_ID_stage__Slow \
	Vfalco_top_ID_stage__DepSet_hc0460b4c__0__Slow \
	Vfalco_top_ID_stage__DepSet_h78676f51__0__Slow \
	Vfalco_top_mem_access__Slow \
	Vfalco_top_mem_access__DepSet_h030e78f4__0__Slow \
	Vfalco_top_mem_access__DepSet_hb49ca0ac__0__Slow \
	Vfalco_top_pipeline_control_recovery__Slow \
	Vfalco_top_pipeline_control_recovery__DepSet_hd16300d7__0__Slow \
	Vfalco_top_pipeline_control_recovery__DepSet_he707388b__0__Slow \
	Vfalco_top_load_store_unit__Slow \
	Vfalco_top_load_store_unit__DepSet_ha7c8e8f0__0__Slow \
	Vfalco_top_load_store_unit__DepSet_h105f10a8__0__Slow \
	Vfalco_top_alu_muldiv_execute_group__Slow \
	Vfalco_top_alu_muldiv_execute_group__DepSet_h65f17e61__0__Slow \
	Vfalco_top_alu_muldiv_execute_group__DepSet_h52959a19__0__Slow \
	Vfalco_top_csr_file__Slow \
	Vfalco_top_csr_file__DepSet_h3a721662__0__Slow \
	Vfalco_top_csr_file__DepSet_h8c184216__0__Slow \
	Vfalco_top_mem_issue_queue__Slow \
	Vfalco_top_mem_issue_queue__DepSet_h7c8226d2__0__Slow \
	Vfalco_top_mem_issue_queue__DepSet_h49285286__0__Slow \
	Vfalco_top_int_rob_tag_replay_unit__Slow \
	Vfalco_top_int_rob_tag_replay_unit__DepSet_h8d57ac4c__0__Slow \
	Vfalco_top_empty_entry_finder8_wrapper__Slow \
	Vfalco_top_empty_entry_finder8_wrapper__DepSet_h8da49ea1__0__Slow \
	Vfalco_top_empty_entry_finder8_wrapper__DepSet_h2240fc75__0__Slow \
	Vfalco_top_combine_data_unit__Slow \
	Vfalco_top_combine_data_unit__DepSet_hcf243edc__0__Slow \
	Vfalco_top_combine_data_unit__DepSet_ha0f10053__0__Slow \
	Vfalco_top_mem_replay_unit__Slow \
	Vfalco_top_mem_replay_unit__DepSet_h53d672e4__0__Slow \
	Vfalco_top_ALU__Slow \
	Vfalco_top_ALU__DepSet_h6ff0c63d__0__Slow \
	Vfalco_top_ID_stage_io__Slow \
	Vfalco_top_ID_stage_io__DepSet_h70e5b910__0__Slow \
	Vfalco_top_exe_stage_io__Slow \
	Vfalco_top_exe_stage_io__DepSet_h947ef0f1__0__Slow \
	Vfalco_top_register_map_table__Slow \
	Vfalco_top_register_map_table__DepSet_ha6cb98b4__0__Slow \
	Vfalco_top_AGU_io__Slow \
	Vfalco_top_AGU_io__DepSet_h680a9b34__0__Slow \
	Vfalco_top_load_forward_unit__Slow \
	Vfalco_top_load_forward_unit__DepSet_h05c9d4bb__0__Slow \
	Vfalco_top_load_forward_unit__DepSet_hb25e04df__0__Slow \
	Vfalco_top_pipeline_control_recovery_io__Slow \
	Vfalco_top_pipeline_control_recovery_io__DepSet_h5cad465a__0__Slow \
	Vfalco_top_fast_mul__Slow \
	Vfalco_top_fast_mul__DepSet_h9816b2ac__0__Slow \
	Vfalco_top_int_iq_ctr_rob_tag_balance_selector__Slow \
	Vfalco_top_int_iq_ctr_rob_tag_balance_selector__DepSet_he3f43a27__0__Slow \
	Vfalco_top_int_iq_ctr_rob_tag_balance_selector__DepSet_hd4925e5b__0__Slow \
	Vfalco_top_divider__Slow \
	Vfalco_top_divider__DepSet_hb7d88140__0__Slow \
	Vfalco_top_gshare_branch_predictor__Slow \
	Vfalco_top_gshare_branch_predictor__DepSet_hc8bcb4b1__0__Slow \
	Vfalco_top_load_store_unit_io__Slow \
	Vfalco_top_load_store_unit_io__DepSet_haec949d4__0__Slow \
	Vfalco_top_int_issue_queue_io__Slow \
	Vfalco_top_int_issue_queue_io__DepSet_hab4d3158__0__Slow \
	Vfalco_top_physical_register_file__Slow \
	Vfalco_top_physical_register_file__DepSet_h2360a7be__0__Slow \
	Vfalco_top_load_buffer_io__Slow \
	Vfalco_top_load_buffer_io__DepSet_h7931cc9a__0__Slow \
	Vfalco_top_mem_iq_balance_selector_wo_store__Slow \
	Vfalco_top_mem_iq_balance_selector_wo_store__DepSet_h96563263__0__Slow \
	Vfalco_top_mem_iq_balance_selector_wo_store__DepSet_h1ff46617__0__Slow \
	Vfalco_top_last_fetch_store_table__Slow \
	Vfalco_top_last_fetch_store_table__DepSet_h17cb72dd__0__Slow \
	Vfalco_top_prf_freelist__Slow \
	Vfalco_top_prf_freelist__DepSet_h63e2ba6f__0__Slow \
	Vfalco_top_busy_list__Slow \
	Vfalco_top_busy_list__DepSet_h694cf72b__0__Slow \
	Vfalco_top_rename_dispatch_io__Slow \
	Vfalco_top_rename_dispatch_io__DepSet_hffd1a5ea__0__Slow \
	Vfalco_top_decoder__Slow \
	Vfalco_top_decoder__DepSet_h7f0be334__0__Slow \
	Vfalco_top_mem_issue_queue_io__Slow \
	Vfalco_top_mem_issue_queue_io__DepSet_hfbf17cb1__0__Slow \
	Vfalco_top_program_counter__Slow \
	Vfalco_top_program_counter__DepSet_hbf983b8a__0__Slow \
	Vfalco_top_IF_stage_io__Slow \
	Vfalco_top_IF_stage_io__DepSet_ha1851d16__0__Slow \
	Vfalco_top_commit_stage_io__Slow \
	Vfalco_top_commit_stage_io__DepSet_hb3dd7363__0__Slow \
	Vfalco_top_branch_unit__Slow \
	Vfalco_top_branch_unit__DepSet_ha183d5be__0__Slow \
	Vfalco_top_store_buffer_io__Slow \
	Vfalco_top_store_buffer_io__DepSet_h96f8146b__0__Slow \
	Vfalco_top_csr_io__Slow \
	Vfalco_top_csr_io__DepSet_hb10f2992__0__Slow \
	Vfalco_top_mem_access_io__Slow \
	Vfalco_top_mem_access_io__DepSet_h11b55dd5__0__Slow \
	Vfalco_top_store_set_id_table__Slow \
	Vfalco_top_store_set_id_table__DepSet_h548cd758__0__Slow \
	Vfalco_top_store_set_id_table__DepSet_h611b0300__0__Slow \
	Vfalco_top_register_read_io__Slow \
	Vfalco_top_register_read_io__DepSet_hb2d3f3b0__0__Slow \
	Vfalco_top_BTB__Slow \
	Vfalco_top_BTB__DepSet_h6405303b__0__Slow \
	Vfalco_top_BTB__DepSet_hf4df5923__0__Slow \
	Vfalco_top_Picker8_1__Slow \
	Vfalco_top_Picker8_1__DepSet_ha7d79143__0__Slow \
	Vfalco_top_Picker8_1__DepSet_h158063a3__0__Slow \
	Vfalco_top_Picker8_2__Slow \
	Vfalco_top_Picker8_2__DepSet_h840c44cc__0__Slow \
	Vfalco_top_Picker8_2__DepSet_h1ead16b1__0__Slow \
	Vfalco_top_empty_entry_finder8__Slow \
	Vfalco_top_empty_entry_finder8__DepSet_h6f48586e__0__Slow \
	Vfalco_top_empty_entry_finder8__DepSet_hd35f8bb1__0__Slow \
	Vfalco_top_empty_entry_finder8__DepSet_h857e01df__0__Slow \
	Vfalco_top_empty_entry_finder8__DepSet_hcfaf7c1d__0__Slow \
	Vfalco_top_Latest_Picker_2_1__Slow \
	Vfalco_top_Latest_Picker_2_1__DepSet_he92b4e73__0__Slow \
	Vfalco_top_LS_wo_store_Picker8_1__Slow \
	Vfalco_top_LS_wo_store_Picker8_1__DepSet_he802787a__0__Slow \
	Vfalco_top_LS_wo_store_Picker8_1__DepSet_h5929b292__0__Slow \
	Vfalco_top_distri_ram2r1w__E200_A9_D1e__Slow \
	Vfalco_top_distri_ram2r1w__E200_A9_D1e__DepSet_h9f5d1189__0__Slow \
	Vfalco_top_distri_ram2r1w__E200_A9_D15__Slow \
	Vfalco_top_distri_ram2r1w__E200_A9_D15__DepSet_h5994d19a__0__Slow \
	Vfalco_top_sram_dual_port__R8_RBb__Slow \
	Vfalco_top_sram_dual_port__R8_RBb__DepSet_h62b2fcb7__0__Slow \
	Vfalco_top_Picker2_1__Slow \
	Vfalco_top_Picker2_1__DepSet_hc4741880__0__Slow \
	Vfalco_top_Picker2_2__Slow \
	Vfalco_top_Picker2_2__DepSet_h45a2d301__0__Slow \
	Vfalco_top_Picker4_2__Slow \
	Vfalco_top_Picker4_2__DepSet_hef6072c6__0__Slow \
	Vfalco_top_emptry_entry_finder2__Slow \
	Vfalco_top_emptry_entry_finder2__DepSet_ha5f5f610__0__Slow \
	Vfalco_top_emptry_entry_finder4__Slow \
	Vfalco_top_emptry_entry_finder4__DepSet_he1700a35__0__Slow \
	Vfalco_top_LS_wo_store_Picker2_1__Slow \
	Vfalco_top_LS_wo_store_Picker2_1__DepSet_h1332a6e5__0__Slow \

# Generated support classes, fast-path, compile with highest optimization
VM_SUPPORT_FAST += \
	Vfalco_top__Dpi \
	Vfalco_top__Trace__0 \

# Generated support classes, non-fast-path, compile with low/medium optimization
VM_SUPPORT_SLOW += \
	Vfalco_top__Syms \
	Vfalco_top__Trace__0__Slow \
	Vfalco_top__TraceDecls__0__Slow \

# Global classes, need linked once per executable, fast-path, compile with highest optimization
VM_GLOBAL_FAST += \
	verilated \
	verilated_dpi \
	verilated_vcd_c \
	verilated_threads \

# Global classes, need linked once per executable, non-fast-path, compile with low/medium optimization
VM_GLOBAL_SLOW += \


# Verilated -*- Makefile -*-
