// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vfalco_top.h for the primary calling header

#ifndef VERILATED_VFALCO_TOP_STORE_BUFFER_H_
#define VERILATED_VFALCO_TOP_STORE_BUFFER_H_  // guard

#include "verilated.h"
class Vfalco_top_combine_data_unit;
class Vfalco_top_load_forward_unit;


class Vfalco_top__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vfalco_top_store_buffer final : public VerilatedModule {
  public:
    // CELLS
    Vfalco_top_load_forward_unit* __PVT__LFU;
    Vfalco_top_combine_data_unit* __PVT__genblk9__BRA__0__KET____DOT__CDU;
    Vfalco_top_combine_data_unit* __PVT__genblk9__BRA__1__KET____DOT__CDU;
    Vfalco_top_combine_data_unit* __PVT__genblk9__BRA__2__KET____DOT__CDU;
    Vfalco_top_combine_data_unit* __PVT__genblk9__BRA__3__KET____DOT__CDU;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(__PVT__clk,0,0);
        VL_IN8(__PVT__rst,0,0);
        VL_IN8(__PVT__store_resp,1,0);
        CData/*3:0*/ alloc_ptr;
        CData/*3:0*/ __PVT__alloc_pre_0_ptr;
        CData/*3:0*/ __PVT__alloc_pre_1_ptr;
        CData/*3:0*/ retire_ptr;
        CData/*3:0*/ retire_next_ptr;
        CData/*3:0*/ pop_ptr;
        CData/*0:0*/ __PVT__load_forward_hit;
        CData/*3:0*/ __PVT__load_forward_hit_index;
        CData/*3:0*/ __PVT__load_forward_hit_mask;
        CData/*0:0*/ __PVT__pop;
        CData/*0:0*/ __PVT__store_pop;
        CData/*0:0*/ __PVT__allocate_new_entry;
        CData/*3:0*/ __PVT__sdb_input_mask;
        CData/*3:0*/ flush_counter;
        CData/*3:0*/ __Vcellout__genblk9__BRA__0__KET____DOT__CDU__hit_index;
        CData/*0:0*/ __Vcellout__genblk9__BRA__0__KET____DOT__CDU__hit;
        CData/*3:0*/ __Vcellout__genblk9__BRA__1__KET____DOT__CDU__hit_index;
        CData/*0:0*/ __Vcellout__genblk9__BRA__1__KET____DOT__CDU__hit;
        CData/*3:0*/ __Vcellout__genblk9__BRA__2__KET____DOT__CDU__hit_index;
        CData/*0:0*/ __Vcellout__genblk9__BRA__2__KET____DOT__CDU__hit;
        CData/*3:0*/ __Vcellout__genblk9__BRA__3__KET____DOT__CDU__hit_index;
        CData/*0:0*/ __Vcellout__genblk9__BRA__3__KET____DOT__CDU__hit;
        CData/*0:0*/ __Vfunc_IsBrROBKill__0__Vfuncout;
        CData/*5:0*/ __Vfunc_IsBrROBKill__0__rob_tag;
        CData/*0:0*/ __Vfunc_IsBrROBKill__1__Vfuncout;
        CData/*5:0*/ __Vfunc_IsBrROBKill__1__rob_tag;
        CData/*0:0*/ __Vfunc_IsBrROBKill__2__Vfuncout;
        CData/*5:0*/ __Vfunc_IsBrROBKill__2__rob_tag;
        CData/*0:0*/ __Vfunc_IsBrROBKill__3__Vfuncout;
        CData/*5:0*/ __Vfunc_IsBrROBKill__3__rob_tag;
        CData/*0:0*/ __Vfunc_IsBrROBKill__4__Vfuncout;
        CData/*5:0*/ __Vfunc_IsBrROBKill__4__rob_tag;
        CData/*0:0*/ __Vfunc_IsBrROBKill__5__Vfuncout;
        CData/*5:0*/ __Vfunc_IsBrROBKill__5__rob_tag;
        CData/*0:0*/ __Vfunc_IsBrROBKill__6__Vfuncout;
        CData/*5:0*/ __Vfunc_IsBrROBKill__6__rob_tag;
        CData/*0:0*/ __Vfunc_IsBrROBKill__7__Vfuncout;
        CData/*5:0*/ __Vfunc_IsBrROBKill__7__rob_tag;
        CData/*0:0*/ __Vfunc_IsBrROBKill__8__Vfuncout;
        CData/*5:0*/ __Vfunc_IsBrROBKill__8__rob_tag;
        CData/*0:0*/ __Vfunc_IsBrROBKill__9__Vfuncout;
        CData/*5:0*/ __Vfunc_IsBrROBKill__9__rob_tag;
        CData/*0:0*/ __Vfunc_IsBrROBKill__10__Vfuncout;
        CData/*5:0*/ __Vfunc_IsBrROBKill__10__rob_tag;
        CData/*0:0*/ __Vfunc_IsBrROBKill__11__Vfuncout;
        CData/*5:0*/ __Vfunc_IsBrROBKill__11__rob_tag;
        CData/*0:0*/ __Vfunc_IsBrROBKill__12__Vfuncout;
        CData/*5:0*/ __Vfunc_IsBrROBKill__12__rob_tag;
        CData/*0:0*/ __Vfunc_IsBrROBKill__13__Vfuncout;
        CData/*5:0*/ __Vfunc_IsBrROBKill__13__rob_tag;
        CData/*0:0*/ __Vfunc_IsBrROBKill__14__Vfuncout;
        CData/*5:0*/ __Vfunc_IsBrROBKill__14__rob_tag;
        CData/*0:0*/ __Vfunc_IsBrROBKill__15__Vfuncout;
        CData/*5:0*/ __Vfunc_IsBrROBKill__15__rob_tag;
        CData/*3:0*/ __Vdly__alloc_ptr;
        CData/*3:0*/ __Vdly__retire_ptr;
        CData/*3:0*/ __Vdly__pop_ptr;
        CData/*0:0*/ __VdlySet__SDB_addr__v0;
        CData/*0:0*/ __VdlySet__SDB_addr__v1;
        CData/*3:0*/ __VdlyVal__st_mask__v1;
        CData/*5:0*/ __VdlyVal__SDB_rob_tag__v1;
    };
    struct {
        CData/*0:0*/ __VdlyVal__is_non_idempotent__v1;
        CData/*0:0*/ __VdlySet__SDB_addr__v2;
        CData/*3:0*/ __VdlyVal__st_mask__v2;
        CData/*5:0*/ __VdlyVal__SDB_rob_tag__v2;
        CData/*0:0*/ __VdlyVal__is_non_idempotent__v2;
        CData/*0:0*/ __VdlySet__SDB_addr__v3;
        CData/*0:0*/ __VdlySet__SDB_addr__v4;
        CData/*3:0*/ __VdlyVal__st_mask__v4;
        CData/*5:0*/ __VdlyVal__SDB_rob_tag__v4;
        CData/*0:0*/ __VdlyVal__is_non_idempotent__v4;
        CData/*0:0*/ __VdlySet__SDB_addr__v5;
        CData/*3:0*/ __VdlyVal__st_mask__v5;
        CData/*5:0*/ __VdlyVal__SDB_rob_tag__v5;
        CData/*0:0*/ __VdlyVal__is_non_idempotent__v5;
        CData/*0:0*/ __VdlySet__SDB_addr__v6;
        CData/*0:0*/ __VdlySet__SDB_addr__v7;
        CData/*3:0*/ __VdlyVal__st_mask__v7;
        CData/*5:0*/ __VdlyVal__SDB_rob_tag__v7;
        CData/*0:0*/ __VdlyVal__is_non_idempotent__v7;
        CData/*0:0*/ __VdlySet__SDB_addr__v8;
        CData/*3:0*/ __VdlyVal__st_mask__v8;
        CData/*5:0*/ __VdlyVal__SDB_rob_tag__v8;
        CData/*0:0*/ __VdlyVal__is_non_idempotent__v8;
        CData/*0:0*/ __VdlySet__SDB_addr__v9;
        CData/*0:0*/ __VdlySet__SDB_addr__v10;
        CData/*3:0*/ __VdlyVal__st_mask__v10;
        CData/*5:0*/ __VdlyVal__SDB_rob_tag__v10;
        CData/*0:0*/ __VdlyVal__is_non_idempotent__v10;
        CData/*0:0*/ __VdlySet__SDB_addr__v11;
        CData/*3:0*/ __VdlyVal__st_mask__v11;
        CData/*5:0*/ __VdlyVal__SDB_rob_tag__v11;
        CData/*0:0*/ __VdlyVal__is_non_idempotent__v11;
        CData/*0:0*/ __VdlySet__SDB_addr__v12;
        CData/*0:0*/ __VdlySet__SDB_addr__v13;
        CData/*3:0*/ __VdlyVal__st_mask__v13;
        CData/*5:0*/ __VdlyVal__SDB_rob_tag__v13;
        CData/*0:0*/ __VdlyVal__is_non_idempotent__v13;
        CData/*0:0*/ __VdlySet__SDB_addr__v14;
        CData/*3:0*/ __VdlyVal__st_mask__v14;
        CData/*5:0*/ __VdlyVal__SDB_rob_tag__v14;
        CData/*0:0*/ __VdlyVal__is_non_idempotent__v14;
        CData/*0:0*/ __VdlySet__SDB_addr__v15;
        CData/*0:0*/ __VdlySet__SDB_addr__v16;
        CData/*3:0*/ __VdlyVal__st_mask__v16;
        CData/*5:0*/ __VdlyVal__SDB_rob_tag__v16;
        CData/*0:0*/ __VdlyVal__is_non_idempotent__v16;
        CData/*0:0*/ __VdlySet__SDB_addr__v17;
        CData/*3:0*/ __VdlyVal__st_mask__v17;
        CData/*5:0*/ __VdlyVal__SDB_rob_tag__v17;
        CData/*0:0*/ __VdlyVal__is_non_idempotent__v17;
        CData/*0:0*/ __VdlySet__SDB_addr__v18;
        CData/*0:0*/ __VdlySet__SDB_addr__v19;
        CData/*3:0*/ __VdlyVal__st_mask__v19;
        CData/*5:0*/ __VdlyVal__SDB_rob_tag__v19;
        CData/*0:0*/ __VdlyVal__is_non_idempotent__v19;
        CData/*0:0*/ __VdlySet__SDB_addr__v20;
        CData/*3:0*/ __VdlyVal__st_mask__v20;
        CData/*5:0*/ __VdlyVal__SDB_rob_tag__v20;
        CData/*0:0*/ __VdlyVal__is_non_idempotent__v20;
        CData/*0:0*/ __VdlySet__SDB_addr__v21;
        CData/*0:0*/ __VdlySet__SDB_addr__v22;
        CData/*3:0*/ __VdlyVal__st_mask__v22;
        CData/*5:0*/ __VdlyVal__SDB_rob_tag__v22;
        CData/*0:0*/ __VdlyVal__is_non_idempotent__v22;
    };
    struct {
        CData/*0:0*/ __VdlySet__SDB_addr__v23;
        CData/*3:0*/ __VdlyVal__st_mask__v23;
        CData/*5:0*/ __VdlyVal__SDB_rob_tag__v23;
        CData/*0:0*/ __VdlyVal__is_non_idempotent__v23;
        CData/*0:0*/ __VdlySet__SDB_addr__v24;
        CData/*0:0*/ __VdlySet__SDB_addr__v25;
        CData/*3:0*/ __VdlyVal__st_mask__v25;
        CData/*5:0*/ __VdlyVal__SDB_rob_tag__v25;
        CData/*0:0*/ __VdlyVal__is_non_idempotent__v25;
        CData/*0:0*/ __VdlySet__SDB_addr__v26;
        CData/*3:0*/ __VdlyVal__st_mask__v26;
        CData/*5:0*/ __VdlyVal__SDB_rob_tag__v26;
        CData/*0:0*/ __VdlyVal__is_non_idempotent__v26;
        CData/*0:0*/ __VdlySet__SDB_addr__v27;
        CData/*0:0*/ __VdlySet__SDB_addr__v28;
        CData/*3:0*/ __VdlyVal__st_mask__v28;
        CData/*5:0*/ __VdlyVal__SDB_rob_tag__v28;
        CData/*0:0*/ __VdlyVal__is_non_idempotent__v28;
        CData/*0:0*/ __VdlySet__SDB_addr__v29;
        CData/*3:0*/ __VdlyVal__st_mask__v29;
        CData/*5:0*/ __VdlyVal__SDB_rob_tag__v29;
        CData/*0:0*/ __VdlyVal__is_non_idempotent__v29;
        CData/*0:0*/ __VdlySet__SDB_addr__v30;
        CData/*0:0*/ __VdlySet__SDB_addr__v31;
        CData/*3:0*/ __VdlyVal__st_mask__v31;
        CData/*5:0*/ __VdlyVal__SDB_rob_tag__v31;
        CData/*0:0*/ __VdlyVal__is_non_idempotent__v31;
        CData/*0:0*/ __VdlySet__SDB_addr__v32;
        CData/*3:0*/ __VdlyVal__st_mask__v32;
        CData/*5:0*/ __VdlyVal__SDB_rob_tag__v32;
        CData/*0:0*/ __VdlyVal__is_non_idempotent__v32;
        CData/*0:0*/ __VdlySet__SDB_addr__v33;
        CData/*0:0*/ __VdlySet__SDB_addr__v34;
        CData/*3:0*/ __VdlyVal__st_mask__v34;
        CData/*5:0*/ __VdlyVal__SDB_rob_tag__v34;
        CData/*0:0*/ __VdlyVal__is_non_idempotent__v34;
        CData/*0:0*/ __VdlySet__SDB_addr__v35;
        CData/*3:0*/ __VdlyVal__st_mask__v35;
        CData/*5:0*/ __VdlyVal__SDB_rob_tag__v35;
        CData/*0:0*/ __VdlyVal__is_non_idempotent__v35;
        CData/*0:0*/ __VdlySet__SDB_addr__v36;
        CData/*0:0*/ __VdlySet__SDB_addr__v37;
        CData/*3:0*/ __VdlyVal__st_mask__v37;
        CData/*5:0*/ __VdlyVal__SDB_rob_tag__v37;
        CData/*0:0*/ __VdlyVal__is_non_idempotent__v37;
        CData/*0:0*/ __VdlySet__SDB_addr__v38;
        CData/*3:0*/ __VdlyVal__st_mask__v38;
        CData/*5:0*/ __VdlyVal__SDB_rob_tag__v38;
        CData/*0:0*/ __VdlyVal__is_non_idempotent__v38;
        CData/*0:0*/ __VdlySet__SDB_addr__v39;
        CData/*0:0*/ __VdlySet__SDB_addr__v40;
        CData/*3:0*/ __VdlyVal__st_mask__v40;
        CData/*5:0*/ __VdlyVal__SDB_rob_tag__v40;
        CData/*0:0*/ __VdlyVal__is_non_idempotent__v40;
        CData/*0:0*/ __VdlySet__SDB_addr__v41;
        CData/*3:0*/ __VdlyVal__st_mask__v41;
        CData/*5:0*/ __VdlyVal__SDB_rob_tag__v41;
        CData/*0:0*/ __VdlyVal__is_non_idempotent__v41;
        CData/*0:0*/ __VdlySet__SDB_addr__v42;
        CData/*0:0*/ __VdlySet__SDB_addr__v43;
        CData/*3:0*/ __VdlyVal__st_mask__v43;
        CData/*5:0*/ __VdlyVal__SDB_rob_tag__v43;
        CData/*0:0*/ __VdlyVal__is_non_idempotent__v43;
        CData/*0:0*/ __VdlySet__SDB_addr__v44;
    };
    struct {
        CData/*3:0*/ __VdlyVal__st_mask__v44;
        CData/*5:0*/ __VdlyVal__SDB_rob_tag__v44;
        CData/*0:0*/ __VdlyVal__is_non_idempotent__v44;
        CData/*0:0*/ __VdlySet__SDB_addr__v45;
        CData/*0:0*/ __VdlySet__SDB_addr__v46;
        CData/*3:0*/ __VdlyVal__st_mask__v46;
        CData/*5:0*/ __VdlyVal__SDB_rob_tag__v46;
        CData/*0:0*/ __VdlyVal__is_non_idempotent__v46;
        CData/*0:0*/ __VdlySet__SDB_addr__v47;
        CData/*3:0*/ __VdlyVal__st_mask__v47;
        CData/*5:0*/ __VdlyVal__SDB_rob_tag__v47;
        CData/*0:0*/ __VdlyVal__is_non_idempotent__v47;
        CData/*0:0*/ __VdlyVal__valid__v0;
        CData/*0:0*/ __VdlySet__valid__v0;
        CData/*0:0*/ __VdlyVal__valid__v1;
        CData/*0:0*/ __VdlySet__valid__v1;
        CData/*0:0*/ __VdlyVal__valid__v2;
        CData/*0:0*/ __VdlySet__valid__v2;
        CData/*0:0*/ __VdlyVal__valid__v3;
        CData/*0:0*/ __VdlySet__valid__v3;
        CData/*0:0*/ __VdlyVal__valid__v4;
        CData/*0:0*/ __VdlySet__valid__v4;
        CData/*0:0*/ __VdlyVal__valid__v5;
        CData/*0:0*/ __VdlySet__valid__v5;
        CData/*0:0*/ __VdlyVal__valid__v6;
        CData/*0:0*/ __VdlySet__valid__v6;
        CData/*0:0*/ __VdlyVal__valid__v7;
        CData/*0:0*/ __VdlySet__valid__v7;
        CData/*0:0*/ __VdlyVal__valid__v8;
        CData/*0:0*/ __VdlySet__valid__v8;
        CData/*0:0*/ __VdlyVal__valid__v9;
        CData/*0:0*/ __VdlySet__valid__v9;
        CData/*0:0*/ __VdlyVal__valid__v10;
        CData/*0:0*/ __VdlySet__valid__v10;
        CData/*0:0*/ __VdlyVal__valid__v11;
        CData/*0:0*/ __VdlySet__valid__v11;
        CData/*0:0*/ __VdlyVal__valid__v12;
        CData/*0:0*/ __VdlySet__valid__v12;
        CData/*0:0*/ __VdlyVal__valid__v13;
        CData/*0:0*/ __VdlySet__valid__v13;
        CData/*0:0*/ __VdlyVal__valid__v14;
        CData/*0:0*/ __VdlySet__valid__v14;
        CData/*0:0*/ __VdlyVal__valid__v15;
        CData/*0:0*/ __VdlySet__valid__v15;
        CData/*0:0*/ __VdlyVal__retirement__v0;
        CData/*0:0*/ __VdlySet__retirement__v0;
        CData/*0:0*/ __VdlyVal__retirement__v1;
        CData/*0:0*/ __VdlySet__retirement__v1;
        CData/*0:0*/ __VdlyVal__retirement__v2;
        CData/*0:0*/ __VdlySet__retirement__v2;
        CData/*0:0*/ __VdlyVal__retirement__v3;
        CData/*0:0*/ __VdlySet__retirement__v3;
        CData/*0:0*/ __VdlyVal__retirement__v4;
        CData/*0:0*/ __VdlySet__retirement__v4;
        CData/*0:0*/ __VdlyVal__retirement__v5;
        CData/*0:0*/ __VdlySet__retirement__v5;
        CData/*0:0*/ __VdlyVal__retirement__v6;
        CData/*0:0*/ __VdlySet__retirement__v6;
        CData/*0:0*/ __VdlyVal__retirement__v7;
        CData/*0:0*/ __VdlySet__retirement__v7;
        CData/*0:0*/ __VdlyVal__retirement__v8;
        CData/*0:0*/ __VdlySet__retirement__v8;
        CData/*0:0*/ __VdlyVal__retirement__v9;
        CData/*0:0*/ __VdlySet__retirement__v9;
    };
    struct {
        CData/*0:0*/ __VdlyVal__retirement__v10;
        CData/*0:0*/ __VdlySet__retirement__v10;
        CData/*0:0*/ __VdlyVal__retirement__v11;
        CData/*0:0*/ __VdlySet__retirement__v11;
        CData/*0:0*/ __VdlyVal__retirement__v12;
        CData/*0:0*/ __VdlySet__retirement__v12;
        CData/*0:0*/ __VdlyVal__retirement__v13;
        CData/*0:0*/ __VdlySet__retirement__v13;
        CData/*0:0*/ __VdlyVal__retirement__v14;
        CData/*0:0*/ __VdlySet__retirement__v14;
        CData/*0:0*/ __VdlyVal__retirement__v15;
        CData/*0:0*/ __VdlySet__retirement__v15;
        SData/*15:0*/ flush_vec;
        SData/*14:0*/ __Vfunc_IsBrROBKill__0__branch_recovery_flush;
        SData/*14:0*/ __Vfunc_IsBrROBKill__1__branch_recovery_flush;
        SData/*14:0*/ __Vfunc_IsBrROBKill__2__branch_recovery_flush;
        SData/*14:0*/ __Vfunc_IsBrROBKill__3__branch_recovery_flush;
        SData/*14:0*/ __Vfunc_IsBrROBKill__4__branch_recovery_flush;
        SData/*14:0*/ __Vfunc_IsBrROBKill__5__branch_recovery_flush;
        SData/*14:0*/ __Vfunc_IsBrROBKill__6__branch_recovery_flush;
        SData/*14:0*/ __Vfunc_IsBrROBKill__7__branch_recovery_flush;
        SData/*14:0*/ __Vfunc_IsBrROBKill__8__branch_recovery_flush;
        SData/*14:0*/ __Vfunc_IsBrROBKill__9__branch_recovery_flush;
        SData/*14:0*/ __Vfunc_IsBrROBKill__10__branch_recovery_flush;
        SData/*14:0*/ __Vfunc_IsBrROBKill__11__branch_recovery_flush;
        SData/*14:0*/ __Vfunc_IsBrROBKill__12__branch_recovery_flush;
        SData/*14:0*/ __Vfunc_IsBrROBKill__13__branch_recovery_flush;
        SData/*14:0*/ __Vfunc_IsBrROBKill__14__branch_recovery_flush;
        SData/*14:0*/ __Vfunc_IsBrROBKill__15__branch_recovery_flush;
        IData/*31:0*/ __PVT__load_forward_data;
        IData/*31:0*/ __PVT__sdb_input_data;
        IData/*31:0*/ __PVT__i;
        IData/*31:0*/ __VdlyVal__SDB_addr__v1;
        IData/*31:0*/ __VdlyVal__SDB_data__v1;
        IData/*31:0*/ __VdlyVal__SDB_addr__v2;
        IData/*31:0*/ __VdlyVal__SDB_data__v2;
        IData/*31:0*/ __VdlyVal__SDB_addr__v4;
        IData/*31:0*/ __VdlyVal__SDB_data__v4;
        IData/*31:0*/ __VdlyVal__SDB_addr__v5;
        IData/*31:0*/ __VdlyVal__SDB_data__v5;
        IData/*31:0*/ __VdlyVal__SDB_addr__v7;
        IData/*31:0*/ __VdlyVal__SDB_data__v7;
        IData/*31:0*/ __VdlyVal__SDB_addr__v8;
        IData/*31:0*/ __VdlyVal__SDB_data__v8;
        IData/*31:0*/ __VdlyVal__SDB_addr__v10;
        IData/*31:0*/ __VdlyVal__SDB_data__v10;
        IData/*31:0*/ __VdlyVal__SDB_addr__v11;
        IData/*31:0*/ __VdlyVal__SDB_data__v11;
        IData/*31:0*/ __VdlyVal__SDB_addr__v13;
        IData/*31:0*/ __VdlyVal__SDB_data__v13;
        IData/*31:0*/ __VdlyVal__SDB_addr__v14;
        IData/*31:0*/ __VdlyVal__SDB_data__v14;
        IData/*31:0*/ __VdlyVal__SDB_addr__v16;
        IData/*31:0*/ __VdlyVal__SDB_data__v16;
        IData/*31:0*/ __VdlyVal__SDB_addr__v17;
        IData/*31:0*/ __VdlyVal__SDB_data__v17;
        IData/*31:0*/ __VdlyVal__SDB_addr__v19;
        IData/*31:0*/ __VdlyVal__SDB_data__v19;
        IData/*31:0*/ __VdlyVal__SDB_addr__v20;
        IData/*31:0*/ __VdlyVal__SDB_data__v20;
        IData/*31:0*/ __VdlyVal__SDB_addr__v22;
        IData/*31:0*/ __VdlyVal__SDB_data__v22;
        IData/*31:0*/ __VdlyVal__SDB_addr__v23;
        IData/*31:0*/ __VdlyVal__SDB_data__v23;
    };
    struct {
        IData/*31:0*/ __VdlyVal__SDB_addr__v25;
        IData/*31:0*/ __VdlyVal__SDB_data__v25;
        IData/*31:0*/ __VdlyVal__SDB_addr__v26;
        IData/*31:0*/ __VdlyVal__SDB_data__v26;
        IData/*31:0*/ __VdlyVal__SDB_addr__v28;
        IData/*31:0*/ __VdlyVal__SDB_data__v28;
        IData/*31:0*/ __VdlyVal__SDB_addr__v29;
        IData/*31:0*/ __VdlyVal__SDB_data__v29;
        IData/*31:0*/ __VdlyVal__SDB_addr__v31;
        IData/*31:0*/ __VdlyVal__SDB_data__v31;
        IData/*31:0*/ __VdlyVal__SDB_addr__v32;
        IData/*31:0*/ __VdlyVal__SDB_data__v32;
        IData/*31:0*/ __VdlyVal__SDB_addr__v34;
        IData/*31:0*/ __VdlyVal__SDB_data__v34;
        IData/*31:0*/ __VdlyVal__SDB_addr__v35;
        IData/*31:0*/ __VdlyVal__SDB_data__v35;
        IData/*31:0*/ __VdlyVal__SDB_addr__v37;
        IData/*31:0*/ __VdlyVal__SDB_data__v37;
        IData/*31:0*/ __VdlyVal__SDB_addr__v38;
        IData/*31:0*/ __VdlyVal__SDB_data__v38;
        IData/*31:0*/ __VdlyVal__SDB_addr__v40;
        IData/*31:0*/ __VdlyVal__SDB_data__v40;
        IData/*31:0*/ __VdlyVal__SDB_addr__v41;
        IData/*31:0*/ __VdlyVal__SDB_data__v41;
        IData/*31:0*/ __VdlyVal__SDB_addr__v43;
        IData/*31:0*/ __VdlyVal__SDB_data__v43;
        IData/*31:0*/ __VdlyVal__SDB_addr__v44;
        IData/*31:0*/ __VdlyVal__SDB_data__v44;
        IData/*31:0*/ __VdlyVal__SDB_addr__v46;
        IData/*31:0*/ __VdlyVal__SDB_data__v46;
        IData/*31:0*/ __VdlyVal__SDB_addr__v47;
        IData/*31:0*/ __VdlyVal__SDB_data__v47;
        VL_OUTW(__PVT__store_req,68,0,3);
        VlUnpacked<IData/*31:0*/, 16> SDB_data;
        VlUnpacked<IData/*31:0*/, 16> SDB_addr;
        VlUnpacked<CData/*3:0*/, 16> st_mask;
        VlUnpacked<CData/*5:0*/, 16> SDB_rob_tag;
        VlUnpacked<CData/*0:0*/, 16> retirement;
        VlUnpacked<CData/*0:0*/, 16> valid;
        VlUnpacked<CData/*0:0*/, 16> is_non_idempotent;
        VlUnpacked<CData/*0:0*/, 16> __PVT__load_store_addr_match;
        VlUnpacked<CData/*0:0*/, 16> __PVT__entry_is_non_idempotent;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 16>, 4> __PVT__sdb_input_match;
        VlUnpacked<CData/*3:0*/, 15> __PVT__temp_ptr;
        VlUnpacked<CData/*7:0*/, 4> __PVT__sdb_input_byte_data;
        VlUnpacked<CData/*0:0*/, 4> __PVT__byte_match;
        VlUnpacked<CData/*3:0*/, 4> __PVT__byte_match_index;
        VlUnpacked<CData/*0:0*/, 16> __Vcellinp__genblk9__BRA__0__KET____DOT__CDU__match;
        VlUnpacked<CData/*0:0*/, 16> __Vcellinp__genblk9__BRA__1__KET____DOT__CDU__match;
        VlUnpacked<CData/*0:0*/, 16> __Vcellinp__genblk9__BRA__2__KET____DOT__CDU__match;
        VlUnpacked<CData/*0:0*/, 16> __Vcellinp__genblk9__BRA__3__KET____DOT__CDU__match;
    };

    // INTERNAL VARIABLES
    Vfalco_top__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vfalco_top_store_buffer(Vfalco_top__Syms* symsp, const char* v__name);
    ~Vfalco_top_store_buffer();
    VL_UNCOPYABLE(Vfalco_top_store_buffer);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
