// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design implementation internals
// See Vfalco_top.h for the primary calling header

#include "Vfalco_top__pch.h"
#include "Vfalco_top_int_issue_queue.h"

VL_ATTR_COLD void Vfalco_top_int_issue_queue___ctor_var_reset(Vfalco_top_int_issue_queue* vlSelf) {
    (void)vlSelf;  // Prevent unused variable warning
    Vfalco_top__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+          Vfalco_top_int_issue_queue___ctor_var_reset\n"); );
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    vlSelf->__PVT__clk = VL_RAND_RESET_I(1);
    vlSelf->__PVT__rst = VL_RAND_RESET_I(1);
    vlSelf->__PVT__muldiv_busy = VL_RAND_RESET_I(1);
    vlSelf->__PVT__i = VL_RAND_RESET_I(32);
    vlSelf->__PVT__counter = VL_RAND_RESET_I(4);
    for (int __Vi0 = 0; __Vi0 < 8; ++__Vi0) {
        VL_RAND_RESET_W(205, vlSelf->__PVT__issue_slot[__Vi0]);
    }
    for (int __Vi0 = 0; __Vi0 < 8; ++__Vi0) {
        vlSelf->valid[__Vi0] = VL_RAND_RESET_I(1);
    }
    for (int __Vi0 = 0; __Vi0 < 8; ++__Vi0) {
        vlSelf->rs1_ready[__Vi0] = VL_RAND_RESET_I(1);
    }
    for (int __Vi0 = 0; __Vi0 < 8; ++__Vi0) {
        vlSelf->rs2_ready[__Vi0] = VL_RAND_RESET_I(1);
    }
    vlSelf->__PVT__replay_issue_first = VL_RAND_RESET_I(1);
    vlSelf->__PVT__wake_up_stall_issue_instr0_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__wake_up_stall_issue_instr1_valid = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(205, vlSelf->__PVT__wake_up_stall_issue_instr0_pack);
    VL_RAND_RESET_W(205, vlSelf->__PVT__wake_up_stall_issue_instr1_pack);
    vlSelf->__PVT__replay_issue_instr0_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__replay_issue_instr1_valid = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(205, vlSelf->__PVT__replay_issue_instr0_pack);
    VL_RAND_RESET_W(205, vlSelf->__PVT__replay_issue_instr1_pack);
    vlSelf->__PVT__replay_fifo_issue_muldiv = VL_RAND_RESET_I(1);
    for (int __Vi0 = 0; __Vi0 < 8; ++__Vi0) {
        vlSelf->issue_ready[__Vi0] = VL_RAND_RESET_I(1);
    }
    for (int __Vi0 = 0; __Vi0 < 8; ++__Vi0) {
        vlSelf->__PVT__issue_rs1[__Vi0] = VL_RAND_RESET_I(1);
    }
    for (int __Vi0 = 0; __Vi0 < 8; ++__Vi0) {
        vlSelf->__PVT__issue_rs2[__Vi0] = VL_RAND_RESET_I(1);
    }
    for (int __Vi0 = 0; __Vi0 < 8; ++__Vi0) {
        vlSelf->__PVT__entry_is_csr_instr[__Vi0] = VL_RAND_RESET_I(1);
    }
    for (int __Vi0 = 0; __Vi0 < 8; ++__Vi0) {
        vlSelf->__PVT__entry_is_ctrl_instr[__Vi0] = VL_RAND_RESET_I(1);
    }
    for (int __Vi0 = 0; __Vi0 < 8; ++__Vi0) {
        vlSelf->__PVT__entry_is_muldiv_instr[__Vi0] = VL_RAND_RESET_I(1);
    }
    for (int __Vi0 = 0; __Vi0 < 8; ++__Vi0) {
        vlSelf->__PVT__entry_is_critical[__Vi0] = VL_RAND_RESET_I(1);
    }
    vlSelf->__PVT__issue_slot_idx0 = VL_RAND_RESET_I(3);
    vlSelf->__PVT__issue_slot_idx1 = VL_RAND_RESET_I(3);
    vlSelf->__PVT__issue_slot_idx0_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__issue_slot_idx1_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__muldiv_issuable = VL_RAND_RESET_I(1);
    vlSelf->__PVT__dispatch_slot_idx0 = VL_RAND_RESET_I(3);
    vlSelf->__PVT__dispatch_slot_idx1 = VL_RAND_RESET_I(3);
    vlSelf->__PVT__allocatable_slot_idx0 = VL_RAND_RESET_I(3);
    vlSelf->__PVT__allocatable_slot_idx1 = VL_RAND_RESET_I(3);
    vlSelf->__PVT__allocatable_slot_idx0_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__allocatable_slot_idx1_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__allocatable_slot_idx0_valid_reg = VL_RAND_RESET_I(1);
    vlSelf->__PVT__allocatable_slot_idx1_valid_reg = VL_RAND_RESET_I(1);
    vlSelf->__PVT__dispatch_instr0_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__dispatch_instr1_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__issue_lock = VL_RAND_RESET_I(1);
    vlSelf->__Vcellinp__INT_selector__load_wake_up_kill = VL_RAND_RESET_I(1);
    vlSelf->__Vcellinp__INT_selector__branch_miss_flush = VL_RAND_RESET_I(1);
    vlSelf->__Vcellinp__INT_selector__issue_replay = VL_RAND_RESET_I(1);
    vlSelf->__Vcellinp__INT_selector__non_posion_issue = VL_RAND_RESET_I(1);
    vlSelf->__Vcellinp__INT_selector__recovery_flush = VL_RAND_RESET_I(1);
    vlSelf->__Vcellinp__INT_selector__icache_miss = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(205, vlSelf->__Vcellinp__Replay_Unit__issue_instr1_pack);
    VL_RAND_RESET_W(205, vlSelf->__Vcellinp__Replay_Unit__issue_instr0_pack);
    vlSelf->__Vcellinp__Replay_Unit__issue_instr1_valid = VL_RAND_RESET_I(1);
    vlSelf->__Vcellinp__Replay_Unit__issue_instr0_valid = VL_RAND_RESET_I(1);
    vlSelf->__Vcellinp__Replay_Unit__cur_lsu_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vcellinp__Replay_Unit__cur_commit_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vcellinp__Replay_Unit__replay_muldiv_stall = VL_RAND_RESET_I(1);
    vlSelf->__Vcellinp__Replay_Unit__load_depend_replay = VL_RAND_RESET_I(1);
    vlSelf->__Vcellinp__Replay_Unit__load_wake_up_predict_failed = VL_RAND_RESET_I(1);
    vlSelf->__Vcellinp__Replay_Unit__load_wake_up_failed_stall = VL_RAND_RESET_I(1);
    vlSelf->__Vcellinp__Replay_Unit__recovery_stall = VL_RAND_RESET_I(1);
    vlSelf->__Vcellinp__Replay_Unit__recovery_flush_BCAST = VL_RAND_RESET_I(15);
    vlSelf->__Vfunc_IsBrROBKill__0__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_IsBrROBKill__0__branch_recovery_flush = VL_RAND_RESET_I(15);
    vlSelf->__Vfunc_IsBrROBKill__0__rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_IsBrROBKill__1__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_IsBrROBKill__1__branch_recovery_flush = VL_RAND_RESET_I(15);
    vlSelf->__Vfunc_IsBrROBKill__1__rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_IsBrROBKill__2__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_IsBrROBKill__2__branch_recovery_flush = VL_RAND_RESET_I(15);
    vlSelf->__Vfunc_IsBrROBKill__2__rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_IsBrROBKill__3__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_IsBrROBKill__3__branch_recovery_flush = VL_RAND_RESET_I(15);
    vlSelf->__Vfunc_IsBrROBKill__3__rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_IsBrROBKill__4__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_IsBrROBKill__4__branch_recovery_flush = VL_RAND_RESET_I(15);
    vlSelf->__Vfunc_IsBrROBKill__4__rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_IsBrROBKill__5__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_IsBrROBKill__5__branch_recovery_flush = VL_RAND_RESET_I(15);
    vlSelf->__Vfunc_IsBrROBKill__5__rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_IsBrROBKill__6__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_IsBrROBKill__6__branch_recovery_flush = VL_RAND_RESET_I(15);
    vlSelf->__Vfunc_IsBrROBKill__6__rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_IsBrROBKill__7__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_IsBrROBKill__7__branch_recovery_flush = VL_RAND_RESET_I(15);
    vlSelf->__Vfunc_IsBrROBKill__7__rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_IsBrROBKill__8__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_IsBrROBKill__8__branch_recovery_flush = VL_RAND_RESET_I(15);
    vlSelf->__Vfunc_IsBrROBKill__8__rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_IsBrROBKill__9__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_IsBrROBKill__9__branch_recovery_flush = VL_RAND_RESET_I(15);
    vlSelf->__Vfunc_IsBrROBKill__9__rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_IsBrROBKill__10__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_IsBrROBKill__10__branch_recovery_flush = VL_RAND_RESET_I(15);
    vlSelf->__Vfunc_IsBrROBKill__10__rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_IsBrROBKill__11__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_IsBrROBKill__11__branch_recovery_flush = VL_RAND_RESET_I(15);
    vlSelf->__Vfunc_IsBrROBKill__11__rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_IsBrROBKill__12__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_IsBrROBKill__12__branch_recovery_flush = VL_RAND_RESET_I(15);
    vlSelf->__Vfunc_IsBrROBKill__12__rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_IsBrROBKill__13__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_IsBrROBKill__13__branch_recovery_flush = VL_RAND_RESET_I(15);
    vlSelf->__Vfunc_IsBrROBKill__13__rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_IsBrROBKill__14__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_IsBrROBKill__14__branch_recovery_flush = VL_RAND_RESET_I(15);
    vlSelf->__Vfunc_IsBrROBKill__14__rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_IsBrROBKill__15__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_IsBrROBKill__15__branch_recovery_flush = VL_RAND_RESET_I(15);
    vlSelf->__Vfunc_IsBrROBKill__15__rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_bypass_network__16__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_bypass_network__16__prf_addr = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_bypass_network__16__ready = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_bypass_network__17__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_bypass_network__17__prf_addr = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_bypass_network__17__ready = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_wakeup_network__18__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_wakeup_network__18__prf_addr = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_bypass_network__19__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_bypass_network__19__prf_addr = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_bypass_network__19__ready = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_bypass_network__20__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_bypass_network__20__prf_addr = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_bypass_network__20__ready = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_wakeup_network__21__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_wakeup_network__21__prf_addr = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_bypass_network__22__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_bypass_network__22__prf_addr = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_bypass_network__22__ready = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_bypass_network__23__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_bypass_network__23__prf_addr = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_bypass_network__23__ready = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_wakeup_network__24__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_wakeup_network__24__prf_addr = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_bypass_network__25__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_bypass_network__25__prf_addr = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_bypass_network__25__ready = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_bypass_network__26__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_bypass_network__26__prf_addr = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_bypass_network__26__ready = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_wakeup_network__27__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_wakeup_network__27__prf_addr = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_bypass_network__28__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_bypass_network__28__prf_addr = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_bypass_network__28__ready = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_bypass_network__29__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_bypass_network__29__prf_addr = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_bypass_network__29__ready = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_wakeup_network__30__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_wakeup_network__30__prf_addr = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_bypass_network__31__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_bypass_network__31__prf_addr = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_bypass_network__31__ready = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_bypass_network__32__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_bypass_network__32__prf_addr = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_bypass_network__32__ready = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_wakeup_network__33__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_wakeup_network__33__prf_addr = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_bypass_network__34__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_bypass_network__34__prf_addr = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_bypass_network__34__ready = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_bypass_network__35__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_bypass_network__35__prf_addr = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_bypass_network__35__ready = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_wakeup_network__36__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_wakeup_network__36__prf_addr = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_bypass_network__37__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_bypass_network__37__prf_addr = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_bypass_network__37__ready = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_bypass_network__38__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_bypass_network__38__prf_addr = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_bypass_network__38__ready = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_wakeup_network__39__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_wakeup_network__39__prf_addr = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_bypass_network__40__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_bypass_network__40__prf_addr = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_bypass_network__40__ready = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_bypass_network__41__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_bypass_network__41__prf_addr = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_bypass_network__41__ready = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_wakeup_network__42__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_wakeup_network__42__prf_addr = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_bypass_network__43__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_bypass_network__43__prf_addr = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_bypass_network__43__ready = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_bypass_network__44__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_bypass_network__44__prf_addr = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_bypass_network__44__ready = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_wakeup_network__45__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_wakeup_network__45__prf_addr = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_bypass_network__46__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_bypass_network__46__prf_addr = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_bypass_network__46__ready = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_bypass_network__47__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_bypass_network__47__prf_addr = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_bypass_network__47__ready = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_wakeup_network__48__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_wakeup_network__48__prf_addr = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_bypass_network__49__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_bypass_network__49__prf_addr = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_bypass_network__49__ready = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_bypass_network__50__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_bypass_network__50__prf_addr = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_bypass_network__50__ready = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_wakeup_network__51__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_wakeup_network__51__prf_addr = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_bypass_network__52__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_bypass_network__52__prf_addr = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_bypass_network__52__ready = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_bypass_network__53__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_bypass_network__53__prf_addr = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_bypass_network__53__ready = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_wakeup_network__54__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_wakeup_network__54__prf_addr = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_bypass_network__55__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_bypass_network__55__prf_addr = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_bypass_network__55__ready = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_bypass_network__56__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_bypass_network__56__prf_addr = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_bypass_network__56__ready = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_wakeup_network__57__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_wakeup_network__57__prf_addr = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_bypass_network__58__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_bypass_network__58__prf_addr = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_bypass_network__58__ready = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_bypass_network__59__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_bypass_network__59__prf_addr = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_bypass_network__59__ready = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_wakeup_network__60__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_wakeup_network__60__prf_addr = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_bypass_network__61__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_bypass_network__61__prf_addr = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_bypass_network__61__ready = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_bypass_network__62__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_bypass_network__62__prf_addr = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_bypass_network__62__ready = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_wakeup_network__63__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_wakeup_network__63__prf_addr = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_InstrIsCritcal__64__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_InstrIsCritcal__64__instr_rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_InstrIsCritcal__64__commit_rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_InstrIsCritcal__64__lsu_rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_InstrIsCritcal__65__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_InstrIsCritcal__65__instr_rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_InstrIsCritcal__65__commit_rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_InstrIsCritcal__65__lsu_rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_InstrIsCritcal__66__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_InstrIsCritcal__66__instr_rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_InstrIsCritcal__66__commit_rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_InstrIsCritcal__66__lsu_rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_InstrIsCritcal__67__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_InstrIsCritcal__67__instr_rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_InstrIsCritcal__67__commit_rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_InstrIsCritcal__67__lsu_rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_InstrIsCritcal__68__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_InstrIsCritcal__68__instr_rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_InstrIsCritcal__68__commit_rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_InstrIsCritcal__68__lsu_rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_InstrIsCritcal__69__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_InstrIsCritcal__69__instr_rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_InstrIsCritcal__69__commit_rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_InstrIsCritcal__69__lsu_rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_InstrIsCritcal__70__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_InstrIsCritcal__70__instr_rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_InstrIsCritcal__70__commit_rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_InstrIsCritcal__70__lsu_rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_InstrIsCritcal__71__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_InstrIsCritcal__71__instr_rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_InstrIsCritcal__71__commit_rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_InstrIsCritcal__71__lsu_rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_IsBrROBKill__72__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_IsBrROBKill__72__branch_recovery_flush = VL_RAND_RESET_I(15);
    vlSelf->__Vfunc_IsBrROBKill__72__rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_IsBrROBKill__73__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_IsBrROBKill__73__branch_recovery_flush = VL_RAND_RESET_I(15);
    vlSelf->__Vfunc_IsBrROBKill__73__rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_IsBrROBKill__74__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_IsBrROBKill__74__branch_recovery_flush = VL_RAND_RESET_I(15);
    vlSelf->__Vfunc_IsBrROBKill__74__rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_IsBrROBKill__75__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_IsBrROBKill__75__branch_recovery_flush = VL_RAND_RESET_I(15);
    vlSelf->__Vfunc_IsBrROBKill__75__rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vdly__counter = VL_RAND_RESET_I(4);
    vlSelf->__Vdly__dispatch_slot_idx0 = VL_RAND_RESET_I(3);
    vlSelf->__Vdly__dispatch_slot_idx1 = VL_RAND_RESET_I(3);
    vlSelf->__Vdly__allocatable_slot_idx0_valid_reg = VL_RAND_RESET_I(1);
    vlSelf->__Vdly__allocatable_slot_idx1_valid_reg = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(205, vlSelf->__VdlyVal__issue_slot__v0);
    vlSelf->__VdlySet__issue_slot__v0 = 0;
    VL_RAND_RESET_W(205, vlSelf->__VdlyVal__issue_slot__v1);
    vlSelf->__VdlySet__issue_slot__v1 = 0;
    VL_RAND_RESET_W(205, vlSelf->__VdlyVal__issue_slot__v2);
    vlSelf->__VdlySet__issue_slot__v2 = 0;
    VL_RAND_RESET_W(205, vlSelf->__VdlyVal__issue_slot__v3);
    vlSelf->__VdlySet__issue_slot__v3 = 0;
    VL_RAND_RESET_W(205, vlSelf->__VdlyVal__issue_slot__v4);
    vlSelf->__VdlySet__issue_slot__v4 = 0;
    VL_RAND_RESET_W(205, vlSelf->__VdlyVal__issue_slot__v5);
    vlSelf->__VdlySet__issue_slot__v5 = 0;
    VL_RAND_RESET_W(205, vlSelf->__VdlyVal__issue_slot__v6);
    vlSelf->__VdlySet__issue_slot__v6 = 0;
    VL_RAND_RESET_W(205, vlSelf->__VdlyVal__issue_slot__v7);
    vlSelf->__VdlySet__issue_slot__v7 = 0;
    vlSelf->__VdlyVal__valid__v0 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__valid__v0 = 0;
    vlSelf->__VdlyVal__valid__v1 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__valid__v1 = 0;
    vlSelf->__VdlyVal__valid__v2 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__valid__v2 = 0;
    vlSelf->__VdlyVal__valid__v3 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__valid__v3 = 0;
    vlSelf->__VdlyVal__valid__v4 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__valid__v4 = 0;
    vlSelf->__VdlyVal__valid__v5 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__valid__v5 = 0;
    vlSelf->__VdlyVal__valid__v6 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__valid__v6 = 0;
    vlSelf->__VdlyVal__valid__v7 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__valid__v7 = 0;
    vlSelf->__VdlyVal__rs1_ready__v0 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__rs1_ready__v0 = 0;
    vlSelf->__VdlyVal__rs1_ready__v1 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__rs1_ready__v1 = 0;
    vlSelf->__VdlyVal__rs1_ready__v2 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__rs1_ready__v2 = 0;
    vlSelf->__VdlyVal__rs1_ready__v3 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__rs1_ready__v3 = 0;
    vlSelf->__VdlyVal__rs1_ready__v4 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__rs1_ready__v4 = 0;
    vlSelf->__VdlyVal__rs1_ready__v5 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__rs1_ready__v5 = 0;
    vlSelf->__VdlyVal__rs1_ready__v6 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__rs1_ready__v6 = 0;
    vlSelf->__VdlyVal__rs1_ready__v7 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__rs1_ready__v7 = 0;
    vlSelf->__VdlyVal__rs2_ready__v0 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__rs2_ready__v0 = 0;
    vlSelf->__VdlyVal__rs2_ready__v1 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__rs2_ready__v1 = 0;
    vlSelf->__VdlyVal__rs2_ready__v2 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__rs2_ready__v2 = 0;
    vlSelf->__VdlyVal__rs2_ready__v3 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__rs2_ready__v3 = 0;
    vlSelf->__VdlyVal__rs2_ready__v4 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__rs2_ready__v4 = 0;
    vlSelf->__VdlyVal__rs2_ready__v5 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__rs2_ready__v5 = 0;
    vlSelf->__VdlyVal__rs2_ready__v6 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__rs2_ready__v6 = 0;
    vlSelf->__VdlyVal__rs2_ready__v7 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__rs2_ready__v7 = 0;
}
