// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vfalco_top.h for the primary calling header

#ifndef VERILATED_VFALCO_TOP_INT_ISSUE_QUEUE_H_
#define VERILATED_VFALCO_TOP_INT_ISSUE_QUEUE_H_  // guard

#include "verilated.h"
class Vfalco_top_empty_entry_finder8_wrapper;
class Vfalco_top_int_iq_ctr_rob_tag_balance_selector;
class Vfalco_top_int_rob_tag_replay_unit;


class Vfalco_top__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vfalco_top_int_issue_queue final : public VerilatedModule {
  public:
    // CELLS
    Vfalco_top_empty_entry_finder8_wrapper* __PVT__empty_entry_finder;
    Vfalco_top_int_iq_ctr_rob_tag_balance_selector* INT_selector;
    Vfalco_top_int_rob_tag_replay_unit* __PVT__Replay_Unit;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(__PVT__clk,0,0);
        VL_IN8(__PVT__rst,0,0);
        VL_IN8(__PVT__muldiv_busy,0,0);
        CData/*3:0*/ __PVT__counter;
        CData/*0:0*/ __PVT__replay_issue_first;
        CData/*0:0*/ __PVT__wake_up_stall_issue_instr0_valid;
        CData/*0:0*/ __PVT__wake_up_stall_issue_instr1_valid;
        CData/*0:0*/ __PVT__replay_issue_instr0_valid;
        CData/*0:0*/ __PVT__replay_issue_instr1_valid;
        CData/*0:0*/ __PVT__replay_fifo_issue_muldiv;
        CData/*2:0*/ __PVT__issue_slot_idx0;
        CData/*2:0*/ __PVT__issue_slot_idx1;
        CData/*0:0*/ __PVT__issue_slot_idx0_valid;
        CData/*0:0*/ __PVT__issue_slot_idx1_valid;
        CData/*0:0*/ __PVT__muldiv_issuable;
        CData/*2:0*/ __PVT__dispatch_slot_idx0;
        CData/*2:0*/ __PVT__dispatch_slot_idx1;
        CData/*2:0*/ __PVT__allocatable_slot_idx0;
        CData/*2:0*/ __PVT__allocatable_slot_idx1;
        CData/*0:0*/ __PVT__allocatable_slot_idx0_valid;
        CData/*0:0*/ __PVT__allocatable_slot_idx1_valid;
        CData/*0:0*/ __PVT__allocatable_slot_idx0_valid_reg;
        CData/*0:0*/ __PVT__allocatable_slot_idx1_valid_reg;
        CData/*0:0*/ __PVT__dispatch_instr0_valid;
        CData/*0:0*/ __PVT__dispatch_instr1_valid;
        CData/*0:0*/ __PVT__issue_lock;
        CData/*0:0*/ __Vcellinp__INT_selector__load_wake_up_kill;
        CData/*0:0*/ __Vcellinp__INT_selector__branch_miss_flush;
        CData/*0:0*/ __Vcellinp__INT_selector__issue_replay;
        CData/*0:0*/ __Vcellinp__INT_selector__non_posion_issue;
        CData/*0:0*/ __Vcellinp__INT_selector__recovery_flush;
        CData/*0:0*/ __Vcellinp__INT_selector__icache_miss;
        CData/*0:0*/ __Vcellinp__Replay_Unit__issue_instr1_valid;
        CData/*0:0*/ __Vcellinp__Replay_Unit__issue_instr0_valid;
        CData/*5:0*/ __Vcellinp__Replay_Unit__cur_lsu_tag;
        CData/*5:0*/ __Vcellinp__Replay_Unit__cur_commit_tag;
        CData/*0:0*/ __Vcellinp__Replay_Unit__replay_muldiv_stall;
        CData/*0:0*/ __Vcellinp__Replay_Unit__load_depend_replay;
        CData/*0:0*/ __Vcellinp__Replay_Unit__load_wake_up_predict_failed;
        CData/*0:0*/ __Vcellinp__Replay_Unit__load_wake_up_failed_stall;
        CData/*0:0*/ __Vcellinp__Replay_Unit__recovery_stall;
        CData/*0:0*/ __Vfunc_IsBrROBKill__0__Vfuncout;
        CData/*5:0*/ __Vfunc_IsBrROBKill__0__rob_tag;
        CData/*0:0*/ __Vfunc_IsBrROBKill__1__Vfuncout;
        CData/*5:0*/ __Vfunc_IsBrROBKill__1__rob_tag;
        CData/*0:0*/ __Vfunc_IsBrROBKill__2__Vfuncout;
        CData/*5:0*/ __Vfunc_IsBrROBKill__2__rob_tag;
        CData/*0:0*/ __Vfunc_IsBrROBKill__3__Vfuncout;
        CData/*5:0*/ __Vfunc_IsBrROBKill__3__rob_tag;
        CData/*0:0*/ __Vfunc_IsBrROBKill__4__Vfuncout;
        CData/*5:0*/ __Vfunc_IsBrROBKill__4__rob_tag;
        CData/*0:0*/ __Vfunc_IsBrROBKill__5__Vfuncout;
        CData/*5:0*/ __Vfunc_IsBrROBKill__5__rob_tag;
        CData/*0:0*/ __Vfunc_IsBrROBKill__6__Vfuncout;
        CData/*5:0*/ __Vfunc_IsBrROBKill__6__rob_tag;
        CData/*0:0*/ __Vfunc_IsBrROBKill__7__Vfuncout;
        CData/*5:0*/ __Vfunc_IsBrROBKill__7__rob_tag;
        CData/*0:0*/ __Vfunc_IsBrROBKill__8__Vfuncout;
        CData/*5:0*/ __Vfunc_IsBrROBKill__8__rob_tag;
        CData/*0:0*/ __Vfunc_IsBrROBKill__9__Vfuncout;
        CData/*5:0*/ __Vfunc_IsBrROBKill__9__rob_tag;
        CData/*0:0*/ __Vfunc_IsBrROBKill__10__Vfuncout;
        CData/*5:0*/ __Vfunc_IsBrROBKill__10__rob_tag;
        CData/*0:0*/ __Vfunc_IsBrROBKill__11__Vfuncout;
    };
    struct {
        CData/*5:0*/ __Vfunc_IsBrROBKill__11__rob_tag;
        CData/*0:0*/ __Vfunc_IsBrROBKill__12__Vfuncout;
        CData/*5:0*/ __Vfunc_IsBrROBKill__12__rob_tag;
        CData/*0:0*/ __Vfunc_IsBrROBKill__13__Vfuncout;
        CData/*5:0*/ __Vfunc_IsBrROBKill__13__rob_tag;
        CData/*0:0*/ __Vfunc_IsBrROBKill__14__Vfuncout;
        CData/*5:0*/ __Vfunc_IsBrROBKill__14__rob_tag;
        CData/*0:0*/ __Vfunc_IsBrROBKill__15__Vfuncout;
        CData/*5:0*/ __Vfunc_IsBrROBKill__15__rob_tag;
        CData/*0:0*/ __Vfunc_bypass_network__16__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__16__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__16__ready;
        CData/*0:0*/ __Vfunc_bypass_network__17__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__17__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__17__ready;
        CData/*0:0*/ __Vfunc_wakeup_network__18__Vfuncout;
        CData/*5:0*/ __Vfunc_wakeup_network__18__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__19__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__19__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__19__ready;
        CData/*0:0*/ __Vfunc_bypass_network__20__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__20__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__20__ready;
        CData/*0:0*/ __Vfunc_wakeup_network__21__Vfuncout;
        CData/*5:0*/ __Vfunc_wakeup_network__21__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__22__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__22__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__22__ready;
        CData/*0:0*/ __Vfunc_bypass_network__23__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__23__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__23__ready;
        CData/*0:0*/ __Vfunc_wakeup_network__24__Vfuncout;
        CData/*5:0*/ __Vfunc_wakeup_network__24__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__25__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__25__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__25__ready;
        CData/*0:0*/ __Vfunc_bypass_network__26__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__26__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__26__ready;
        CData/*0:0*/ __Vfunc_wakeup_network__27__Vfuncout;
        CData/*5:0*/ __Vfunc_wakeup_network__27__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__28__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__28__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__28__ready;
        CData/*0:0*/ __Vfunc_bypass_network__29__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__29__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__29__ready;
        CData/*0:0*/ __Vfunc_wakeup_network__30__Vfuncout;
        CData/*5:0*/ __Vfunc_wakeup_network__30__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__31__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__31__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__31__ready;
        CData/*0:0*/ __Vfunc_bypass_network__32__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__32__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__32__ready;
        CData/*0:0*/ __Vfunc_wakeup_network__33__Vfuncout;
        CData/*5:0*/ __Vfunc_wakeup_network__33__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__34__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__34__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__34__ready;
        CData/*0:0*/ __Vfunc_bypass_network__35__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__35__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__35__ready;
        CData/*0:0*/ __Vfunc_wakeup_network__36__Vfuncout;
    };
    struct {
        CData/*5:0*/ __Vfunc_wakeup_network__36__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__37__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__37__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__37__ready;
        CData/*0:0*/ __Vfunc_bypass_network__38__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__38__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__38__ready;
        CData/*0:0*/ __Vfunc_wakeup_network__39__Vfuncout;
        CData/*5:0*/ __Vfunc_wakeup_network__39__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__40__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__40__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__40__ready;
        CData/*0:0*/ __Vfunc_bypass_network__41__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__41__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__41__ready;
        CData/*0:0*/ __Vfunc_wakeup_network__42__Vfuncout;
        CData/*5:0*/ __Vfunc_wakeup_network__42__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__43__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__43__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__43__ready;
        CData/*0:0*/ __Vfunc_bypass_network__44__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__44__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__44__ready;
        CData/*0:0*/ __Vfunc_wakeup_network__45__Vfuncout;
        CData/*5:0*/ __Vfunc_wakeup_network__45__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__46__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__46__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__46__ready;
        CData/*0:0*/ __Vfunc_bypass_network__47__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__47__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__47__ready;
        CData/*0:0*/ __Vfunc_wakeup_network__48__Vfuncout;
        CData/*5:0*/ __Vfunc_wakeup_network__48__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__49__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__49__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__49__ready;
        CData/*0:0*/ __Vfunc_bypass_network__50__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__50__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__50__ready;
        CData/*0:0*/ __Vfunc_wakeup_network__51__Vfuncout;
        CData/*5:0*/ __Vfunc_wakeup_network__51__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__52__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__52__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__52__ready;
        CData/*0:0*/ __Vfunc_bypass_network__53__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__53__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__53__ready;
        CData/*0:0*/ __Vfunc_wakeup_network__54__Vfuncout;
        CData/*5:0*/ __Vfunc_wakeup_network__54__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__55__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__55__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__55__ready;
        CData/*0:0*/ __Vfunc_bypass_network__56__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__56__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__56__ready;
        CData/*0:0*/ __Vfunc_wakeup_network__57__Vfuncout;
        CData/*5:0*/ __Vfunc_wakeup_network__57__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__58__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__58__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__58__ready;
        CData/*0:0*/ __Vfunc_bypass_network__59__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__59__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__59__ready;
        CData/*0:0*/ __Vfunc_wakeup_network__60__Vfuncout;
    };
    struct {
        CData/*5:0*/ __Vfunc_wakeup_network__60__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__61__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__61__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__61__ready;
        CData/*0:0*/ __Vfunc_bypass_network__62__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__62__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__62__ready;
        CData/*0:0*/ __Vfunc_wakeup_network__63__Vfuncout;
        CData/*5:0*/ __Vfunc_wakeup_network__63__prf_addr;
        CData/*0:0*/ __Vfunc_InstrIsCritcal__64__Vfuncout;
        CData/*5:0*/ __Vfunc_InstrIsCritcal__64__instr_rob_tag;
        CData/*5:0*/ __Vfunc_InstrIsCritcal__64__commit_rob_tag;
        CData/*5:0*/ __Vfunc_InstrIsCritcal__64__lsu_rob_tag;
        CData/*0:0*/ __Vfunc_InstrIsCritcal__65__Vfuncout;
        CData/*5:0*/ __Vfunc_InstrIsCritcal__65__instr_rob_tag;
        CData/*5:0*/ __Vfunc_InstrIsCritcal__65__commit_rob_tag;
        CData/*5:0*/ __Vfunc_InstrIsCritcal__65__lsu_rob_tag;
        CData/*0:0*/ __Vfunc_InstrIsCritcal__66__Vfuncout;
        CData/*5:0*/ __Vfunc_InstrIsCritcal__66__instr_rob_tag;
        CData/*5:0*/ __Vfunc_InstrIsCritcal__66__commit_rob_tag;
        CData/*5:0*/ __Vfunc_InstrIsCritcal__66__lsu_rob_tag;
        CData/*0:0*/ __Vfunc_InstrIsCritcal__67__Vfuncout;
        CData/*5:0*/ __Vfunc_InstrIsCritcal__67__instr_rob_tag;
        CData/*5:0*/ __Vfunc_InstrIsCritcal__67__commit_rob_tag;
        CData/*5:0*/ __Vfunc_InstrIsCritcal__67__lsu_rob_tag;
        CData/*0:0*/ __Vfunc_InstrIsCritcal__68__Vfuncout;
        CData/*5:0*/ __Vfunc_InstrIsCritcal__68__instr_rob_tag;
        CData/*5:0*/ __Vfunc_InstrIsCritcal__68__commit_rob_tag;
        CData/*5:0*/ __Vfunc_InstrIsCritcal__68__lsu_rob_tag;
        CData/*0:0*/ __Vfunc_InstrIsCritcal__69__Vfuncout;
        CData/*5:0*/ __Vfunc_InstrIsCritcal__69__instr_rob_tag;
        CData/*5:0*/ __Vfunc_InstrIsCritcal__69__commit_rob_tag;
        CData/*5:0*/ __Vfunc_InstrIsCritcal__69__lsu_rob_tag;
        CData/*0:0*/ __Vfunc_InstrIsCritcal__70__Vfuncout;
        CData/*5:0*/ __Vfunc_InstrIsCritcal__70__instr_rob_tag;
        CData/*5:0*/ __Vfunc_InstrIsCritcal__70__commit_rob_tag;
        CData/*5:0*/ __Vfunc_InstrIsCritcal__70__lsu_rob_tag;
        CData/*0:0*/ __Vfunc_InstrIsCritcal__71__Vfuncout;
        CData/*5:0*/ __Vfunc_InstrIsCritcal__71__instr_rob_tag;
        CData/*5:0*/ __Vfunc_InstrIsCritcal__71__commit_rob_tag;
        CData/*5:0*/ __Vfunc_InstrIsCritcal__71__lsu_rob_tag;
        CData/*0:0*/ __Vfunc_IsBrROBKill__72__Vfuncout;
        CData/*5:0*/ __Vfunc_IsBrROBKill__72__rob_tag;
        CData/*0:0*/ __Vfunc_IsBrROBKill__73__Vfuncout;
        CData/*5:0*/ __Vfunc_IsBrROBKill__73__rob_tag;
        CData/*0:0*/ __Vfunc_IsBrROBKill__74__Vfuncout;
        CData/*5:0*/ __Vfunc_IsBrROBKill__74__rob_tag;
        CData/*0:0*/ __Vfunc_IsBrROBKill__75__Vfuncout;
        CData/*5:0*/ __Vfunc_IsBrROBKill__75__rob_tag;
        CData/*3:0*/ __Vdly__counter;
        CData/*2:0*/ __Vdly__dispatch_slot_idx0;
        CData/*2:0*/ __Vdly__dispatch_slot_idx1;
        CData/*0:0*/ __Vdly__allocatable_slot_idx0_valid_reg;
        CData/*0:0*/ __Vdly__allocatable_slot_idx1_valid_reg;
        CData/*0:0*/ __VdlySet__issue_slot__v0;
        CData/*0:0*/ __VdlySet__issue_slot__v1;
        CData/*0:0*/ __VdlySet__issue_slot__v2;
        CData/*0:0*/ __VdlySet__issue_slot__v3;
        CData/*0:0*/ __VdlySet__issue_slot__v4;
        CData/*0:0*/ __VdlySet__issue_slot__v5;
        CData/*0:0*/ __VdlySet__issue_slot__v6;
        CData/*0:0*/ __VdlySet__issue_slot__v7;
        CData/*0:0*/ __VdlyVal__valid__v0;
        CData/*0:0*/ __VdlySet__valid__v0;
    };
    struct {
        CData/*0:0*/ __VdlyVal__valid__v1;
        CData/*0:0*/ __VdlySet__valid__v1;
        CData/*0:0*/ __VdlyVal__valid__v2;
        CData/*0:0*/ __VdlySet__valid__v2;
        CData/*0:0*/ __VdlyVal__valid__v3;
        CData/*0:0*/ __VdlySet__valid__v3;
        CData/*0:0*/ __VdlyVal__valid__v4;
        CData/*0:0*/ __VdlySet__valid__v4;
        CData/*0:0*/ __VdlyVal__valid__v5;
        CData/*0:0*/ __VdlySet__valid__v5;
        CData/*0:0*/ __VdlyVal__valid__v6;
        CData/*0:0*/ __VdlySet__valid__v6;
        CData/*0:0*/ __VdlyVal__valid__v7;
        CData/*0:0*/ __VdlySet__valid__v7;
        CData/*0:0*/ __VdlyVal__rs1_ready__v0;
        CData/*0:0*/ __VdlySet__rs1_ready__v0;
        CData/*0:0*/ __VdlyVal__rs1_ready__v1;
        CData/*0:0*/ __VdlySet__rs1_ready__v1;
        CData/*0:0*/ __VdlyVal__rs1_ready__v2;
        CData/*0:0*/ __VdlySet__rs1_ready__v2;
        CData/*0:0*/ __VdlyVal__rs1_ready__v3;
        CData/*0:0*/ __VdlySet__rs1_ready__v3;
        CData/*0:0*/ __VdlyVal__rs1_ready__v4;
        CData/*0:0*/ __VdlySet__rs1_ready__v4;
        CData/*0:0*/ __VdlyVal__rs1_ready__v5;
        CData/*0:0*/ __VdlySet__rs1_ready__v5;
        CData/*0:0*/ __VdlyVal__rs1_ready__v6;
        CData/*0:0*/ __VdlySet__rs1_ready__v6;
        CData/*0:0*/ __VdlyVal__rs1_ready__v7;
        CData/*0:0*/ __VdlySet__rs1_ready__v7;
        CData/*0:0*/ __VdlyVal__rs2_ready__v0;
        CData/*0:0*/ __VdlySet__rs2_ready__v0;
        CData/*0:0*/ __VdlyVal__rs2_ready__v1;
        CData/*0:0*/ __VdlySet__rs2_ready__v1;
        CData/*0:0*/ __VdlyVal__rs2_ready__v2;
        CData/*0:0*/ __VdlySet__rs2_ready__v2;
        CData/*0:0*/ __VdlyVal__rs2_ready__v3;
        CData/*0:0*/ __VdlySet__rs2_ready__v3;
        CData/*0:0*/ __VdlyVal__rs2_ready__v4;
        CData/*0:0*/ __VdlySet__rs2_ready__v4;
        CData/*0:0*/ __VdlyVal__rs2_ready__v5;
        CData/*0:0*/ __VdlySet__rs2_ready__v5;
        CData/*0:0*/ __VdlyVal__rs2_ready__v6;
        CData/*0:0*/ __VdlySet__rs2_ready__v6;
        CData/*0:0*/ __VdlyVal__rs2_ready__v7;
        CData/*0:0*/ __VdlySet__rs2_ready__v7;
        SData/*14:0*/ __Vcellinp__Replay_Unit__recovery_flush_BCAST;
        SData/*14:0*/ __Vfunc_IsBrROBKill__0__branch_recovery_flush;
        SData/*14:0*/ __Vfunc_IsBrROBKill__1__branch_recovery_flush;
        SData/*14:0*/ __Vfunc_IsBrROBKill__2__branch_recovery_flush;
        SData/*14:0*/ __Vfunc_IsBrROBKill__3__branch_recovery_flush;
        SData/*14:0*/ __Vfunc_IsBrROBKill__4__branch_recovery_flush;
        SData/*14:0*/ __Vfunc_IsBrROBKill__5__branch_recovery_flush;
        SData/*14:0*/ __Vfunc_IsBrROBKill__6__branch_recovery_flush;
        SData/*14:0*/ __Vfunc_IsBrROBKill__7__branch_recovery_flush;
        SData/*14:0*/ __Vfunc_IsBrROBKill__8__branch_recovery_flush;
        SData/*14:0*/ __Vfunc_IsBrROBKill__9__branch_recovery_flush;
        SData/*14:0*/ __Vfunc_IsBrROBKill__10__branch_recovery_flush;
        SData/*14:0*/ __Vfunc_IsBrROBKill__11__branch_recovery_flush;
        SData/*14:0*/ __Vfunc_IsBrROBKill__12__branch_recovery_flush;
        SData/*14:0*/ __Vfunc_IsBrROBKill__13__branch_recovery_flush;
        SData/*14:0*/ __Vfunc_IsBrROBKill__14__branch_recovery_flush;
        SData/*14:0*/ __Vfunc_IsBrROBKill__15__branch_recovery_flush;
        SData/*14:0*/ __Vfunc_IsBrROBKill__72__branch_recovery_flush;
    };
    struct {
        SData/*14:0*/ __Vfunc_IsBrROBKill__73__branch_recovery_flush;
        SData/*14:0*/ __Vfunc_IsBrROBKill__74__branch_recovery_flush;
        SData/*14:0*/ __Vfunc_IsBrROBKill__75__branch_recovery_flush;
        IData/*31:0*/ __PVT__i;
        VlWide<7>/*204:0*/ __PVT__wake_up_stall_issue_instr0_pack;
        VlWide<7>/*204:0*/ __PVT__wake_up_stall_issue_instr1_pack;
        VlWide<7>/*204:0*/ __PVT__replay_issue_instr0_pack;
        VlWide<7>/*204:0*/ __PVT__replay_issue_instr1_pack;
        VlWide<7>/*204:0*/ __Vcellinp__Replay_Unit__issue_instr1_pack;
        VlWide<7>/*204:0*/ __Vcellinp__Replay_Unit__issue_instr0_pack;
        VlWide<7>/*204:0*/ __VdlyVal__issue_slot__v0;
        VlWide<7>/*204:0*/ __VdlyVal__issue_slot__v1;
        VlWide<7>/*204:0*/ __VdlyVal__issue_slot__v2;
        VlWide<7>/*204:0*/ __VdlyVal__issue_slot__v3;
        VlWide<7>/*204:0*/ __VdlyVal__issue_slot__v4;
        VlWide<7>/*204:0*/ __VdlyVal__issue_slot__v5;
        VlWide<7>/*204:0*/ __VdlyVal__issue_slot__v6;
        VlWide<7>/*204:0*/ __VdlyVal__issue_slot__v7;
        VlUnpacked<VlWide<7>/*204:0*/, 8> __PVT__issue_slot;
        VlUnpacked<CData/*0:0*/, 8> valid;
        VlUnpacked<CData/*0:0*/, 8> rs1_ready;
        VlUnpacked<CData/*0:0*/, 8> rs2_ready;
        VlUnpacked<CData/*0:0*/, 8> issue_ready;
        VlUnpacked<CData/*0:0*/, 8> __PVT__issue_rs1;
        VlUnpacked<CData/*0:0*/, 8> __PVT__issue_rs2;
        VlUnpacked<CData/*0:0*/, 8> __PVT__entry_is_csr_instr;
        VlUnpacked<CData/*0:0*/, 8> __PVT__entry_is_ctrl_instr;
        VlUnpacked<CData/*0:0*/, 8> __PVT__entry_is_muldiv_instr;
        VlUnpacked<CData/*0:0*/, 8> __PVT__entry_is_critical;
    };

    // INTERNAL VARIABLES
    Vfalco_top__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vfalco_top_int_issue_queue(Vfalco_top__Syms* symsp, const char* v__name);
    ~Vfalco_top_int_issue_queue();
    VL_UNCOPYABLE(Vfalco_top_int_issue_queue);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
