// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vfalco_top.h for the primary calling header

#ifndef VERILATED_VFALCO_TOP_MEM_ISSUE_QUEUE_H_
#define VERILATED_VFALCO_TOP_MEM_ISSUE_QUEUE_H_  // guard

#include "verilated.h"
class Vfalco_top_empty_entry_finder8_wrapper;
class Vfalco_top_mem_iq_balance_selector_wo_store;
class Vfalco_top_mem_replay_unit;


class Vfalco_top__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vfalco_top_mem_issue_queue final : public VerilatedModule {
  public:
    // CELLS
    Vfalco_top_empty_entry_finder8_wrapper* __PVT__empty_entry_finder;
    Vfalco_top_mem_iq_balance_selector_wo_store* __PVT__selector;
    Vfalco_top_mem_replay_unit* __PVT__replay_unit;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(__PVT__clk,0,0);
        VL_IN8(__PVT__rst,0,0);
        CData/*7:0*/ cur_depvec;
        CData/*7:0*/ instr0_depvec;
        CData/*7:0*/ instr0_depvec_ori;
        CData/*7:0*/ instr1_depvec;
        CData/*7:0*/ flush_vec;
        CData/*7:0*/ issue_flush_vec;
        CData/*2:0*/ __PVT__issue_slot_idx;
        CData/*0:0*/ __PVT__issue_slot_idx_valid;
        CData/*5:0*/ __PVT__ld_spec_rob_tag;
        CData/*2:0*/ __PVT__dispatch_slot_idx0;
        CData/*2:0*/ __PVT__dispatch_slot_idx1;
        CData/*2:0*/ __PVT__allocatable_slot_idx0;
        CData/*2:0*/ __PVT__allocatable_slot_idx1;
        CData/*0:0*/ __PVT__allocatable_slot_idx0_valid;
        CData/*0:0*/ __PVT__allocatable_slot_idx1_valid;
        CData/*0:0*/ __PVT__allocatable_slot_idx0_valid_reg;
        CData/*0:0*/ __PVT__allocatable_slot_idx1_valid_reg;
        CData/*0:0*/ __PVT__dispatch_instr0_valid;
        CData/*0:0*/ __PVT__dispatch_instr1_valid;
        CData/*0:0*/ __PVT__issue_lock;
        CData/*0:0*/ __PVT__replay_issue_instr_valid;
        CData/*0:0*/ __Vcellinp__replay_unit__issue_instr_valid;
        CData/*0:0*/ __Vcellinp__replay_unit__replay_muldiv_stall;
        CData/*0:0*/ __Vcellinp__replay_unit__load_depend_replay;
        CData/*0:0*/ __Vcellinp__replay_unit__load_wake_up_predict_failed;
        CData/*0:0*/ __Vcellinp__replay_unit__load_wake_up_failed_stall;
        CData/*0:0*/ __Vcellinp__replay_unit__recovery_stall;
        CData/*0:0*/ __Vfunc_IsBrROBKill__0__Vfuncout;
        CData/*5:0*/ __Vfunc_IsBrROBKill__0__rob_tag;
        CData/*0:0*/ __Vfunc_IsBrROBKill__1__Vfuncout;
        CData/*5:0*/ __Vfunc_IsBrROBKill__1__rob_tag;
        CData/*0:0*/ __Vfunc_IsBrROBKill__2__Vfuncout;
        CData/*5:0*/ __Vfunc_IsBrROBKill__2__rob_tag;
        CData/*0:0*/ __Vfunc_IsBrROBKill__3__Vfuncout;
        CData/*5:0*/ __Vfunc_IsBrROBKill__3__rob_tag;
        CData/*0:0*/ __Vfunc_IsBrROBKill__4__Vfuncout;
        CData/*5:0*/ __Vfunc_IsBrROBKill__4__rob_tag;
        CData/*0:0*/ __Vfunc_IsBrROBKill__5__Vfuncout;
        CData/*5:0*/ __Vfunc_IsBrROBKill__5__rob_tag;
        CData/*0:0*/ __Vfunc_IsBrROBKill__6__Vfuncout;
        CData/*5:0*/ __Vfunc_IsBrROBKill__6__rob_tag;
        CData/*0:0*/ __Vfunc_IsBrROBKill__7__Vfuncout;
        CData/*5:0*/ __Vfunc_IsBrROBKill__7__rob_tag;
        CData/*0:0*/ __Vfunc_bypass_network__8__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__8__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__8__ready;
        CData/*0:0*/ __Vfunc_bypass_network__9__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__9__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__9__ready;
        CData/*0:0*/ __Vfunc_wakeup_network__10__Vfuncout;
        CData/*5:0*/ __Vfunc_wakeup_network__10__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__11__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__11__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__11__ready;
        CData/*0:0*/ __Vfunc_bypass_network__12__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__12__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__12__ready;
        CData/*0:0*/ __Vfunc_wakeup_network__13__Vfuncout;
        CData/*5:0*/ __Vfunc_wakeup_network__13__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__14__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__14__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__14__ready;
    };
    struct {
        CData/*0:0*/ __Vfunc_bypass_network__15__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__15__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__15__ready;
        CData/*0:0*/ __Vfunc_wakeup_network__16__Vfuncout;
        CData/*5:0*/ __Vfunc_wakeup_network__16__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__17__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__17__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__17__ready;
        CData/*0:0*/ __Vfunc_bypass_network__18__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__18__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__18__ready;
        CData/*0:0*/ __Vfunc_wakeup_network__19__Vfuncout;
        CData/*5:0*/ __Vfunc_wakeup_network__19__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__20__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__20__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__20__ready;
        CData/*0:0*/ __Vfunc_bypass_network__21__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__21__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__21__ready;
        CData/*0:0*/ __Vfunc_wakeup_network__22__Vfuncout;
        CData/*5:0*/ __Vfunc_wakeup_network__22__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__23__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__23__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__23__ready;
        CData/*0:0*/ __Vfunc_bypass_network__24__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__24__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__24__ready;
        CData/*0:0*/ __Vfunc_wakeup_network__25__Vfuncout;
        CData/*5:0*/ __Vfunc_wakeup_network__25__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__26__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__26__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__26__ready;
        CData/*0:0*/ __Vfunc_bypass_network__27__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__27__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__27__ready;
        CData/*0:0*/ __Vfunc_wakeup_network__28__Vfuncout;
        CData/*5:0*/ __Vfunc_wakeup_network__28__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__29__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__29__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__29__ready;
        CData/*0:0*/ __Vfunc_bypass_network__30__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__30__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__30__ready;
        CData/*0:0*/ __Vfunc_wakeup_network__31__Vfuncout;
        CData/*5:0*/ __Vfunc_wakeup_network__31__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__32__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__32__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__32__ready;
        CData/*0:0*/ __Vfunc_bypass_network__33__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__33__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__33__ready;
        CData/*0:0*/ __Vfunc_wakeup_network__34__Vfuncout;
        CData/*5:0*/ __Vfunc_wakeup_network__34__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__35__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__35__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__35__ready;
        CData/*0:0*/ __Vfunc_bypass_network__36__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__36__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__36__ready;
        CData/*0:0*/ __Vfunc_wakeup_network__37__Vfuncout;
        CData/*5:0*/ __Vfunc_wakeup_network__37__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__38__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__38__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__38__ready;
    };
    struct {
        CData/*0:0*/ __Vfunc_bypass_network__39__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__39__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__39__ready;
        CData/*0:0*/ __Vfunc_wakeup_network__40__Vfuncout;
        CData/*5:0*/ __Vfunc_wakeup_network__40__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__41__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__41__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__41__ready;
        CData/*0:0*/ __Vfunc_bypass_network__42__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__42__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__42__ready;
        CData/*0:0*/ __Vfunc_wakeup_network__43__Vfuncout;
        CData/*5:0*/ __Vfunc_wakeup_network__43__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__44__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__44__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__44__ready;
        CData/*0:0*/ __Vfunc_bypass_network__45__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__45__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__45__ready;
        CData/*0:0*/ __Vfunc_wakeup_network__46__Vfuncout;
        CData/*5:0*/ __Vfunc_wakeup_network__46__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__47__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__47__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__47__ready;
        CData/*0:0*/ __Vfunc_bypass_network__48__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__48__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__48__ready;
        CData/*0:0*/ __Vfunc_wakeup_network__49__Vfuncout;
        CData/*5:0*/ __Vfunc_wakeup_network__49__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__50__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__50__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__50__ready;
        CData/*0:0*/ __Vfunc_bypass_network__51__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__51__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__51__ready;
        CData/*0:0*/ __Vfunc_wakeup_network__52__Vfuncout;
        CData/*5:0*/ __Vfunc_wakeup_network__52__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__53__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__53__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__53__ready;
        CData/*0:0*/ __Vfunc_bypass_network__54__Vfuncout;
        CData/*5:0*/ __Vfunc_bypass_network__54__prf_addr;
        CData/*0:0*/ __Vfunc_bypass_network__54__ready;
        CData/*0:0*/ __Vfunc_wakeup_network__55__Vfuncout;
        CData/*5:0*/ __Vfunc_wakeup_network__55__prf_addr;
        CData/*0:0*/ __Vfunc_IsBrROBKill__56__Vfuncout;
        CData/*5:0*/ __Vfunc_IsBrROBKill__56__rob_tag;
        CData/*0:0*/ __Vfunc_IsBrROBKill__57__Vfuncout;
        CData/*5:0*/ __Vfunc_IsBrROBKill__57__rob_tag;
        CData/*2:0*/ __Vdly__dispatch_slot_idx0;
        CData/*2:0*/ __Vdly__dispatch_slot_idx1;
        CData/*0:0*/ __Vdly__allocatable_slot_idx0_valid_reg;
        CData/*0:0*/ __Vdly__allocatable_slot_idx1_valid_reg;
        CData/*5:0*/ __Vdly__ld_spec_rob_tag;
        CData/*0:0*/ __VdlySet__issue_slot__v0;
        CData/*0:0*/ __VdlySet__issue_slot__v1;
        CData/*0:0*/ __VdlySet__issue_slot__v2;
        CData/*0:0*/ __VdlySet__issue_slot__v3;
        CData/*0:0*/ __VdlySet__issue_slot__v4;
        CData/*0:0*/ __VdlySet__issue_slot__v5;
        CData/*0:0*/ __VdlySet__issue_slot__v6;
        CData/*0:0*/ __VdlySet__issue_slot__v7;
        CData/*0:0*/ __VdlyVal__valid__v0;
        CData/*0:0*/ __VdlySet__valid__v0;
    };
    struct {
        CData/*0:0*/ __VdlyVal__valid__v1;
        CData/*0:0*/ __VdlySet__valid__v1;
        CData/*0:0*/ __VdlyVal__valid__v2;
        CData/*0:0*/ __VdlySet__valid__v2;
        CData/*0:0*/ __VdlyVal__valid__v3;
        CData/*0:0*/ __VdlySet__valid__v3;
        CData/*0:0*/ __VdlyVal__valid__v4;
        CData/*0:0*/ __VdlySet__valid__v4;
        CData/*0:0*/ __VdlyVal__valid__v5;
        CData/*0:0*/ __VdlySet__valid__v5;
        CData/*0:0*/ __VdlyVal__valid__v6;
        CData/*0:0*/ __VdlySet__valid__v6;
        CData/*0:0*/ __VdlyVal__valid__v7;
        CData/*0:0*/ __VdlySet__valid__v7;
        CData/*0:0*/ __VdlyVal__rs1_ready__v0;
        CData/*0:0*/ __VdlySet__rs1_ready__v0;
        CData/*0:0*/ __VdlyVal__rs1_ready__v1;
        CData/*0:0*/ __VdlySet__rs1_ready__v1;
        CData/*0:0*/ __VdlyVal__rs1_ready__v2;
        CData/*0:0*/ __VdlySet__rs1_ready__v2;
        CData/*0:0*/ __VdlyVal__rs1_ready__v3;
        CData/*0:0*/ __VdlySet__rs1_ready__v3;
        CData/*0:0*/ __VdlyVal__rs1_ready__v4;
        CData/*0:0*/ __VdlySet__rs1_ready__v4;
        CData/*0:0*/ __VdlyVal__rs1_ready__v5;
        CData/*0:0*/ __VdlySet__rs1_ready__v5;
        CData/*0:0*/ __VdlyVal__rs1_ready__v6;
        CData/*0:0*/ __VdlySet__rs1_ready__v6;
        CData/*0:0*/ __VdlyVal__rs1_ready__v7;
        CData/*0:0*/ __VdlySet__rs1_ready__v7;
        CData/*0:0*/ __VdlyVal__rs2_ready__v0;
        CData/*0:0*/ __VdlySet__rs2_ready__v0;
        CData/*0:0*/ __VdlyVal__rs2_ready__v1;
        CData/*0:0*/ __VdlySet__rs2_ready__v1;
        CData/*0:0*/ __VdlyVal__rs2_ready__v2;
        CData/*0:0*/ __VdlySet__rs2_ready__v2;
        CData/*0:0*/ __VdlyVal__rs2_ready__v3;
        CData/*0:0*/ __VdlySet__rs2_ready__v3;
        CData/*0:0*/ __VdlyVal__rs2_ready__v4;
        CData/*0:0*/ __VdlySet__rs2_ready__v4;
        CData/*0:0*/ __VdlyVal__rs2_ready__v5;
        CData/*0:0*/ __VdlySet__rs2_ready__v5;
        CData/*0:0*/ __VdlyVal__rs2_ready__v6;
        CData/*0:0*/ __VdlySet__rs2_ready__v6;
        CData/*0:0*/ __VdlyVal__rs2_ready__v7;
        CData/*0:0*/ __VdlySet__rs2_ready__v7;
        CData/*7:0*/ __VdlyVal__depvec__v0;
        CData/*0:0*/ __VdlySet__depvec__v0;
        CData/*7:0*/ __VdlyVal__depvec__v1;
        CData/*0:0*/ __VdlySet__depvec__v1;
        CData/*7:0*/ __VdlyVal__depvec__v2;
        CData/*0:0*/ __VdlySet__depvec__v2;
        CData/*7:0*/ __VdlyVal__depvec__v3;
        CData/*0:0*/ __VdlySet__depvec__v3;
        CData/*7:0*/ __VdlyVal__depvec__v4;
        CData/*0:0*/ __VdlySet__depvec__v4;
        CData/*7:0*/ __VdlyVal__depvec__v5;
        CData/*0:0*/ __VdlySet__depvec__v5;
        CData/*7:0*/ __VdlyVal__depvec__v6;
        CData/*0:0*/ __VdlySet__depvec__v6;
        CData/*7:0*/ __VdlyVal__depvec__v7;
        CData/*0:0*/ __VdlySet__depvec__v7;
        SData/*14:0*/ __Vcellinp__replay_unit__recovery_flush_BCAST;
        SData/*14:0*/ __Vfunc_IsBrROBKill__0__branch_recovery_flush;
    };
    struct {
        SData/*14:0*/ __Vfunc_IsBrROBKill__1__branch_recovery_flush;
        SData/*14:0*/ __Vfunc_IsBrROBKill__2__branch_recovery_flush;
        SData/*14:0*/ __Vfunc_IsBrROBKill__3__branch_recovery_flush;
        SData/*14:0*/ __Vfunc_IsBrROBKill__4__branch_recovery_flush;
        SData/*14:0*/ __Vfunc_IsBrROBKill__5__branch_recovery_flush;
        SData/*14:0*/ __Vfunc_IsBrROBKill__6__branch_recovery_flush;
        SData/*14:0*/ __Vfunc_IsBrROBKill__7__branch_recovery_flush;
        SData/*14:0*/ __Vfunc_IsBrROBKill__56__branch_recovery_flush;
        SData/*14:0*/ __Vfunc_IsBrROBKill__57__branch_recovery_flush;
        IData/*31:0*/ __PVT__unnamedblk1__DOT__i;
        VlWide<5>/*128:0*/ __PVT__replay_issue_instr_pack;
        VlWide<5>/*128:0*/ __Vcellinp__replay_unit__issue_instr_pack;
        VlWide<5>/*128:0*/ __VdlyVal__issue_slot__v0;
        VlWide<5>/*128:0*/ __VdlyVal__issue_slot__v1;
        VlWide<5>/*128:0*/ __VdlyVal__issue_slot__v2;
        VlWide<5>/*128:0*/ __VdlyVal__issue_slot__v3;
        VlWide<5>/*128:0*/ __VdlyVal__issue_slot__v4;
        VlWide<5>/*128:0*/ __VdlyVal__issue_slot__v5;
        VlWide<5>/*128:0*/ __VdlyVal__issue_slot__v6;
        VlWide<5>/*128:0*/ __VdlyVal__issue_slot__v7;
        VlUnpacked<VlWide<5>/*128:0*/, 8> __PVT__issue_slot;
        VlUnpacked<CData/*7:0*/, 8> depvec;
        VlUnpacked<CData/*0:0*/, 8> valid;
        VlUnpacked<CData/*0:0*/, 8> rs1_ready;
        VlUnpacked<CData/*0:0*/, 8> rs2_ready;
        VlUnpacked<CData/*0:0*/, 8> issue_rs1;
        VlUnpacked<CData/*0:0*/, 8> issue_rs2;
        VlUnpacked<CData/*0:0*/, 8> issue_ready;
        VlUnpacked<CData/*0:0*/, 8> entry_is_store;
    };

    // INTERNAL VARIABLES
    Vfalco_top__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vfalco_top_mem_issue_queue(Vfalco_top__Syms* symsp, const char* v__name);
    ~Vfalco_top_mem_issue_queue();
    VL_UNCOPYABLE(Vfalco_top_mem_issue_queue);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
