// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design implementation internals
// See Vfalco_top.h for the primary calling header

#include "Vfalco_top__pch.h"
#include "Vfalco_top_store_buffer.h"

VL_ATTR_COLD void Vfalco_top_store_buffer___ctor_var_reset(Vfalco_top_store_buffer* vlSelf) {
    (void)vlSelf;  // Prevent unused variable warning
    Vfalco_top__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+          Vfalco_top_store_buffer___ctor_var_reset\n"); );
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    vlSelf->__PVT__clk = VL_RAND_RESET_I(1);
    vlSelf->__PVT__rst = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(69, vlSelf->__PVT__store_req);
    vlSelf->__PVT__store_resp = VL_RAND_RESET_I(2);
    for (int __Vi0 = 0; __Vi0 < 16; ++__Vi0) {
        vlSelf->SDB_data[__Vi0] = VL_RAND_RESET_I(32);
    }
    for (int __Vi0 = 0; __Vi0 < 16; ++__Vi0) {
        vlSelf->SDB_addr[__Vi0] = VL_RAND_RESET_I(32);
    }
    for (int __Vi0 = 0; __Vi0 < 16; ++__Vi0) {
        vlSelf->st_mask[__Vi0] = VL_RAND_RESET_I(4);
    }
    for (int __Vi0 = 0; __Vi0 < 16; ++__Vi0) {
        vlSelf->SDB_rob_tag[__Vi0] = VL_RAND_RESET_I(6);
    }
    for (int __Vi0 = 0; __Vi0 < 16; ++__Vi0) {
        vlSelf->retirement[__Vi0] = VL_RAND_RESET_I(1);
    }
    for (int __Vi0 = 0; __Vi0 < 16; ++__Vi0) {
        vlSelf->valid[__Vi0] = VL_RAND_RESET_I(1);
    }
    for (int __Vi0 = 0; __Vi0 < 16; ++__Vi0) {
        vlSelf->is_non_idempotent[__Vi0] = VL_RAND_RESET_I(1);
    }
    vlSelf->alloc_ptr = VL_RAND_RESET_I(4);
    vlSelf->__PVT__alloc_pre_0_ptr = VL_RAND_RESET_I(4);
    vlSelf->__PVT__alloc_pre_1_ptr = VL_RAND_RESET_I(4);
    vlSelf->retire_ptr = VL_RAND_RESET_I(4);
    vlSelf->retire_next_ptr = VL_RAND_RESET_I(4);
    vlSelf->pop_ptr = VL_RAND_RESET_I(4);
    for (int __Vi0 = 0; __Vi0 < 16; ++__Vi0) {
        vlSelf->__PVT__load_store_addr_match[__Vi0] = VL_RAND_RESET_I(1);
    }
    vlSelf->__PVT__load_forward_hit = VL_RAND_RESET_I(1);
    vlSelf->__PVT__load_forward_hit_index = VL_RAND_RESET_I(4);
    vlSelf->__PVT__load_forward_data = VL_RAND_RESET_I(32);
    vlSelf->__PVT__load_forward_hit_mask = VL_RAND_RESET_I(4);
    vlSelf->__PVT__pop = VL_RAND_RESET_I(1);
    vlSelf->__PVT__store_pop = VL_RAND_RESET_I(1);
    vlSelf->__PVT__allocate_new_entry = VL_RAND_RESET_I(1);
    for (int __Vi0 = 0; __Vi0 < 16; ++__Vi0) {
        vlSelf->__PVT__entry_is_non_idempotent[__Vi0] = VL_RAND_RESET_I(1);
    }
    vlSelf->__PVT__sdb_input_data = VL_RAND_RESET_I(32);
    vlSelf->__PVT__sdb_input_mask = VL_RAND_RESET_I(4);
    for (int __Vi0 = 0; __Vi0 < 4; ++__Vi0) {
        for (int __Vi1 = 0; __Vi1 < 16; ++__Vi1) {
            vlSelf->__PVT__sdb_input_match[__Vi0][__Vi1] = VL_RAND_RESET_I(1);
        }
    }
    for (int __Vi0 = 0; __Vi0 < 15; ++__Vi0) {
        vlSelf->__PVT__temp_ptr[__Vi0] = VL_RAND_RESET_I(4);
    }
    for (int __Vi0 = 0; __Vi0 < 4; ++__Vi0) {
        vlSelf->__PVT__sdb_input_byte_data[__Vi0] = VL_RAND_RESET_I(8);
    }
    for (int __Vi0 = 0; __Vi0 < 4; ++__Vi0) {
        vlSelf->__PVT__byte_match[__Vi0] = VL_RAND_RESET_I(1);
    }
    for (int __Vi0 = 0; __Vi0 < 4; ++__Vi0) {
        vlSelf->__PVT__byte_match_index[__Vi0] = VL_RAND_RESET_I(4);
    }
    vlSelf->flush_vec = VL_RAND_RESET_I(16);
    vlSelf->flush_counter = VL_RAND_RESET_I(4);
    vlSelf->__PVT__i = VL_RAND_RESET_I(32);
    vlSelf->__Vcellout__genblk9__BRA__0__KET____DOT__CDU__hit_index = VL_RAND_RESET_I(4);
    vlSelf->__Vcellout__genblk9__BRA__0__KET____DOT__CDU__hit = VL_RAND_RESET_I(1);
    for (int __Vi0 = 0; __Vi0 < 16; ++__Vi0) {
        vlSelf->__Vcellinp__genblk9__BRA__0__KET____DOT__CDU__match[__Vi0] = VL_RAND_RESET_I(1);
    }
    vlSelf->__Vcellout__genblk9__BRA__1__KET____DOT__CDU__hit_index = VL_RAND_RESET_I(4);
    vlSelf->__Vcellout__genblk9__BRA__1__KET____DOT__CDU__hit = VL_RAND_RESET_I(1);
    for (int __Vi0 = 0; __Vi0 < 16; ++__Vi0) {
        vlSelf->__Vcellinp__genblk9__BRA__1__KET____DOT__CDU__match[__Vi0] = VL_RAND_RESET_I(1);
    }
    vlSelf->__Vcellout__genblk9__BRA__2__KET____DOT__CDU__hit_index = VL_RAND_RESET_I(4);
    vlSelf->__Vcellout__genblk9__BRA__2__KET____DOT__CDU__hit = VL_RAND_RESET_I(1);
    for (int __Vi0 = 0; __Vi0 < 16; ++__Vi0) {
        vlSelf->__Vcellinp__genblk9__BRA__2__KET____DOT__CDU__match[__Vi0] = VL_RAND_RESET_I(1);
    }
    vlSelf->__Vcellout__genblk9__BRA__3__KET____DOT__CDU__hit_index = VL_RAND_RESET_I(4);
    vlSelf->__Vcellout__genblk9__BRA__3__KET____DOT__CDU__hit = VL_RAND_RESET_I(1);
    for (int __Vi0 = 0; __Vi0 < 16; ++__Vi0) {
        vlSelf->__Vcellinp__genblk9__BRA__3__KET____DOT__CDU__match[__Vi0] = VL_RAND_RESET_I(1);
    }
    vlSelf->__Vfunc_IsBrROBKill__0__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_IsBrROBKill__0__branch_recovery_flush = VL_RAND_RESET_I(15);
    vlSelf->__Vfunc_IsBrROBKill__0__rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_IsBrROBKill__1__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_IsBrROBKill__1__branch_recovery_flush = VL_RAND_RESET_I(15);
    vlSelf->__Vfunc_IsBrROBKill__1__rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_IsBrROBKill__2__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_IsBrROBKill__2__branch_recovery_flush = VL_RAND_RESET_I(15);
    vlSelf->__Vfunc_IsBrROBKill__2__rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_IsBrROBKill__3__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_IsBrROBKill__3__branch_recovery_flush = VL_RAND_RESET_I(15);
    vlSelf->__Vfunc_IsBrROBKill__3__rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_IsBrROBKill__4__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_IsBrROBKill__4__branch_recovery_flush = VL_RAND_RESET_I(15);
    vlSelf->__Vfunc_IsBrROBKill__4__rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_IsBrROBKill__5__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_IsBrROBKill__5__branch_recovery_flush = VL_RAND_RESET_I(15);
    vlSelf->__Vfunc_IsBrROBKill__5__rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_IsBrROBKill__6__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_IsBrROBKill__6__branch_recovery_flush = VL_RAND_RESET_I(15);
    vlSelf->__Vfunc_IsBrROBKill__6__rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_IsBrROBKill__7__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_IsBrROBKill__7__branch_recovery_flush = VL_RAND_RESET_I(15);
    vlSelf->__Vfunc_IsBrROBKill__7__rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_IsBrROBKill__8__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_IsBrROBKill__8__branch_recovery_flush = VL_RAND_RESET_I(15);
    vlSelf->__Vfunc_IsBrROBKill__8__rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_IsBrROBKill__9__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_IsBrROBKill__9__branch_recovery_flush = VL_RAND_RESET_I(15);
    vlSelf->__Vfunc_IsBrROBKill__9__rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_IsBrROBKill__10__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_IsBrROBKill__10__branch_recovery_flush = VL_RAND_RESET_I(15);
    vlSelf->__Vfunc_IsBrROBKill__10__rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_IsBrROBKill__11__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_IsBrROBKill__11__branch_recovery_flush = VL_RAND_RESET_I(15);
    vlSelf->__Vfunc_IsBrROBKill__11__rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_IsBrROBKill__12__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_IsBrROBKill__12__branch_recovery_flush = VL_RAND_RESET_I(15);
    vlSelf->__Vfunc_IsBrROBKill__12__rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_IsBrROBKill__13__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_IsBrROBKill__13__branch_recovery_flush = VL_RAND_RESET_I(15);
    vlSelf->__Vfunc_IsBrROBKill__13__rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_IsBrROBKill__14__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_IsBrROBKill__14__branch_recovery_flush = VL_RAND_RESET_I(15);
    vlSelf->__Vfunc_IsBrROBKill__14__rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_IsBrROBKill__15__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_IsBrROBKill__15__branch_recovery_flush = VL_RAND_RESET_I(15);
    vlSelf->__Vfunc_IsBrROBKill__15__rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vdly__alloc_ptr = VL_RAND_RESET_I(4);
    vlSelf->__Vdly__retire_ptr = VL_RAND_RESET_I(4);
    vlSelf->__Vdly__pop_ptr = VL_RAND_RESET_I(4);
    vlSelf->__VdlySet__SDB_addr__v0 = 0;
    vlSelf->__VdlyVal__SDB_addr__v1 = VL_RAND_RESET_I(32);
    vlSelf->__VdlySet__SDB_addr__v1 = 0;
    vlSelf->__VdlyVal__SDB_data__v1 = VL_RAND_RESET_I(32);
    vlSelf->__VdlyVal__st_mask__v1 = VL_RAND_RESET_I(4);
    vlSelf->__VdlyVal__SDB_rob_tag__v1 = VL_RAND_RESET_I(6);
    vlSelf->__VdlyVal__is_non_idempotent__v1 = VL_RAND_RESET_I(1);
    vlSelf->__VdlyVal__SDB_addr__v2 = VL_RAND_RESET_I(32);
    vlSelf->__VdlySet__SDB_addr__v2 = 0;
    vlSelf->__VdlyVal__SDB_data__v2 = VL_RAND_RESET_I(32);
    vlSelf->__VdlyVal__st_mask__v2 = VL_RAND_RESET_I(4);
    vlSelf->__VdlyVal__SDB_rob_tag__v2 = VL_RAND_RESET_I(6);
    vlSelf->__VdlyVal__is_non_idempotent__v2 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__SDB_addr__v3 = 0;
    vlSelf->__VdlyVal__SDB_addr__v4 = VL_RAND_RESET_I(32);
    vlSelf->__VdlySet__SDB_addr__v4 = 0;
    vlSelf->__VdlyVal__SDB_data__v4 = VL_RAND_RESET_I(32);
    vlSelf->__VdlyVal__st_mask__v4 = VL_RAND_RESET_I(4);
    vlSelf->__VdlyVal__SDB_rob_tag__v4 = VL_RAND_RESET_I(6);
    vlSelf->__VdlyVal__is_non_idempotent__v4 = VL_RAND_RESET_I(1);
    vlSelf->__VdlyVal__SDB_addr__v5 = VL_RAND_RESET_I(32);
    vlSelf->__VdlySet__SDB_addr__v5 = 0;
    vlSelf->__VdlyVal__SDB_data__v5 = VL_RAND_RESET_I(32);
    vlSelf->__VdlyVal__st_mask__v5 = VL_RAND_RESET_I(4);
    vlSelf->__VdlyVal__SDB_rob_tag__v5 = VL_RAND_RESET_I(6);
    vlSelf->__VdlyVal__is_non_idempotent__v5 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__SDB_addr__v6 = 0;
    vlSelf->__VdlyVal__SDB_addr__v7 = VL_RAND_RESET_I(32);
    vlSelf->__VdlySet__SDB_addr__v7 = 0;
    vlSelf->__VdlyVal__SDB_data__v7 = VL_RAND_RESET_I(32);
    vlSelf->__VdlyVal__st_mask__v7 = VL_RAND_RESET_I(4);
    vlSelf->__VdlyVal__SDB_rob_tag__v7 = VL_RAND_RESET_I(6);
    vlSelf->__VdlyVal__is_non_idempotent__v7 = VL_RAND_RESET_I(1);
    vlSelf->__VdlyVal__SDB_addr__v8 = VL_RAND_RESET_I(32);
    vlSelf->__VdlySet__SDB_addr__v8 = 0;
    vlSelf->__VdlyVal__SDB_data__v8 = VL_RAND_RESET_I(32);
    vlSelf->__VdlyVal__st_mask__v8 = VL_RAND_RESET_I(4);
    vlSelf->__VdlyVal__SDB_rob_tag__v8 = VL_RAND_RESET_I(6);
    vlSelf->__VdlyVal__is_non_idempotent__v8 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__SDB_addr__v9 = 0;
    vlSelf->__VdlyVal__SDB_addr__v10 = VL_RAND_RESET_I(32);
    vlSelf->__VdlySet__SDB_addr__v10 = 0;
    vlSelf->__VdlyVal__SDB_data__v10 = VL_RAND_RESET_I(32);
    vlSelf->__VdlyVal__st_mask__v10 = VL_RAND_RESET_I(4);
    vlSelf->__VdlyVal__SDB_rob_tag__v10 = VL_RAND_RESET_I(6);
    vlSelf->__VdlyVal__is_non_idempotent__v10 = VL_RAND_RESET_I(1);
    vlSelf->__VdlyVal__SDB_addr__v11 = VL_RAND_RESET_I(32);
    vlSelf->__VdlySet__SDB_addr__v11 = 0;
    vlSelf->__VdlyVal__SDB_data__v11 = VL_RAND_RESET_I(32);
    vlSelf->__VdlyVal__st_mask__v11 = VL_RAND_RESET_I(4);
    vlSelf->__VdlyVal__SDB_rob_tag__v11 = VL_RAND_RESET_I(6);
    vlSelf->__VdlyVal__is_non_idempotent__v11 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__SDB_addr__v12 = 0;
    vlSelf->__VdlyVal__SDB_addr__v13 = VL_RAND_RESET_I(32);
    vlSelf->__VdlySet__SDB_addr__v13 = 0;
    vlSelf->__VdlyVal__SDB_data__v13 = VL_RAND_RESET_I(32);
    vlSelf->__VdlyVal__st_mask__v13 = VL_RAND_RESET_I(4);
    vlSelf->__VdlyVal__SDB_rob_tag__v13 = VL_RAND_RESET_I(6);
    vlSelf->__VdlyVal__is_non_idempotent__v13 = VL_RAND_RESET_I(1);
    vlSelf->__VdlyVal__SDB_addr__v14 = VL_RAND_RESET_I(32);
    vlSelf->__VdlySet__SDB_addr__v14 = 0;
    vlSelf->__VdlyVal__SDB_data__v14 = VL_RAND_RESET_I(32);
    vlSelf->__VdlyVal__st_mask__v14 = VL_RAND_RESET_I(4);
    vlSelf->__VdlyVal__SDB_rob_tag__v14 = VL_RAND_RESET_I(6);
    vlSelf->__VdlyVal__is_non_idempotent__v14 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__SDB_addr__v15 = 0;
    vlSelf->__VdlyVal__SDB_addr__v16 = VL_RAND_RESET_I(32);
    vlSelf->__VdlySet__SDB_addr__v16 = 0;
    vlSelf->__VdlyVal__SDB_data__v16 = VL_RAND_RESET_I(32);
    vlSelf->__VdlyVal__st_mask__v16 = VL_RAND_RESET_I(4);
    vlSelf->__VdlyVal__SDB_rob_tag__v16 = VL_RAND_RESET_I(6);
    vlSelf->__VdlyVal__is_non_idempotent__v16 = VL_RAND_RESET_I(1);
    vlSelf->__VdlyVal__SDB_addr__v17 = VL_RAND_RESET_I(32);
    vlSelf->__VdlySet__SDB_addr__v17 = 0;
    vlSelf->__VdlyVal__SDB_data__v17 = VL_RAND_RESET_I(32);
    vlSelf->__VdlyVal__st_mask__v17 = VL_RAND_RESET_I(4);
    vlSelf->__VdlyVal__SDB_rob_tag__v17 = VL_RAND_RESET_I(6);
    vlSelf->__VdlyVal__is_non_idempotent__v17 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__SDB_addr__v18 = 0;
    vlSelf->__VdlyVal__SDB_addr__v19 = VL_RAND_RESET_I(32);
    vlSelf->__VdlySet__SDB_addr__v19 = 0;
    vlSelf->__VdlyVal__SDB_data__v19 = VL_RAND_RESET_I(32);
    vlSelf->__VdlyVal__st_mask__v19 = VL_RAND_RESET_I(4);
    vlSelf->__VdlyVal__SDB_rob_tag__v19 = VL_RAND_RESET_I(6);
    vlSelf->__VdlyVal__is_non_idempotent__v19 = VL_RAND_RESET_I(1);
    vlSelf->__VdlyVal__SDB_addr__v20 = VL_RAND_RESET_I(32);
    vlSelf->__VdlySet__SDB_addr__v20 = 0;
    vlSelf->__VdlyVal__SDB_data__v20 = VL_RAND_RESET_I(32);
    vlSelf->__VdlyVal__st_mask__v20 = VL_RAND_RESET_I(4);
    vlSelf->__VdlyVal__SDB_rob_tag__v20 = VL_RAND_RESET_I(6);
    vlSelf->__VdlyVal__is_non_idempotent__v20 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__SDB_addr__v21 = 0;
    vlSelf->__VdlyVal__SDB_addr__v22 = VL_RAND_RESET_I(32);
    vlSelf->__VdlySet__SDB_addr__v22 = 0;
    vlSelf->__VdlyVal__SDB_data__v22 = VL_RAND_RESET_I(32);
    vlSelf->__VdlyVal__st_mask__v22 = VL_RAND_RESET_I(4);
    vlSelf->__VdlyVal__SDB_rob_tag__v22 = VL_RAND_RESET_I(6);
    vlSelf->__VdlyVal__is_non_idempotent__v22 = VL_RAND_RESET_I(1);
    vlSelf->__VdlyVal__SDB_addr__v23 = VL_RAND_RESET_I(32);
    vlSelf->__VdlySet__SDB_addr__v23 = 0;
    vlSelf->__VdlyVal__SDB_data__v23 = VL_RAND_RESET_I(32);
    vlSelf->__VdlyVal__st_mask__v23 = VL_RAND_RESET_I(4);
    vlSelf->__VdlyVal__SDB_rob_tag__v23 = VL_RAND_RESET_I(6);
    vlSelf->__VdlyVal__is_non_idempotent__v23 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__SDB_addr__v24 = 0;
    vlSelf->__VdlyVal__SDB_addr__v25 = VL_RAND_RESET_I(32);
    vlSelf->__VdlySet__SDB_addr__v25 = 0;
    vlSelf->__VdlyVal__SDB_data__v25 = VL_RAND_RESET_I(32);
    vlSelf->__VdlyVal__st_mask__v25 = VL_RAND_RESET_I(4);
    vlSelf->__VdlyVal__SDB_rob_tag__v25 = VL_RAND_RESET_I(6);
    vlSelf->__VdlyVal__is_non_idempotent__v25 = VL_RAND_RESET_I(1);
    vlSelf->__VdlyVal__SDB_addr__v26 = VL_RAND_RESET_I(32);
    vlSelf->__VdlySet__SDB_addr__v26 = 0;
    vlSelf->__VdlyVal__SDB_data__v26 = VL_RAND_RESET_I(32);
    vlSelf->__VdlyVal__st_mask__v26 = VL_RAND_RESET_I(4);
    vlSelf->__VdlyVal__SDB_rob_tag__v26 = VL_RAND_RESET_I(6);
    vlSelf->__VdlyVal__is_non_idempotent__v26 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__SDB_addr__v27 = 0;
    vlSelf->__VdlyVal__SDB_addr__v28 = VL_RAND_RESET_I(32);
    vlSelf->__VdlySet__SDB_addr__v28 = 0;
    vlSelf->__VdlyVal__SDB_data__v28 = VL_RAND_RESET_I(32);
    vlSelf->__VdlyVal__st_mask__v28 = VL_RAND_RESET_I(4);
    vlSelf->__VdlyVal__SDB_rob_tag__v28 = VL_RAND_RESET_I(6);
    vlSelf->__VdlyVal__is_non_idempotent__v28 = VL_RAND_RESET_I(1);
    vlSelf->__VdlyVal__SDB_addr__v29 = VL_RAND_RESET_I(32);
    vlSelf->__VdlySet__SDB_addr__v29 = 0;
    vlSelf->__VdlyVal__SDB_data__v29 = VL_RAND_RESET_I(32);
    vlSelf->__VdlyVal__st_mask__v29 = VL_RAND_RESET_I(4);
    vlSelf->__VdlyVal__SDB_rob_tag__v29 = VL_RAND_RESET_I(6);
    vlSelf->__VdlyVal__is_non_idempotent__v29 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__SDB_addr__v30 = 0;
    vlSelf->__VdlyVal__SDB_addr__v31 = VL_RAND_RESET_I(32);
    vlSelf->__VdlySet__SDB_addr__v31 = 0;
    vlSelf->__VdlyVal__SDB_data__v31 = VL_RAND_RESET_I(32);
    vlSelf->__VdlyVal__st_mask__v31 = VL_RAND_RESET_I(4);
    vlSelf->__VdlyVal__SDB_rob_tag__v31 = VL_RAND_RESET_I(6);
    vlSelf->__VdlyVal__is_non_idempotent__v31 = VL_RAND_RESET_I(1);
    vlSelf->__VdlyVal__SDB_addr__v32 = VL_RAND_RESET_I(32);
    vlSelf->__VdlySet__SDB_addr__v32 = 0;
    vlSelf->__VdlyVal__SDB_data__v32 = VL_RAND_RESET_I(32);
    vlSelf->__VdlyVal__st_mask__v32 = VL_RAND_RESET_I(4);
    vlSelf->__VdlyVal__SDB_rob_tag__v32 = VL_RAND_RESET_I(6);
    vlSelf->__VdlyVal__is_non_idempotent__v32 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__SDB_addr__v33 = 0;
    vlSelf->__VdlyVal__SDB_addr__v34 = VL_RAND_RESET_I(32);
    vlSelf->__VdlySet__SDB_addr__v34 = 0;
    vlSelf->__VdlyVal__SDB_data__v34 = VL_RAND_RESET_I(32);
    vlSelf->__VdlyVal__st_mask__v34 = VL_RAND_RESET_I(4);
    vlSelf->__VdlyVal__SDB_rob_tag__v34 = VL_RAND_RESET_I(6);
    vlSelf->__VdlyVal__is_non_idempotent__v34 = VL_RAND_RESET_I(1);
    vlSelf->__VdlyVal__SDB_addr__v35 = VL_RAND_RESET_I(32);
    vlSelf->__VdlySet__SDB_addr__v35 = 0;
    vlSelf->__VdlyVal__SDB_data__v35 = VL_RAND_RESET_I(32);
    vlSelf->__VdlyVal__st_mask__v35 = VL_RAND_RESET_I(4);
    vlSelf->__VdlyVal__SDB_rob_tag__v35 = VL_RAND_RESET_I(6);
    vlSelf->__VdlyVal__is_non_idempotent__v35 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__SDB_addr__v36 = 0;
    vlSelf->__VdlyVal__SDB_addr__v37 = VL_RAND_RESET_I(32);
    vlSelf->__VdlySet__SDB_addr__v37 = 0;
    vlSelf->__VdlyVal__SDB_data__v37 = VL_RAND_RESET_I(32);
    vlSelf->__VdlyVal__st_mask__v37 = VL_RAND_RESET_I(4);
    vlSelf->__VdlyVal__SDB_rob_tag__v37 = VL_RAND_RESET_I(6);
    vlSelf->__VdlyVal__is_non_idempotent__v37 = VL_RAND_RESET_I(1);
    vlSelf->__VdlyVal__SDB_addr__v38 = VL_RAND_RESET_I(32);
    vlSelf->__VdlySet__SDB_addr__v38 = 0;
    vlSelf->__VdlyVal__SDB_data__v38 = VL_RAND_RESET_I(32);
    vlSelf->__VdlyVal__st_mask__v38 = VL_RAND_RESET_I(4);
    vlSelf->__VdlyVal__SDB_rob_tag__v38 = VL_RAND_RESET_I(6);
    vlSelf->__VdlyVal__is_non_idempotent__v38 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__SDB_addr__v39 = 0;
    vlSelf->__VdlyVal__SDB_addr__v40 = VL_RAND_RESET_I(32);
    vlSelf->__VdlySet__SDB_addr__v40 = 0;
    vlSelf->__VdlyVal__SDB_data__v40 = VL_RAND_RESET_I(32);
    vlSelf->__VdlyVal__st_mask__v40 = VL_RAND_RESET_I(4);
    vlSelf->__VdlyVal__SDB_rob_tag__v40 = VL_RAND_RESET_I(6);
    vlSelf->__VdlyVal__is_non_idempotent__v40 = VL_RAND_RESET_I(1);
    vlSelf->__VdlyVal__SDB_addr__v41 = VL_RAND_RESET_I(32);
    vlSelf->__VdlySet__SDB_addr__v41 = 0;
    vlSelf->__VdlyVal__SDB_data__v41 = VL_RAND_RESET_I(32);
    vlSelf->__VdlyVal__st_mask__v41 = VL_RAND_RESET_I(4);
    vlSelf->__VdlyVal__SDB_rob_tag__v41 = VL_RAND_RESET_I(6);
    vlSelf->__VdlyVal__is_non_idempotent__v41 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__SDB_addr__v42 = 0;
    vlSelf->__VdlyVal__SDB_addr__v43 = VL_RAND_RESET_I(32);
    vlSelf->__VdlySet__SDB_addr__v43 = 0;
    vlSelf->__VdlyVal__SDB_data__v43 = VL_RAND_RESET_I(32);
    vlSelf->__VdlyVal__st_mask__v43 = VL_RAND_RESET_I(4);
    vlSelf->__VdlyVal__SDB_rob_tag__v43 = VL_RAND_RESET_I(6);
    vlSelf->__VdlyVal__is_non_idempotent__v43 = VL_RAND_RESET_I(1);
    vlSelf->__VdlyVal__SDB_addr__v44 = VL_RAND_RESET_I(32);
    vlSelf->__VdlySet__SDB_addr__v44 = 0;
    vlSelf->__VdlyVal__SDB_data__v44 = VL_RAND_RESET_I(32);
    vlSelf->__VdlyVal__st_mask__v44 = VL_RAND_RESET_I(4);
    vlSelf->__VdlyVal__SDB_rob_tag__v44 = VL_RAND_RESET_I(6);
    vlSelf->__VdlyVal__is_non_idempotent__v44 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__SDB_addr__v45 = 0;
    vlSelf->__VdlyVal__SDB_addr__v46 = VL_RAND_RESET_I(32);
    vlSelf->__VdlySet__SDB_addr__v46 = 0;
    vlSelf->__VdlyVal__SDB_data__v46 = VL_RAND_RESET_I(32);
    vlSelf->__VdlyVal__st_mask__v46 = VL_RAND_RESET_I(4);
    vlSelf->__VdlyVal__SDB_rob_tag__v46 = VL_RAND_RESET_I(6);
    vlSelf->__VdlyVal__is_non_idempotent__v46 = VL_RAND_RESET_I(1);
    vlSelf->__VdlyVal__SDB_addr__v47 = VL_RAND_RESET_I(32);
    vlSelf->__VdlySet__SDB_addr__v47 = 0;
    vlSelf->__VdlyVal__SDB_data__v47 = VL_RAND_RESET_I(32);
    vlSelf->__VdlyVal__st_mask__v47 = VL_RAND_RESET_I(4);
    vlSelf->__VdlyVal__SDB_rob_tag__v47 = VL_RAND_RESET_I(6);
    vlSelf->__VdlyVal__is_non_idempotent__v47 = VL_RAND_RESET_I(1);
    vlSelf->__VdlyVal__valid__v0 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__valid__v0 = 0;
    vlSelf->__VdlyVal__valid__v1 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__valid__v1 = 0;
    vlSelf->__VdlyVal__valid__v2 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__valid__v2 = 0;
    vlSelf->__VdlyVal__valid__v3 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__valid__v3 = 0;
    vlSelf->__VdlyVal__valid__v4 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__valid__v4 = 0;
    vlSelf->__VdlyVal__valid__v5 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__valid__v5 = 0;
    vlSelf->__VdlyVal__valid__v6 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__valid__v6 = 0;
    vlSelf->__VdlyVal__valid__v7 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__valid__v7 = 0;
    vlSelf->__VdlyVal__valid__v8 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__valid__v8 = 0;
    vlSelf->__VdlyVal__valid__v9 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__valid__v9 = 0;
    vlSelf->__VdlyVal__valid__v10 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__valid__v10 = 0;
    vlSelf->__VdlyVal__valid__v11 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__valid__v11 = 0;
    vlSelf->__VdlyVal__valid__v12 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__valid__v12 = 0;
    vlSelf->__VdlyVal__valid__v13 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__valid__v13 = 0;
    vlSelf->__VdlyVal__valid__v14 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__valid__v14 = 0;
    vlSelf->__VdlyVal__valid__v15 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__valid__v15 = 0;
    vlSelf->__VdlyVal__retirement__v0 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__retirement__v0 = 0;
    vlSelf->__VdlyVal__retirement__v1 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__retirement__v1 = 0;
    vlSelf->__VdlyVal__retirement__v2 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__retirement__v2 = 0;
    vlSelf->__VdlyVal__retirement__v3 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__retirement__v3 = 0;
    vlSelf->__VdlyVal__retirement__v4 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__retirement__v4 = 0;
    vlSelf->__VdlyVal__retirement__v5 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__retirement__v5 = 0;
    vlSelf->__VdlyVal__retirement__v6 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__retirement__v6 = 0;
    vlSelf->__VdlyVal__retirement__v7 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__retirement__v7 = 0;
    vlSelf->__VdlyVal__retirement__v8 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__retirement__v8 = 0;
    vlSelf->__VdlyVal__retirement__v9 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__retirement__v9 = 0;
    vlSelf->__VdlyVal__retirement__v10 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__retirement__v10 = 0;
    vlSelf->__VdlyVal__retirement__v11 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__retirement__v11 = 0;
    vlSelf->__VdlyVal__retirement__v12 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__retirement__v12 = 0;
    vlSelf->__VdlyVal__retirement__v13 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__retirement__v13 = 0;
    vlSelf->__VdlyVal__retirement__v14 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__retirement__v14 = 0;
    vlSelf->__VdlyVal__retirement__v15 = VL_RAND_RESET_I(1);
    vlSelf->__VdlySet__retirement__v15 = 0;
}
