// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vfalco_top.h for the primary calling header

#ifndef VERILATED_VFALCO_TOP_REGISTER_MAP_TABLE_H_
#define VERILATED_VFALCO_TOP_REGISTER_MAP_TABLE_H_  // guard

#include "verilated.h"


class Vfalco_top__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vfalco_top_register_map_table final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(__PVT__clk,0,0);
        VL_IN8(__PVT__rst,0,0);
        VL_IN8(__PVT__recovery_mode,0,0);
        VL_IN8(__PVT__recovery_map_arf_0,4,0);
        VL_IN8(__PVT__recovery_map_prf_0,5,0);
        VL_IN8(__PVT__recovery_map_arf_1,4,0);
        VL_IN8(__PVT__recovery_map_prf_1,5,0);
        VL_IN8(__PVT__recovery_map_0_valid,0,0);
        VL_IN8(__PVT__recovery_map_1_valid,0,0);
        VL_IN8(instr0_rd,4,0);
        VL_IN8(__PVT__instr0_rs1,4,0);
        VL_IN8(__PVT__instr0_rs2,4,0);
        VL_IN8(__PVT__instr0_rd_new_prf,5,0);
        VL_IN8(instr0_rd_new_map_valid,0,0);
        VL_OUT8(__PVT__instr0_rd_stale_prf,5,0);
        VL_OUT8(__PVT__instr0_rs1_prf,5,0);
        VL_OUT8(__PVT__instr0_rs2_prf,5,0);
        VL_IN8(instr1_rd,4,0);
        VL_IN8(__PVT__instr1_rs1,4,0);
        VL_IN8(__PVT__instr1_rs2,4,0);
        VL_IN8(__PVT__instr1_rd_new_prf,5,0);
        VL_IN8(instr1_rd_new_map_valid,0,0);
        VL_OUT8(__PVT__instr1_rd_stale_prf,5,0);
        VL_OUT8(__PVT__instr1_rs1_prf,5,0);
        VL_OUT8(__PVT__instr1_rs2_prf,5,0);
        VL_IN8(__PVT__recovery_flush,0,0);
        VL_IN8(__PVT__recovery_no_copy,0,0);
        VL_IN8(__PVT__recovery_target_rob_tag,5,0);
        VL_IN8(__PVT__instr0_rob_tag,5,0);
        VL_IN8(__PVT__instr1_rob_tag,5,0);
        VL_IN8(__PVT__instr0_valid,0,0);
        VL_IN8(__PVT__instr1_valid,0,0);
        CData/*2:0*/ recovery_target;
        CData/*0:0*/ __PVT__instr0_copy;
        CData/*0:0*/ __PVT__instr1_copy;
        CData/*2:0*/ __PVT__copy_target;
        CData/*0:0*/ __VdlySet__reg_map_table__v0;
        CData/*0:0*/ __VdlySet__reg_map_table__v1;
        CData/*0:0*/ __VdlySet__reg_map_table__v2;
        CData/*0:0*/ __VdlySet__reg_map_table__v3;
        CData/*0:0*/ __VdlySet__reg_map_table__v4;
        CData/*0:0*/ __VdlySet__reg_map_table__v5;
        CData/*0:0*/ __VdlySet__reg_map_table__v6;
        CData/*0:0*/ __VdlySet__reg_map_table__v7;
        CData/*0:0*/ __VdlySet__reg_map_table__v8;
        CData/*0:0*/ __VdlySet__reg_map_table__v9;
        CData/*0:0*/ __VdlySet__reg_map_table__v10;
        CData/*0:0*/ __VdlySet__reg_map_table__v11;
        CData/*0:0*/ __VdlySet__reg_map_table__v12;
        CData/*0:0*/ __VdlySet__reg_map_table__v13;
        CData/*0:0*/ __VdlySet__reg_map_table__v14;
        CData/*0:0*/ __VdlySet__reg_map_table__v15;
        CData/*0:0*/ __VdlySet__reg_map_table__v16;
        CData/*0:0*/ __VdlySet__reg_map_table__v17;
        CData/*0:0*/ __VdlySet__reg_map_table__v18;
        CData/*0:0*/ __VdlySet__reg_map_table__v19;
        CData/*0:0*/ __VdlySet__reg_map_table__v20;
        CData/*0:0*/ __VdlySet__reg_map_table__v21;
        CData/*0:0*/ __VdlySet__reg_map_table__v22;
        CData/*0:0*/ __VdlySet__reg_map_table__v23;
        CData/*0:0*/ __VdlySet__reg_map_table__v24;
        CData/*0:0*/ __VdlySet__reg_map_table__v25;
        CData/*0:0*/ __VdlySet__reg_map_table__v26;
        CData/*0:0*/ __VdlySet__reg_map_table__v27;
    };
    struct {
        CData/*0:0*/ __VdlySet__reg_map_table__v28;
        CData/*0:0*/ __VdlySet__reg_map_table__v29;
        CData/*0:0*/ __VdlySet__reg_map_table__v30;
        CData/*0:0*/ __VdlySet__reg_map_table__v31;
        CData/*5:0*/ __VdlyVal__reg_map_table__v32;
        CData/*0:0*/ __VdlySet__reg_map_table__v32;
        CData/*5:0*/ __VdlyVal__reg_map_table__v33;
        CData/*0:0*/ __VdlySet__reg_map_table__v33;
        CData/*5:0*/ __VdlyVal__reg_map_table__v34;
        CData/*0:0*/ __VdlySet__reg_map_table__v34;
        CData/*5:0*/ __VdlyVal__reg_map_table__v35;
        CData/*0:0*/ __VdlySet__reg_map_table__v35;
        CData/*5:0*/ __VdlyVal__reg_map_table__v36;
        CData/*0:0*/ __VdlySet__reg_map_table__v36;
        CData/*5:0*/ __VdlyVal__reg_map_table__v37;
        CData/*0:0*/ __VdlySet__reg_map_table__v37;
        CData/*5:0*/ __VdlyVal__reg_map_table__v38;
        CData/*0:0*/ __VdlySet__reg_map_table__v38;
        CData/*5:0*/ __VdlyVal__reg_map_table__v39;
        CData/*0:0*/ __VdlySet__reg_map_table__v39;
        CData/*5:0*/ __VdlyVal__reg_map_table__v40;
        CData/*0:0*/ __VdlySet__reg_map_table__v40;
        CData/*5:0*/ __VdlyVal__reg_map_table__v41;
        CData/*0:0*/ __VdlySet__reg_map_table__v41;
        CData/*5:0*/ __VdlyVal__reg_map_table__v42;
        CData/*0:0*/ __VdlySet__reg_map_table__v42;
        CData/*5:0*/ __VdlyVal__reg_map_table__v43;
        CData/*0:0*/ __VdlySet__reg_map_table__v43;
        CData/*5:0*/ __VdlyVal__reg_map_table__v44;
        CData/*0:0*/ __VdlySet__reg_map_table__v44;
        CData/*5:0*/ __VdlyVal__reg_map_table__v45;
        CData/*0:0*/ __VdlySet__reg_map_table__v45;
        CData/*5:0*/ __VdlyVal__reg_map_table__v46;
        CData/*0:0*/ __VdlySet__reg_map_table__v46;
        CData/*5:0*/ __VdlyVal__reg_map_table__v47;
        CData/*0:0*/ __VdlySet__reg_map_table__v47;
        CData/*5:0*/ __VdlyVal__reg_map_table__v48;
        CData/*0:0*/ __VdlySet__reg_map_table__v48;
        CData/*5:0*/ __VdlyVal__reg_map_table__v49;
        CData/*0:0*/ __VdlySet__reg_map_table__v49;
        CData/*5:0*/ __VdlyVal__reg_map_table__v50;
        CData/*0:0*/ __VdlySet__reg_map_table__v50;
        CData/*5:0*/ __VdlyVal__reg_map_table__v51;
        CData/*0:0*/ __VdlySet__reg_map_table__v51;
        CData/*5:0*/ __VdlyVal__reg_map_table__v52;
        CData/*0:0*/ __VdlySet__reg_map_table__v52;
        CData/*5:0*/ __VdlyVal__reg_map_table__v53;
        CData/*0:0*/ __VdlySet__reg_map_table__v53;
        CData/*5:0*/ __VdlyVal__reg_map_table__v54;
        CData/*0:0*/ __VdlySet__reg_map_table__v54;
        CData/*5:0*/ __VdlyVal__reg_map_table__v55;
        CData/*0:0*/ __VdlySet__reg_map_table__v55;
        CData/*5:0*/ __VdlyVal__reg_map_table__v56;
        CData/*0:0*/ __VdlySet__reg_map_table__v56;
        CData/*5:0*/ __VdlyVal__reg_map_table__v57;
        CData/*0:0*/ __VdlySet__reg_map_table__v57;
        CData/*5:0*/ __VdlyVal__reg_map_table__v58;
        CData/*0:0*/ __VdlySet__reg_map_table__v58;
        CData/*5:0*/ __VdlyVal__reg_map_table__v59;
        CData/*0:0*/ __VdlySet__reg_map_table__v59;
        CData/*5:0*/ __VdlyVal__reg_map_table__v60;
        CData/*0:0*/ __VdlySet__reg_map_table__v60;
        CData/*5:0*/ __VdlyVal__reg_map_table__v61;
        CData/*0:0*/ __VdlySet__reg_map_table__v61;
    };
    struct {
        CData/*5:0*/ __VdlyVal__reg_map_table__v62;
        CData/*0:0*/ __VdlySet__reg_map_table__v62;
        CData/*5:0*/ __VdlyVal__reg_map_table__v63;
        CData/*0:0*/ __VdlySet__reg_map_table__v63;
        CData/*5:0*/ __VdlyVal__reg_map_table__v64;
        CData/*4:0*/ __VdlyDim0__reg_map_table__v64;
        CData/*0:0*/ __VdlySet__reg_map_table__v64;
        CData/*5:0*/ __VdlyVal__reg_map_table__v65;
        CData/*4:0*/ __VdlyDim0__reg_map_table__v65;
        CData/*0:0*/ __VdlySet__reg_map_table__v65;
        CData/*5:0*/ __VdlyVal__reg_map_table__v66;
        CData/*4:0*/ __VdlyDim0__reg_map_table__v66;
        CData/*0:0*/ __VdlySet__reg_map_table__v66;
        CData/*5:0*/ __VdlyVal__reg_map_table__v67;
        CData/*4:0*/ __VdlyDim0__reg_map_table__v67;
        CData/*0:0*/ __VdlySet__reg_map_table__v67;
        CData/*5:0*/ __VdlyVal__reg_map_table__v68;
        CData/*4:0*/ __VdlyDim0__reg_map_table__v68;
        CData/*0:0*/ __VdlySet__reg_map_table__v68;
        CData/*5:0*/ __VdlyVal__reg_map_table__v69;
        CData/*4:0*/ __VdlyDim0__reg_map_table__v69;
        CData/*0:0*/ __VdlySet__reg_map_table__v69;
        CData/*5:0*/ __VdlyVal__copy_table__v0;
        CData/*0:0*/ __VdlySet__copy_table__v0;
        CData/*5:0*/ __VdlyVal__copy_table__v1;
        CData/*0:0*/ __VdlySet__copy_table__v1;
        CData/*5:0*/ __VdlyVal__copy_table__v2;
        CData/*0:0*/ __VdlySet__copy_table__v2;
        CData/*5:0*/ __VdlyVal__copy_table__v3;
        CData/*0:0*/ __VdlySet__copy_table__v3;
        CData/*5:0*/ __VdlyVal__copy_table__v4;
        CData/*0:0*/ __VdlySet__copy_table__v4;
        CData/*5:0*/ __VdlyVal__copy_table__v5;
        CData/*0:0*/ __VdlySet__copy_table__v5;
        CData/*5:0*/ __VdlyVal__copy_table__v6;
        CData/*0:0*/ __VdlySet__copy_table__v6;
        CData/*5:0*/ __VdlyVal__copy_table__v7;
        CData/*0:0*/ __VdlySet__copy_table__v7;
        CData/*5:0*/ __VdlyVal__copy_table__v8;
        CData/*0:0*/ __VdlySet__copy_table__v8;
        CData/*5:0*/ __VdlyVal__copy_table__v9;
        CData/*0:0*/ __VdlySet__copy_table__v9;
        CData/*5:0*/ __VdlyVal__copy_table__v10;
        CData/*0:0*/ __VdlySet__copy_table__v10;
        CData/*5:0*/ __VdlyVal__copy_table__v11;
        CData/*0:0*/ __VdlySet__copy_table__v11;
        CData/*5:0*/ __VdlyVal__copy_table__v12;
        CData/*0:0*/ __VdlySet__copy_table__v12;
        CData/*5:0*/ __VdlyVal__copy_table__v13;
        CData/*0:0*/ __VdlySet__copy_table__v13;
        CData/*5:0*/ __VdlyVal__copy_table__v14;
        CData/*0:0*/ __VdlySet__copy_table__v14;
        CData/*5:0*/ __VdlyVal__copy_table__v15;
        CData/*0:0*/ __VdlySet__copy_table__v15;
        CData/*5:0*/ __VdlyVal__copy_table__v16;
        CData/*0:0*/ __VdlySet__copy_table__v16;
        CData/*5:0*/ __VdlyVal__copy_table__v17;
        CData/*0:0*/ __VdlySet__copy_table__v17;
        CData/*5:0*/ __VdlyVal__copy_table__v18;
        CData/*0:0*/ __VdlySet__copy_table__v18;
        CData/*5:0*/ __VdlyVal__copy_table__v19;
        CData/*0:0*/ __VdlySet__copy_table__v19;
        CData/*5:0*/ __VdlyVal__copy_table__v20;
        CData/*0:0*/ __VdlySet__copy_table__v20;
    };
    struct {
        CData/*5:0*/ __VdlyVal__copy_table__v21;
        CData/*0:0*/ __VdlySet__copy_table__v21;
        CData/*5:0*/ __VdlyVal__copy_table__v22;
        CData/*0:0*/ __VdlySet__copy_table__v22;
        CData/*5:0*/ __VdlyVal__copy_table__v23;
        CData/*0:0*/ __VdlySet__copy_table__v23;
        CData/*5:0*/ __VdlyVal__copy_table__v24;
        CData/*0:0*/ __VdlySet__copy_table__v24;
        CData/*5:0*/ __VdlyVal__copy_table__v25;
        CData/*0:0*/ __VdlySet__copy_table__v25;
        CData/*5:0*/ __VdlyVal__copy_table__v26;
        CData/*0:0*/ __VdlySet__copy_table__v26;
        CData/*5:0*/ __VdlyVal__copy_table__v27;
        CData/*0:0*/ __VdlySet__copy_table__v27;
        CData/*5:0*/ __VdlyVal__copy_table__v28;
        CData/*0:0*/ __VdlySet__copy_table__v28;
        CData/*5:0*/ __VdlyVal__copy_table__v29;
        CData/*0:0*/ __VdlySet__copy_table__v29;
        CData/*5:0*/ __VdlyVal__copy_table__v30;
        CData/*0:0*/ __VdlySet__copy_table__v30;
        CData/*5:0*/ __VdlyVal__copy_table__v31;
        CData/*0:0*/ __VdlySet__copy_table__v31;
        CData/*5:0*/ __VdlyVal__copy_table__v32;
        CData/*0:0*/ __VdlySet__copy_table__v32;
        CData/*5:0*/ __VdlyVal__copy_table__v33;
        CData/*0:0*/ __VdlySet__copy_table__v33;
        CData/*5:0*/ __VdlyVal__copy_table__v34;
        CData/*0:0*/ __VdlySet__copy_table__v34;
        CData/*5:0*/ __VdlyVal__copy_table__v35;
        CData/*0:0*/ __VdlySet__copy_table__v35;
        CData/*5:0*/ __VdlyVal__copy_table__v36;
        CData/*0:0*/ __VdlySet__copy_table__v36;
        CData/*5:0*/ __VdlyVal__copy_table__v37;
        CData/*0:0*/ __VdlySet__copy_table__v37;
        CData/*5:0*/ __VdlyVal__copy_table__v38;
        CData/*0:0*/ __VdlySet__copy_table__v38;
        CData/*5:0*/ __VdlyVal__copy_table__v39;
        CData/*0:0*/ __VdlySet__copy_table__v39;
        CData/*5:0*/ __VdlyVal__copy_table__v40;
        CData/*0:0*/ __VdlySet__copy_table__v40;
        CData/*5:0*/ __VdlyVal__copy_table__v41;
        CData/*0:0*/ __VdlySet__copy_table__v41;
        CData/*5:0*/ __VdlyVal__copy_table__v42;
        CData/*0:0*/ __VdlySet__copy_table__v42;
        CData/*5:0*/ __VdlyVal__copy_table__v43;
        CData/*0:0*/ __VdlySet__copy_table__v43;
        CData/*5:0*/ __VdlyVal__copy_table__v44;
        CData/*0:0*/ __VdlySet__copy_table__v44;
        CData/*5:0*/ __VdlyVal__copy_table__v45;
        CData/*0:0*/ __VdlySet__copy_table__v45;
        CData/*5:0*/ __VdlyVal__copy_table__v46;
        CData/*0:0*/ __VdlySet__copy_table__v46;
        CData/*5:0*/ __VdlyVal__copy_table__v47;
        CData/*0:0*/ __VdlySet__copy_table__v47;
        CData/*5:0*/ __VdlyVal__copy_table__v48;
        CData/*0:0*/ __VdlySet__copy_table__v48;
        CData/*5:0*/ __VdlyVal__copy_table__v49;
        CData/*0:0*/ __VdlySet__copy_table__v49;
        CData/*5:0*/ __VdlyVal__copy_table__v50;
        CData/*0:0*/ __VdlySet__copy_table__v50;
        CData/*5:0*/ __VdlyVal__copy_table__v51;
        CData/*0:0*/ __VdlySet__copy_table__v51;
        CData/*5:0*/ __VdlyVal__copy_table__v52;
        CData/*0:0*/ __VdlySet__copy_table__v52;
    };
    struct {
        CData/*5:0*/ __VdlyVal__copy_table__v53;
        CData/*0:0*/ __VdlySet__copy_table__v53;
        CData/*5:0*/ __VdlyVal__copy_table__v54;
        CData/*0:0*/ __VdlySet__copy_table__v54;
        CData/*5:0*/ __VdlyVal__copy_table__v55;
        CData/*0:0*/ __VdlySet__copy_table__v55;
        CData/*5:0*/ __VdlyVal__copy_table__v56;
        CData/*0:0*/ __VdlySet__copy_table__v56;
        CData/*5:0*/ __VdlyVal__copy_table__v57;
        CData/*0:0*/ __VdlySet__copy_table__v57;
        CData/*5:0*/ __VdlyVal__copy_table__v58;
        CData/*0:0*/ __VdlySet__copy_table__v58;
        CData/*5:0*/ __VdlyVal__copy_table__v59;
        CData/*0:0*/ __VdlySet__copy_table__v59;
        CData/*5:0*/ __VdlyVal__copy_table__v60;
        CData/*0:0*/ __VdlySet__copy_table__v60;
        CData/*5:0*/ __VdlyVal__copy_table__v61;
        CData/*0:0*/ __VdlySet__copy_table__v61;
        CData/*5:0*/ __VdlyVal__copy_table__v62;
        CData/*0:0*/ __VdlySet__copy_table__v62;
        CData/*5:0*/ __VdlyVal__copy_table__v63;
        CData/*0:0*/ __VdlySet__copy_table__v63;
        CData/*5:0*/ __VdlyVal__copy_table__v64;
        CData/*0:0*/ __VdlySet__copy_table__v64;
        CData/*5:0*/ __VdlyVal__copy_table__v65;
        CData/*0:0*/ __VdlySet__copy_table__v65;
        CData/*5:0*/ __VdlyVal__copy_table__v66;
        CData/*0:0*/ __VdlySet__copy_table__v66;
        CData/*5:0*/ __VdlyVal__copy_table__v67;
        CData/*0:0*/ __VdlySet__copy_table__v67;
        CData/*5:0*/ __VdlyVal__copy_table__v68;
        CData/*0:0*/ __VdlySet__copy_table__v68;
        CData/*5:0*/ __VdlyVal__copy_table__v69;
        CData/*0:0*/ __VdlySet__copy_table__v69;
        CData/*5:0*/ __VdlyVal__copy_table__v70;
        CData/*0:0*/ __VdlySet__copy_table__v70;
        CData/*5:0*/ __VdlyVal__copy_table__v71;
        CData/*0:0*/ __VdlySet__copy_table__v71;
        CData/*5:0*/ __VdlyVal__copy_table__v72;
        CData/*0:0*/ __VdlySet__copy_table__v72;
        CData/*5:0*/ __VdlyVal__copy_table__v73;
        CData/*0:0*/ __VdlySet__copy_table__v73;
        CData/*5:0*/ __VdlyVal__copy_table__v74;
        CData/*0:0*/ __VdlySet__copy_table__v74;
        CData/*5:0*/ __VdlyVal__copy_table__v75;
        CData/*0:0*/ __VdlySet__copy_table__v75;
        CData/*5:0*/ __VdlyVal__copy_table__v76;
        CData/*0:0*/ __VdlySet__copy_table__v76;
        CData/*5:0*/ __VdlyVal__copy_table__v77;
        CData/*0:0*/ __VdlySet__copy_table__v77;
        CData/*5:0*/ __VdlyVal__copy_table__v78;
        CData/*0:0*/ __VdlySet__copy_table__v78;
        CData/*5:0*/ __VdlyVal__copy_table__v79;
        CData/*0:0*/ __VdlySet__copy_table__v79;
        CData/*5:0*/ __VdlyVal__copy_table__v80;
        CData/*0:0*/ __VdlySet__copy_table__v80;
        CData/*5:0*/ __VdlyVal__copy_table__v81;
        CData/*0:0*/ __VdlySet__copy_table__v81;
        CData/*5:0*/ __VdlyVal__copy_table__v82;
        CData/*0:0*/ __VdlySet__copy_table__v82;
        CData/*5:0*/ __VdlyVal__copy_table__v83;
        CData/*0:0*/ __VdlySet__copy_table__v83;
        CData/*5:0*/ __VdlyVal__copy_table__v84;
        CData/*0:0*/ __VdlySet__copy_table__v84;
    };
    struct {
        CData/*5:0*/ __VdlyVal__copy_table__v85;
        CData/*0:0*/ __VdlySet__copy_table__v85;
        CData/*5:0*/ __VdlyVal__copy_table__v86;
        CData/*0:0*/ __VdlySet__copy_table__v86;
        CData/*5:0*/ __VdlyVal__copy_table__v87;
        CData/*0:0*/ __VdlySet__copy_table__v87;
        CData/*5:0*/ __VdlyVal__copy_table__v88;
        CData/*0:0*/ __VdlySet__copy_table__v88;
        CData/*5:0*/ __VdlyVal__copy_table__v89;
        CData/*0:0*/ __VdlySet__copy_table__v89;
        CData/*5:0*/ __VdlyVal__copy_table__v90;
        CData/*0:0*/ __VdlySet__copy_table__v90;
        CData/*5:0*/ __VdlyVal__copy_table__v91;
        CData/*0:0*/ __VdlySet__copy_table__v91;
        CData/*5:0*/ __VdlyVal__copy_table__v92;
        CData/*0:0*/ __VdlySet__copy_table__v92;
        CData/*5:0*/ __VdlyVal__copy_table__v93;
        CData/*0:0*/ __VdlySet__copy_table__v93;
        CData/*5:0*/ __VdlyVal__copy_table__v94;
        CData/*0:0*/ __VdlySet__copy_table__v94;
        CData/*5:0*/ __VdlyVal__copy_table__v95;
        CData/*0:0*/ __VdlySet__copy_table__v95;
        CData/*5:0*/ __VdlyVal__copy_table__v96;
        CData/*0:0*/ __VdlySet__copy_table__v96;
        CData/*5:0*/ __VdlyVal__copy_table__v97;
        CData/*0:0*/ __VdlySet__copy_table__v97;
        CData/*5:0*/ __VdlyVal__copy_table__v98;
        CData/*0:0*/ __VdlySet__copy_table__v98;
        CData/*5:0*/ __VdlyVal__copy_table__v99;
        CData/*0:0*/ __VdlySet__copy_table__v99;
        CData/*5:0*/ __VdlyVal__copy_table__v100;
        CData/*0:0*/ __VdlySet__copy_table__v100;
        CData/*5:0*/ __VdlyVal__copy_table__v101;
        CData/*0:0*/ __VdlySet__copy_table__v101;
        CData/*5:0*/ __VdlyVal__copy_table__v102;
        CData/*0:0*/ __VdlySet__copy_table__v102;
        CData/*5:0*/ __VdlyVal__copy_table__v103;
        CData/*0:0*/ __VdlySet__copy_table__v103;
        CData/*5:0*/ __VdlyVal__copy_table__v104;
        CData/*0:0*/ __VdlySet__copy_table__v104;
        CData/*5:0*/ __VdlyVal__copy_table__v105;
        CData/*0:0*/ __VdlySet__copy_table__v105;
        CData/*5:0*/ __VdlyVal__copy_table__v106;
        CData/*0:0*/ __VdlySet__copy_table__v106;
        CData/*5:0*/ __VdlyVal__copy_table__v107;
        CData/*0:0*/ __VdlySet__copy_table__v107;
        CData/*5:0*/ __VdlyVal__copy_table__v108;
        CData/*0:0*/ __VdlySet__copy_table__v108;
        CData/*5:0*/ __VdlyVal__copy_table__v109;
        CData/*0:0*/ __VdlySet__copy_table__v109;
        CData/*5:0*/ __VdlyVal__copy_table__v110;
        CData/*0:0*/ __VdlySet__copy_table__v110;
        CData/*5:0*/ __VdlyVal__copy_table__v111;
        CData/*0:0*/ __VdlySet__copy_table__v111;
        CData/*5:0*/ __VdlyVal__copy_table__v112;
        CData/*0:0*/ __VdlySet__copy_table__v112;
        CData/*5:0*/ __VdlyVal__copy_table__v113;
        CData/*0:0*/ __VdlySet__copy_table__v113;
        CData/*5:0*/ __VdlyVal__copy_table__v114;
        CData/*0:0*/ __VdlySet__copy_table__v114;
        CData/*5:0*/ __VdlyVal__copy_table__v115;
        CData/*0:0*/ __VdlySet__copy_table__v115;
        CData/*5:0*/ __VdlyVal__copy_table__v116;
        CData/*0:0*/ __VdlySet__copy_table__v116;
    };
    struct {
        CData/*5:0*/ __VdlyVal__copy_table__v117;
        CData/*0:0*/ __VdlySet__copy_table__v117;
        CData/*5:0*/ __VdlyVal__copy_table__v118;
        CData/*0:0*/ __VdlySet__copy_table__v118;
        CData/*5:0*/ __VdlyVal__copy_table__v119;
        CData/*0:0*/ __VdlySet__copy_table__v119;
        CData/*5:0*/ __VdlyVal__copy_table__v120;
        CData/*0:0*/ __VdlySet__copy_table__v120;
        CData/*5:0*/ __VdlyVal__copy_table__v121;
        CData/*0:0*/ __VdlySet__copy_table__v121;
        CData/*5:0*/ __VdlyVal__copy_table__v122;
        CData/*0:0*/ __VdlySet__copy_table__v122;
        CData/*5:0*/ __VdlyVal__copy_table__v123;
        CData/*0:0*/ __VdlySet__copy_table__v123;
        CData/*5:0*/ __VdlyVal__copy_table__v124;
        CData/*0:0*/ __VdlySet__copy_table__v124;
        CData/*5:0*/ __VdlyVal__copy_table__v125;
        CData/*0:0*/ __VdlySet__copy_table__v125;
        CData/*5:0*/ __VdlyVal__copy_table__v126;
        CData/*0:0*/ __VdlySet__copy_table__v126;
        CData/*5:0*/ __VdlyVal__copy_table__v127;
        CData/*0:0*/ __VdlySet__copy_table__v127;
        CData/*5:0*/ __VdlyVal__copy_table__v128;
        CData/*0:0*/ __VdlySet__copy_table__v128;
        CData/*5:0*/ __VdlyVal__copy_table__v129;
        CData/*0:0*/ __VdlySet__copy_table__v129;
        CData/*5:0*/ __VdlyVal__copy_table__v130;
        CData/*0:0*/ __VdlySet__copy_table__v130;
        CData/*5:0*/ __VdlyVal__copy_table__v131;
        CData/*0:0*/ __VdlySet__copy_table__v131;
        CData/*5:0*/ __VdlyVal__copy_table__v132;
        CData/*0:0*/ __VdlySet__copy_table__v132;
        CData/*5:0*/ __VdlyVal__copy_table__v133;
        CData/*0:0*/ __VdlySet__copy_table__v133;
        CData/*5:0*/ __VdlyVal__copy_table__v134;
        CData/*0:0*/ __VdlySet__copy_table__v134;
        CData/*5:0*/ __VdlyVal__copy_table__v135;
        CData/*0:0*/ __VdlySet__copy_table__v135;
        CData/*5:0*/ __VdlyVal__copy_table__v136;
        CData/*0:0*/ __VdlySet__copy_table__v136;
        CData/*5:0*/ __VdlyVal__copy_table__v137;
        CData/*0:0*/ __VdlySet__copy_table__v137;
        CData/*5:0*/ __VdlyVal__copy_table__v138;
        CData/*0:0*/ __VdlySet__copy_table__v138;
        CData/*5:0*/ __VdlyVal__copy_table__v139;
        CData/*0:0*/ __VdlySet__copy_table__v139;
        CData/*5:0*/ __VdlyVal__copy_table__v140;
        CData/*0:0*/ __VdlySet__copy_table__v140;
        CData/*5:0*/ __VdlyVal__copy_table__v141;
        CData/*0:0*/ __VdlySet__copy_table__v141;
        CData/*5:0*/ __VdlyVal__copy_table__v142;
        CData/*0:0*/ __VdlySet__copy_table__v142;
        CData/*5:0*/ __VdlyVal__copy_table__v143;
        CData/*0:0*/ __VdlySet__copy_table__v143;
        CData/*5:0*/ __VdlyVal__copy_table__v144;
        CData/*0:0*/ __VdlySet__copy_table__v144;
        CData/*5:0*/ __VdlyVal__copy_table__v145;
        CData/*0:0*/ __VdlySet__copy_table__v145;
        CData/*5:0*/ __VdlyVal__copy_table__v146;
        CData/*0:0*/ __VdlySet__copy_table__v146;
        CData/*5:0*/ __VdlyVal__copy_table__v147;
        CData/*0:0*/ __VdlySet__copy_table__v147;
        CData/*5:0*/ __VdlyVal__copy_table__v148;
        CData/*0:0*/ __VdlySet__copy_table__v148;
    };
    struct {
        CData/*5:0*/ __VdlyVal__copy_table__v149;
        CData/*0:0*/ __VdlySet__copy_table__v149;
        CData/*5:0*/ __VdlyVal__copy_table__v150;
        CData/*0:0*/ __VdlySet__copy_table__v150;
        CData/*5:0*/ __VdlyVal__copy_table__v151;
        CData/*0:0*/ __VdlySet__copy_table__v151;
        CData/*5:0*/ __VdlyVal__copy_table__v152;
        CData/*0:0*/ __VdlySet__copy_table__v152;
        CData/*5:0*/ __VdlyVal__copy_table__v153;
        CData/*0:0*/ __VdlySet__copy_table__v153;
        CData/*5:0*/ __VdlyVal__copy_table__v154;
        CData/*0:0*/ __VdlySet__copy_table__v154;
        CData/*5:0*/ __VdlyVal__copy_table__v155;
        CData/*0:0*/ __VdlySet__copy_table__v155;
        CData/*5:0*/ __VdlyVal__copy_table__v156;
        CData/*0:0*/ __VdlySet__copy_table__v156;
        CData/*5:0*/ __VdlyVal__copy_table__v157;
        CData/*0:0*/ __VdlySet__copy_table__v157;
        CData/*5:0*/ __VdlyVal__copy_table__v158;
        CData/*0:0*/ __VdlySet__copy_table__v158;
        CData/*5:0*/ __VdlyVal__copy_table__v159;
        CData/*0:0*/ __VdlySet__copy_table__v159;
        CData/*5:0*/ __VdlyVal__copy_table__v160;
        CData/*0:0*/ __VdlySet__copy_table__v160;
        CData/*5:0*/ __VdlyVal__copy_table__v161;
        CData/*0:0*/ __VdlySet__copy_table__v161;
        CData/*5:0*/ __VdlyVal__copy_table__v162;
        CData/*0:0*/ __VdlySet__copy_table__v162;
        CData/*5:0*/ __VdlyVal__copy_table__v163;
        CData/*0:0*/ __VdlySet__copy_table__v163;
        CData/*5:0*/ __VdlyVal__copy_table__v164;
        CData/*0:0*/ __VdlySet__copy_table__v164;
        CData/*5:0*/ __VdlyVal__copy_table__v165;
        CData/*0:0*/ __VdlySet__copy_table__v165;
        CData/*5:0*/ __VdlyVal__copy_table__v166;
        CData/*0:0*/ __VdlySet__copy_table__v166;
        CData/*5:0*/ __VdlyVal__copy_table__v167;
        CData/*0:0*/ __VdlySet__copy_table__v167;
        CData/*5:0*/ __VdlyVal__copy_table__v168;
        CData/*0:0*/ __VdlySet__copy_table__v168;
        CData/*5:0*/ __VdlyVal__copy_table__v169;
        CData/*0:0*/ __VdlySet__copy_table__v169;
        CData/*5:0*/ __VdlyVal__copy_table__v170;
        CData/*0:0*/ __VdlySet__copy_table__v170;
        CData/*5:0*/ __VdlyVal__copy_table__v171;
        CData/*0:0*/ __VdlySet__copy_table__v171;
        CData/*5:0*/ __VdlyVal__copy_table__v172;
        CData/*0:0*/ __VdlySet__copy_table__v172;
        CData/*5:0*/ __VdlyVal__copy_table__v173;
        CData/*0:0*/ __VdlySet__copy_table__v173;
        CData/*5:0*/ __VdlyVal__copy_table__v174;
        CData/*0:0*/ __VdlySet__copy_table__v174;
        CData/*5:0*/ __VdlyVal__copy_table__v175;
        CData/*0:0*/ __VdlySet__copy_table__v175;
        CData/*5:0*/ __VdlyVal__copy_table__v176;
        CData/*0:0*/ __VdlySet__copy_table__v176;
        CData/*5:0*/ __VdlyVal__copy_table__v177;
        CData/*0:0*/ __VdlySet__copy_table__v177;
        CData/*5:0*/ __VdlyVal__copy_table__v178;
        CData/*0:0*/ __VdlySet__copy_table__v178;
        CData/*5:0*/ __VdlyVal__copy_table__v179;
        CData/*0:0*/ __VdlySet__copy_table__v179;
        CData/*5:0*/ __VdlyVal__copy_table__v180;
        CData/*0:0*/ __VdlySet__copy_table__v180;
    };
    struct {
        CData/*5:0*/ __VdlyVal__copy_table__v181;
        CData/*0:0*/ __VdlySet__copy_table__v181;
        CData/*5:0*/ __VdlyVal__copy_table__v182;
        CData/*0:0*/ __VdlySet__copy_table__v182;
        CData/*5:0*/ __VdlyVal__copy_table__v183;
        CData/*0:0*/ __VdlySet__copy_table__v183;
        CData/*5:0*/ __VdlyVal__copy_table__v184;
        CData/*0:0*/ __VdlySet__copy_table__v184;
        CData/*5:0*/ __VdlyVal__copy_table__v185;
        CData/*0:0*/ __VdlySet__copy_table__v185;
        CData/*5:0*/ __VdlyVal__copy_table__v186;
        CData/*0:0*/ __VdlySet__copy_table__v186;
        CData/*5:0*/ __VdlyVal__copy_table__v187;
        CData/*0:0*/ __VdlySet__copy_table__v187;
        CData/*5:0*/ __VdlyVal__copy_table__v188;
        CData/*0:0*/ __VdlySet__copy_table__v188;
        CData/*5:0*/ __VdlyVal__copy_table__v189;
        CData/*0:0*/ __VdlySet__copy_table__v189;
        CData/*5:0*/ __VdlyVal__copy_table__v190;
        CData/*0:0*/ __VdlySet__copy_table__v190;
        CData/*5:0*/ __VdlyVal__copy_table__v191;
        CData/*0:0*/ __VdlySet__copy_table__v191;
        CData/*5:0*/ __VdlyVal__copy_table__v192;
        CData/*0:0*/ __VdlySet__copy_table__v192;
        CData/*5:0*/ __VdlyVal__copy_table__v193;
        CData/*0:0*/ __VdlySet__copy_table__v193;
        CData/*5:0*/ __VdlyVal__copy_table__v194;
        CData/*0:0*/ __VdlySet__copy_table__v194;
        CData/*5:0*/ __VdlyVal__copy_table__v195;
        CData/*0:0*/ __VdlySet__copy_table__v195;
        CData/*5:0*/ __VdlyVal__copy_table__v196;
        CData/*0:0*/ __VdlySet__copy_table__v196;
        CData/*5:0*/ __VdlyVal__copy_table__v197;
        CData/*0:0*/ __VdlySet__copy_table__v197;
        CData/*5:0*/ __VdlyVal__copy_table__v198;
        CData/*0:0*/ __VdlySet__copy_table__v198;
        CData/*5:0*/ __VdlyVal__copy_table__v199;
        CData/*0:0*/ __VdlySet__copy_table__v199;
        CData/*5:0*/ __VdlyVal__copy_table__v200;
        CData/*0:0*/ __VdlySet__copy_table__v200;
        CData/*5:0*/ __VdlyVal__copy_table__v201;
        CData/*0:0*/ __VdlySet__copy_table__v201;
        CData/*5:0*/ __VdlyVal__copy_table__v202;
        CData/*0:0*/ __VdlySet__copy_table__v202;
        CData/*5:0*/ __VdlyVal__copy_table__v203;
        CData/*0:0*/ __VdlySet__copy_table__v203;
        CData/*5:0*/ __VdlyVal__copy_table__v204;
        CData/*0:0*/ __VdlySet__copy_table__v204;
        CData/*5:0*/ __VdlyVal__copy_table__v205;
        CData/*0:0*/ __VdlySet__copy_table__v205;
        CData/*5:0*/ __VdlyVal__copy_table__v206;
        CData/*0:0*/ __VdlySet__copy_table__v206;
        CData/*5:0*/ __VdlyVal__copy_table__v207;
        CData/*0:0*/ __VdlySet__copy_table__v207;
        CData/*5:0*/ __VdlyVal__copy_table__v208;
        CData/*0:0*/ __VdlySet__copy_table__v208;
        CData/*5:0*/ __VdlyVal__copy_table__v209;
        CData/*0:0*/ __VdlySet__copy_table__v209;
        CData/*5:0*/ __VdlyVal__copy_table__v210;
        CData/*0:0*/ __VdlySet__copy_table__v210;
        CData/*5:0*/ __VdlyVal__copy_table__v211;
        CData/*0:0*/ __VdlySet__copy_table__v211;
        CData/*5:0*/ __VdlyVal__copy_table__v212;
        CData/*0:0*/ __VdlySet__copy_table__v212;
    };
    struct {
        CData/*5:0*/ __VdlyVal__copy_table__v213;
        CData/*0:0*/ __VdlySet__copy_table__v213;
        CData/*5:0*/ __VdlyVal__copy_table__v214;
        CData/*0:0*/ __VdlySet__copy_table__v214;
        CData/*5:0*/ __VdlyVal__copy_table__v215;
        CData/*0:0*/ __VdlySet__copy_table__v215;
        CData/*5:0*/ __VdlyVal__copy_table__v216;
        CData/*0:0*/ __VdlySet__copy_table__v216;
        CData/*5:0*/ __VdlyVal__copy_table__v217;
        CData/*0:0*/ __VdlySet__copy_table__v217;
        CData/*5:0*/ __VdlyVal__copy_table__v218;
        CData/*0:0*/ __VdlySet__copy_table__v218;
        CData/*5:0*/ __VdlyVal__copy_table__v219;
        CData/*0:0*/ __VdlySet__copy_table__v219;
        CData/*5:0*/ __VdlyVal__copy_table__v220;
        CData/*0:0*/ __VdlySet__copy_table__v220;
        CData/*5:0*/ __VdlyVal__copy_table__v221;
        CData/*0:0*/ __VdlySet__copy_table__v221;
        CData/*5:0*/ __VdlyVal__copy_table__v222;
        CData/*0:0*/ __VdlySet__copy_table__v222;
        CData/*5:0*/ __VdlyVal__copy_table__v223;
        CData/*0:0*/ __VdlySet__copy_table__v223;
        CData/*5:0*/ __VdlyVal__copy_table__v224;
        CData/*0:0*/ __VdlySet__copy_table__v224;
        CData/*5:0*/ __VdlyVal__copy_table__v225;
        CData/*0:0*/ __VdlySet__copy_table__v225;
        CData/*5:0*/ __VdlyVal__copy_table__v226;
        CData/*0:0*/ __VdlySet__copy_table__v226;
        CData/*5:0*/ __VdlyVal__copy_table__v227;
        CData/*0:0*/ __VdlySet__copy_table__v227;
        CData/*5:0*/ __VdlyVal__copy_table__v228;
        CData/*0:0*/ __VdlySet__copy_table__v228;
        CData/*5:0*/ __VdlyVal__copy_table__v229;
        CData/*0:0*/ __VdlySet__copy_table__v229;
        CData/*5:0*/ __VdlyVal__copy_table__v230;
        CData/*0:0*/ __VdlySet__copy_table__v230;
        CData/*5:0*/ __VdlyVal__copy_table__v231;
        CData/*0:0*/ __VdlySet__copy_table__v231;
        CData/*5:0*/ __VdlyVal__copy_table__v232;
        CData/*0:0*/ __VdlySet__copy_table__v232;
        CData/*5:0*/ __VdlyVal__copy_table__v233;
        CData/*0:0*/ __VdlySet__copy_table__v233;
        CData/*5:0*/ __VdlyVal__copy_table__v234;
        CData/*0:0*/ __VdlySet__copy_table__v234;
        CData/*5:0*/ __VdlyVal__copy_table__v235;
        CData/*0:0*/ __VdlySet__copy_table__v235;
        CData/*5:0*/ __VdlyVal__copy_table__v236;
        CData/*0:0*/ __VdlySet__copy_table__v236;
        CData/*5:0*/ __VdlyVal__copy_table__v237;
        CData/*0:0*/ __VdlySet__copy_table__v237;
        CData/*5:0*/ __VdlyVal__copy_table__v238;
        CData/*0:0*/ __VdlySet__copy_table__v238;
        CData/*5:0*/ __VdlyVal__copy_table__v239;
        CData/*0:0*/ __VdlySet__copy_table__v239;
        CData/*5:0*/ __VdlyVal__copy_table__v240;
        CData/*0:0*/ __VdlySet__copy_table__v240;
        CData/*5:0*/ __VdlyVal__copy_table__v241;
        CData/*0:0*/ __VdlySet__copy_table__v241;
        CData/*5:0*/ __VdlyVal__copy_table__v242;
        CData/*0:0*/ __VdlySet__copy_table__v242;
        CData/*5:0*/ __VdlyVal__copy_table__v243;
        CData/*0:0*/ __VdlySet__copy_table__v243;
        CData/*5:0*/ __VdlyVal__copy_table__v244;
        CData/*0:0*/ __VdlySet__copy_table__v244;
    };
    struct {
        CData/*5:0*/ __VdlyVal__copy_table__v245;
        CData/*0:0*/ __VdlySet__copy_table__v245;
        CData/*5:0*/ __VdlyVal__copy_table__v246;
        CData/*0:0*/ __VdlySet__copy_table__v246;
        CData/*5:0*/ __VdlyVal__copy_table__v247;
        CData/*0:0*/ __VdlySet__copy_table__v247;
        CData/*5:0*/ __VdlyVal__copy_table__v248;
        CData/*0:0*/ __VdlySet__copy_table__v248;
        CData/*5:0*/ __VdlyVal__copy_table__v249;
        CData/*0:0*/ __VdlySet__copy_table__v249;
        CData/*5:0*/ __VdlyVal__copy_table__v250;
        CData/*0:0*/ __VdlySet__copy_table__v250;
        CData/*5:0*/ __VdlyVal__copy_table__v251;
        CData/*0:0*/ __VdlySet__copy_table__v251;
        CData/*5:0*/ __VdlyVal__copy_table__v252;
        CData/*0:0*/ __VdlySet__copy_table__v252;
        CData/*5:0*/ __VdlyVal__copy_table__v253;
        CData/*0:0*/ __VdlySet__copy_table__v253;
        CData/*5:0*/ __VdlyVal__copy_table__v254;
        CData/*0:0*/ __VdlySet__copy_table__v254;
        CData/*5:0*/ __VdlyVal__copy_table__v255;
        CData/*0:0*/ __VdlySet__copy_table__v255;
        IData/*31:0*/ __PVT__i;
        VlUnpacked<CData/*5:0*/, 32> reg_map_table;
        VlUnpacked<VlUnpacked<CData/*5:0*/, 32>, 8> copy_table;
    };

    // INTERNAL VARIABLES
    Vfalco_top__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vfalco_top_register_map_table(Vfalco_top__Syms* symsp, const char* v__name);
    ~Vfalco_top_register_map_table();
    VL_UNCOPYABLE(Vfalco_top_register_map_table);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
