// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design implementation internals
// See Vfalco_top.h for the primary calling header

#include "Vfalco_top__pch.h"
#include "Vfalco_top_RNDS_stage.h"

VL_ATTR_COLD void Vfalco_top_RNDS_stage___ctor_var_reset(Vfalco_top_RNDS_stage* vlSelf) {
    (void)vlSelf;  // Prevent unused variable warning
    Vfalco_top__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+          Vfalco_top_RNDS_stage___ctor_var_reset\n"); );
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    vlSelf->__PVT__clk = VL_RAND_RESET_I(1);
    vlSelf->__PVT__rst = VL_RAND_RESET_I(1);
    vlSelf->__PVT__wait_csr = VL_RAND_RESET_I(1);
    vlSelf->__PVT__reg_rename_instr0_req = VL_RAND_RESET_I(1);
    vlSelf->__PVT__reg_rename_instr1_req = VL_RAND_RESET_I(1);
    vlSelf->__PVT__instr0_ready_alloc = VL_RAND_RESET_I(1);
    vlSelf->__PVT__instr1_ready_alloc = VL_RAND_RESET_I(1);
    vlSelf->__PVT__FL_instr0_check_top = VL_RAND_RESET_I(1);
    vlSelf->__PVT__FL_instr1_check_top = VL_RAND_RESET_I(1);
    vlSelf->__PVT__instr0_pre_req = VL_RAND_RESET_I(1);
    vlSelf->__PVT__instr1_pre_req = VL_RAND_RESET_I(1);
    vlSelf->__PVT__instr0_is_mem_op = VL_RAND_RESET_I(1);
    vlSelf->__PVT__instr1_is_mem_op = VL_RAND_RESET_I(1);
    vlSelf->__PVT__instr0_rd_new_prf = VL_RAND_RESET_I(6);
    vlSelf->__PVT__instr1_rd_new_prf = VL_RAND_RESET_I(6);
    vlSelf->__PVT__instr0_rd_prf = VL_RAND_RESET_I(6);
    vlSelf->__PVT__instr1_rd_prf = VL_RAND_RESET_I(6);
    vlSelf->__PVT__instr0_rd_stale_prf = VL_RAND_RESET_I(6);
    vlSelf->__PVT__instr1_rd_stale_prf = VL_RAND_RESET_I(6);
    vlSelf->__PVT__instr0_rs1_prf = VL_RAND_RESET_I(6);
    vlSelf->__PVT__instr1_rs1_prf = VL_RAND_RESET_I(6);
    vlSelf->__PVT__instr0_rs2_prf = VL_RAND_RESET_I(6);
    vlSelf->__PVT__instr1_rs2_prf = VL_RAND_RESET_I(6);
    vlSelf->__PVT__instr0_rs1_reg_ready = VL_RAND_RESET_I(1);
    vlSelf->__PVT__instr0_rs2_reg_ready = VL_RAND_RESET_I(1);
    vlSelf->__PVT__instr1_rs1_reg_ready = VL_RAND_RESET_I(1);
    vlSelf->__PVT__instr1_rs2_reg_ready = VL_RAND_RESET_I(1);
    vlSelf->__PVT__instr0_rs1_operand_ready = VL_RAND_RESET_I(1);
    vlSelf->__PVT__instr0_rs2_operand_ready = VL_RAND_RESET_I(1);
    vlSelf->__PVT__instr1_rs1_operand_ready = VL_RAND_RESET_I(1);
    vlSelf->__PVT__instr1_rs2_operand_ready = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(205, vlSelf->__PVT__pre_int_instr0_pack);
    VL_RAND_RESET_W(205, vlSelf->__PVT__pre_int_instr1_pack);
    VL_RAND_RESET_W(129, vlSelf->__PVT__pre_mem_instr0_pack);
    VL_RAND_RESET_W(129, vlSelf->__PVT__pre_mem_instr1_pack);
    vlSelf->__PVT__pre_int_pack0_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__pre_int_pack1_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__pre_mem_pack0_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__pre_mem_pack1_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__pre_int_instr0_rs1_ready = VL_RAND_RESET_I(1);
    vlSelf->__PVT__pre_int_instr0_rs2_ready = VL_RAND_RESET_I(1);
    vlSelf->__PVT__pre_int_instr1_rs1_ready = VL_RAND_RESET_I(1);
    vlSelf->__PVT__pre_int_instr1_rs2_ready = VL_RAND_RESET_I(1);
    vlSelf->__PVT__pre_mem_instr0_rs1_ready = VL_RAND_RESET_I(1);
    vlSelf->__PVT__pre_mem_instr0_rs2_ready = VL_RAND_RESET_I(1);
    vlSelf->__PVT__pre_mem_instr1_rs1_ready = VL_RAND_RESET_I(1);
    vlSelf->__PVT__pre_mem_instr1_rs2_ready = VL_RAND_RESET_I(1);
    vlSelf->store_counter = VL_RAND_RESET_I(7);
    vlSelf->store_next_counter = VL_RAND_RESET_I(7);
    vlSelf->__PVT__instr0_store_id = VL_RAND_RESET_I(7);
    vlSelf->__PVT__instr1_store_id = VL_RAND_RESET_I(7);
    vlSelf->instr0_predict_result = VL_RAND_RESET_I(1);
    vlSelf->instr1_predict_result = VL_RAND_RESET_I(1);
    vlSelf->instr0_store_set_id = VL_RAND_RESET_I(8);
    vlSelf->instr1_store_set_id = VL_RAND_RESET_I(8);
    vlSelf->__PVT__violation = VL_RAND_RESET_I(1);
    vlSelf->__PVT__recovery_insrt0_pc = VL_RAND_RESET_I(11);
    vlSelf->__PVT__recovery_insrt1_pc = VL_RAND_RESET_I(11);
    vlSelf->__PVT__device_violation = VL_RAND_RESET_I(1);
    vlSelf->__PVT__device_violation_pc = VL_RAND_RESET_I(11);
    vlSelf->__Vcellinp__freelist__instr1_rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vcellinp__freelist__instr0_rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vcellinp__freelist__recovery_target_rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vcellinp__freelist__recovery_no_copy = VL_RAND_RESET_I(1);
    vlSelf->__Vcellinp__freelist__recovery_rollback = VL_RAND_RESET_I(1);
    vlSelf->__Vcellinp__freelist__recovery_flush = VL_RAND_RESET_I(1);
    vlSelf->__Vcellinp__freelist__push_stale_rd1 = VL_RAND_RESET_I(6);
    vlSelf->__Vcellinp__freelist__push_stale_rd0 = VL_RAND_RESET_I(6);
    vlSelf->__Vcellinp__freelist__push_stale_rd1_valid = VL_RAND_RESET_I(1);
    vlSelf->__Vcellinp__freelist__push_stale_rd0_valid = VL_RAND_RESET_I(1);
    vlSelf->__Vcellinp__Map_Table__instr1_rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vcellinp__Map_Table__instr0_rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vcellinp__Map_Table__recovery_target_rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vcellinp__Map_Table__recovery_no_copy = VL_RAND_RESET_I(1);
    vlSelf->__Vcellinp__Map_Table__recovery_flush = VL_RAND_RESET_I(1);
    vlSelf->__Vcellinp__Map_Table__instr1_rs2 = VL_RAND_RESET_I(5);
    vlSelf->__Vcellinp__Map_Table__instr1_rs1 = VL_RAND_RESET_I(5);
    vlSelf->__Vcellinp__Map_Table__instr1_rd = VL_RAND_RESET_I(5);
    vlSelf->__Vcellinp__Map_Table__instr0_rs2 = VL_RAND_RESET_I(5);
    vlSelf->__Vcellinp__Map_Table__instr0_rs1 = VL_RAND_RESET_I(5);
    vlSelf->__Vcellinp__Map_Table__instr0_rd = VL_RAND_RESET_I(5);
    vlSelf->__Vcellinp__Map_Table__recovery_map_1_valid = VL_RAND_RESET_I(1);
    vlSelf->__Vcellinp__Map_Table__recovery_map_0_valid = VL_RAND_RESET_I(1);
    vlSelf->__Vcellinp__Map_Table__recovery_map_prf_1 = VL_RAND_RESET_I(6);
    vlSelf->__Vcellinp__Map_Table__recovery_map_arf_1 = VL_RAND_RESET_I(5);
    vlSelf->__Vcellinp__Map_Table__recovery_map_prf_0 = VL_RAND_RESET_I(6);
    vlSelf->__Vcellinp__Map_Table__recovery_map_arf_0 = VL_RAND_RESET_I(5);
    vlSelf->__Vcellinp__Map_Table__recovery_mode = VL_RAND_RESET_I(1);
    vlSelf->__Vcellinp__Busy_list__int_issue1_rd_prf = VL_RAND_RESET_I(6);
    vlSelf->__Vcellinp__Busy_list__int_issue1_rd_valid = VL_RAND_RESET_I(1);
    vlSelf->__Vcellinp__Busy_list__int_issue0_rd_prf = VL_RAND_RESET_I(6);
    vlSelf->__Vcellinp__Busy_list__int_issue0_rd_valid = VL_RAND_RESET_I(1);
    vlSelf->__Vcellinp__Busy_list__BCAST_load = VL_RAND_RESET_I(7);
    vlSelf->__Vcellinp__Busy_list__BCAST_muldiv = VL_RAND_RESET_I(7);
    vlSelf->__Vcellinp__Busy_list__BCAST_ALU_1 = VL_RAND_RESET_I(7);
    vlSelf->__Vcellinp__Busy_list__BCAST_alu_csr_bc = VL_RAND_RESET_I(7);
    vlSelf->__Vcellinp__LFST__issue_store_set_id = VL_RAND_RESET_I(8);
    vlSelf->__Vcellinp__LFST__issue_store_id = VL_RAND_RESET_I(7);
    vlSelf->__Vcellinp__LFST__issue_store = VL_RAND_RESET_I(1);
    vlSelf->__Vcellinp__LFST__instr1_store_set_id = VL_RAND_RESET_I(8);
    vlSelf->__Vcellinp__LFST__instr0_store_set_id = VL_RAND_RESET_I(8);
    vlSelf->__Vcellinp__LFST__instr1_is_store = VL_RAND_RESET_I(1);
    vlSelf->__Vcellinp__LFST__instr0_is_store = VL_RAND_RESET_I(1);
    vlSelf->__Vcellinp__LFST__instr1_pc = VL_RAND_RESET_I(11);
    vlSelf->__Vcellinp__LFST__instr0_pc = VL_RAND_RESET_I(11);
    vlSelf->__Vfunc_IsBrROBKill__0__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_IsBrROBKill__0__branch_recovery_flush = VL_RAND_RESET_I(15);
    vlSelf->__Vfunc_IsBrROBKill__0__rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_IsBrROBKill__1__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_IsBrROBKill__1__branch_recovery_flush = VL_RAND_RESET_I(15);
    vlSelf->__Vfunc_IsBrROBKill__1__rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_IsBrROBKill__2__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_IsBrROBKill__2__branch_recovery_flush = VL_RAND_RESET_I(15);
    vlSelf->__Vfunc_IsBrROBKill__2__rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_IsBrROBKill__3__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_IsBrROBKill__3__branch_recovery_flush = VL_RAND_RESET_I(15);
    vlSelf->__Vfunc_IsBrROBKill__3__rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_IsBrROBKill__4__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_IsBrROBKill__4__branch_recovery_flush = VL_RAND_RESET_I(15);
    vlSelf->__Vfunc_IsBrROBKill__4__rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_IsBrROBKill__5__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_IsBrROBKill__5__branch_recovery_flush = VL_RAND_RESET_I(15);
    vlSelf->__Vfunc_IsBrROBKill__5__rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_IsBrROBKill__6__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_IsBrROBKill__6__branch_recovery_flush = VL_RAND_RESET_I(15);
    vlSelf->__Vfunc_IsBrROBKill__6__rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vfunc_IsBrROBKill__7__Vfuncout = VL_RAND_RESET_I(1);
    vlSelf->__Vfunc_IsBrROBKill__7__branch_recovery_flush = VL_RAND_RESET_I(15);
    vlSelf->__Vfunc_IsBrROBKill__7__rob_tag = VL_RAND_RESET_I(6);
    vlSelf->__Vdly__wait_csr = VL_RAND_RESET_I(1);
    vlSelf->__Vdly__store_counter = VL_RAND_RESET_I(7);
}
