// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_c.h"
#include "Vsodor_top__Syms.h"


VL_ATTR_COLD void Vsodor_top___024root__trace_init_sub__TOP__0(Vsodor_top___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vsodor_top__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vsodor_top___024root__trace_init_sub__TOP__0\n"); );
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declBit(c+375,"clk", false,-1);
    tracep->declBit(c+376,"rst", false,-1);
}

VL_ATTR_COLD void Vsodor_top___024root__trace_init_sub__TOP__sodor_top__0(Vsodor_top___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vsodor_top__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vsodor_top___024root__trace_init_sub__TOP__sodor_top__0\n"); );
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declBit(c+54,"clk", false,-1);
    tracep->declBit(c+55,"rst", false,-1);
    tracep->declBus(c+62,"imem_req_addr", false,-1, 31,0);
    tracep->declBus(c+203,"imem_resp_data", false,-1, 31,0);
    tracep->declBus(c+328,"dmem_req_addr", false,-1, 31,0);
    tracep->declBus(c+329,"dmem_req_data", false,-1, 31,0);
    tracep->declBit(c+204,"dmem_resp_valid", false,-1);
    tracep->declBit(c+205,"dmem_req_valid", false,-1);
    tracep->declBit(c+206,"dmem_fcn_write_en", false,-1);
    tracep->declBus(c+207,"dmem_bit_typ", false,-1, 2,0);
    tracep->declBus(c+208,"dmem_resp_data", false,-1, 31,0);
    tracep->declBus(c+377,"ddpath_addr", false,-1, 4,0);
    tracep->declBit(c+197,"reset", false,-1);
}

VL_ATTR_COLD void Vsodor_top___024root__trace_init_sub__TOP__sodor_top__sodor_core__0(Vsodor_top___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vsodor_top__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vsodor_top___024root__trace_init_sub__TOP__sodor_top__sodor_core__0\n"); );
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declBit(c+56,"clock", false,-1);
    tracep->declBit(c+198,"reset", false,-1);
    tracep->declBus(c+63,"io_imem_req_bits_addr", false,-1, 31,0);
    tracep->declBus(c+209,"io_imem_resp_bits_data", false,-1, 31,0);
    tracep->declBit(c+210,"io_dmem_req_valid", false,-1);
    tracep->declBus(c+330,"io_dmem_req_bits_addr", false,-1, 31,0);
    tracep->declBus(c+331,"io_dmem_req_bits_data", false,-1, 31,0);
    tracep->declBit(c+211,"io_dmem_req_bits_fcn", false,-1);
    tracep->declBus(c+212,"io_dmem_req_bits_typ", false,-1, 2,0);
    tracep->declBit(c+213,"io_dmem_resp_valid", false,-1);
    tracep->declBus(c+214,"io_dmem_resp_bits_data", false,-1, 31,0);
    tracep->declBus(c+378,"io_ddpath_addr", false,-1, 4,0);
    tracep->declBus(c+379,"io_ddpath_wdata", false,-1, 31,0);
    tracep->declBus(c+323,"io_ddpath_rdata", false,-1, 31,0);
    tracep->declBit(c+215,"c_io_dmem_req_valid", false,-1);
    tracep->declBit(c+216,"c_io_dmem_req_bits_fcn", false,-1);
    tracep->declBus(c+217,"c_io_dmem_req_bits_typ", false,-1, 2,0);
    tracep->declBit(c+218,"c_io_dmem_resp_valid", false,-1);
    tracep->declBus(c+219,"c_io_dat_inst", false,-1, 31,0);
    tracep->declBit(c+332,"c_io_dat_br_eq", false,-1);
    tracep->declBit(c+333,"c_io_dat_br_lt", false,-1);
    tracep->declBit(c+334,"c_io_dat_br_ltu", false,-1);
    tracep->declBit(c+220,"c_io_dat_csr_eret", false,-1);
    tracep->declBit(c+221,"c_io_ctl_stall", false,-1);
    tracep->declBus(c+335,"c_io_ctl_pc_sel", false,-1, 2,0);
    tracep->declBus(c+222,"c_io_ctl_op1_sel", false,-1, 1,0);
    tracep->declBus(c+223,"c_io_ctl_op2_sel", false,-1, 1,0);
    tracep->declBus(c+224,"c_io_ctl_alu_fun", false,-1, 3,0);
    tracep->declBus(c+225,"c_io_ctl_wb_sel", false,-1, 1,0);
    tracep->declBit(c+226,"c_io_ctl_rf_wen", false,-1);
    tracep->declBus(c+227,"c_io_ctl_csr_cmd", false,-1, 2,0);
    tracep->declBit(c+228,"c_io_ctl_exception", false,-1);
    tracep->declBit(c+57,"d_clock", false,-1);
    tracep->declBit(c+199,"d_reset", false,-1);
    tracep->declBus(c+1,"d_io_ddpath_addr", false,-1, 4,0);
    tracep->declBus(c+2,"d_io_ddpath_wdata", false,-1, 31,0);
    tracep->declBus(c+324,"d_io_ddpath_rdata", false,-1, 31,0);
    tracep->declBus(c+64,"d_io_imem_req_bits_addr", false,-1, 31,0);
    tracep->declBus(c+229,"d_io_imem_resp_bits_data", false,-1, 31,0);
    tracep->declBus(c+336,"d_io_dmem_req_bits_addr", false,-1, 31,0);
    tracep->declBus(c+337,"d_io_dmem_req_bits_data", false,-1, 31,0);
    tracep->declBus(c+230,"d_io_dmem_resp_bits_data", false,-1, 31,0);
    tracep->declBit(c+231,"d_io_ctl_stall", false,-1);
    tracep->declBus(c+338,"d_io_ctl_pc_sel", false,-1, 2,0);
    tracep->declBus(c+232,"d_io_ctl_op1_sel", false,-1, 1,0);
    tracep->declBus(c+233,"d_io_ctl_op2_sel", false,-1, 1,0);
    tracep->declBus(c+234,"d_io_ctl_alu_fun", false,-1, 3,0);
    tracep->declBus(c+235,"d_io_ctl_wb_sel", false,-1, 1,0);
    tracep->declBit(c+236,"d_io_ctl_rf_wen", false,-1);
    tracep->declBus(c+237,"d_io_ctl_csr_cmd", false,-1, 2,0);
    tracep->declBit(c+238,"d_io_ctl_exception", false,-1);
    tracep->declBus(c+239,"d_io_dat_inst", false,-1, 31,0);
    tracep->declBit(c+339,"d_io_dat_br_eq", false,-1);
    tracep->declBit(c+340,"d_io_dat_br_lt", false,-1);
    tracep->declBit(c+341,"d_io_dat_br_ltu", false,-1);
    tracep->declBit(c+240,"d_io_dat_csr_eret", false,-1);
}

VL_ATTR_COLD void Vsodor_top___024root__trace_init_sub__TOP__sodor_top__memory_modelling_inst__0(Vsodor_top___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vsodor_top__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vsodor_top___024root__trace_init_sub__TOP__sodor_top__memory_modelling_inst__0\n"); );
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declBit(c+58,"clk", false,-1);
    tracep->declBus(c+325,"imem_addr", false,-1, 31,0);
    tracep->declBus(c+241,"imem_data", false,-1, 31,0);
    tracep->declBus(c+342,"dmem_req_addr", false,-1, 31,0);
    tracep->declBus(c+343,"dmem_req_data", false,-1, 31,0);
    tracep->declBit(c+242,"dmem_req_valid", false,-1);
    tracep->declBit(c+243,"dmem_req_write_en", false,-1);
    tracep->declBus(c+244,"dmem_req_bits_typ", false,-1, 2,0);
    tracep->declBit(c+245,"dmem_resp_valid", false,-1);
    tracep->declBus(c+246,"dmem_resp_data", false,-1, 31,0);
    tracep->declBus(c+247,"imem_read__Vstatic__mem_rdata", false,-1, 31,0);
    tracep->declBus(c+248,"dmem_read__Vstatic__mem_rdata", false,-1, 31,0);
    tracep->declBus(c+249,"dmem_write__Vstatic__m_addr", false,-1, 31,0);
}

VL_ATTR_COLD void Vsodor_top___024root__trace_init_sub__TOP__sodor_top__sodor_core__c__0(Vsodor_top___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vsodor_top__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vsodor_top___024root__trace_init_sub__TOP__sodor_top__sodor_core__c__0\n"); );
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declBit(c+250,"io_dmem_req_valid", false,-1);
    tracep->declBit(c+251,"io_dmem_req_bits_fcn", false,-1);
    tracep->declBus(c+252,"io_dmem_req_bits_typ", false,-1, 2,0);
    tracep->declBit(c+253,"io_dmem_resp_valid", false,-1);
    tracep->declBus(c+254,"io_dat_inst", false,-1, 31,0);
    tracep->declBit(c+344,"io_dat_br_eq", false,-1);
    tracep->declBit(c+345,"io_dat_br_lt", false,-1);
    tracep->declBit(c+346,"io_dat_br_ltu", false,-1);
    tracep->declBit(c+255,"io_dat_csr_eret", false,-1);
    tracep->declBit(c+256,"io_ctl_stall", false,-1);
    tracep->declBus(c+347,"io_ctl_pc_sel", false,-1, 2,0);
    tracep->declBus(c+257,"io_ctl_op1_sel", false,-1, 1,0);
    tracep->declBus(c+258,"io_ctl_op2_sel", false,-1, 1,0);
    tracep->declBus(c+259,"io_ctl_alu_fun", false,-1, 3,0);
    tracep->declBus(c+260,"io_ctl_wb_sel", false,-1, 1,0);
    tracep->declBit(c+261,"io_ctl_rf_wen", false,-1);
    tracep->declBus(c+262,"io_ctl_csr_cmd", false,-1, 2,0);
    tracep->declBit(c+263,"io_ctl_exception", false,-1);
    tracep->declBit(c+264,"cs_val_inst", false,-1);
    tracep->declBus(c+265,"cs_br_type", false,-1, 3,0);
    tracep->declBit(c+266,"cs0_2", false,-1);
    tracep->declBit(c+267,"cs0_3", false,-1);
    tracep->declBus(c+268,"cs0_6", false,-1, 2,0);
    tracep->declBit(c+269,"stall", false,-1);
    tracep->declBus(c+270,"rs1_addr", false,-1, 4,0);
    tracep->declBit(c+271,"csr_ren", false,-1);
    tracep->declBus(c+272,"csr_cmd", false,-1, 2,0);
}

VL_ATTR_COLD void Vsodor_top___024root__trace_init_sub__TOP__sodor_top__sodor_core__d__0(Vsodor_top___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vsodor_top__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vsodor_top___024root__trace_init_sub__TOP__sodor_top__sodor_core__d__0\n"); );
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declBit(c+59,"clock", false,-1);
    tracep->declBit(c+200,"reset", false,-1);
    tracep->declBus(c+3,"io_ddpath_addr", false,-1, 4,0);
    tracep->declBus(c+4,"io_ddpath_wdata", false,-1, 31,0);
    tracep->declBus(c+326,"io_ddpath_rdata", false,-1, 31,0);
    tracep->declBus(c+65,"io_imem_req_bits_addr", false,-1, 31,0);
    tracep->declBus(c+273,"io_imem_resp_bits_data", false,-1, 31,0);
    tracep->declBus(c+348,"io_dmem_req_bits_addr", false,-1, 31,0);
    tracep->declBus(c+349,"io_dmem_req_bits_data", false,-1, 31,0);
    tracep->declBus(c+274,"io_dmem_resp_bits_data", false,-1, 31,0);
    tracep->declBit(c+275,"io_ctl_stall", false,-1);
    tracep->declBus(c+350,"io_ctl_pc_sel", false,-1, 2,0);
    tracep->declBus(c+276,"io_ctl_op1_sel", false,-1, 1,0);
    tracep->declBus(c+277,"io_ctl_op2_sel", false,-1, 1,0);
    tracep->declBus(c+278,"io_ctl_alu_fun", false,-1, 3,0);
    tracep->declBus(c+279,"io_ctl_wb_sel", false,-1, 1,0);
    tracep->declBit(c+280,"io_ctl_rf_wen", false,-1);
    tracep->declBus(c+281,"io_ctl_csr_cmd", false,-1, 2,0);
    tracep->declBit(c+282,"io_ctl_exception", false,-1);
    tracep->declBus(c+283,"io_dat_inst", false,-1, 31,0);
    tracep->declBit(c+351,"io_dat_br_eq", false,-1);
    tracep->declBit(c+352,"io_dat_br_lt", false,-1);
    tracep->declBit(c+353,"io_dat_br_ltu", false,-1);
    tracep->declBit(c+284,"io_dat_csr_eret", false,-1);
    for (int i = 0; i < 32; ++i) {
        tracep->declBus(c+66+i*1,"regfile", true,(i+0), 31,0);
    }
    tracep->declBus(c+327,"regfile_MPORT_1_data", false,-1, 31,0);
    tracep->declBus(c+5,"regfile_MPORT_1_addr", false,-1, 4,0);
    tracep->declBus(c+354,"regfile_MPORT_3_data", false,-1, 31,0);
    tracep->declBus(c+285,"regfile_MPORT_3_addr", false,-1, 4,0);
    tracep->declBus(c+355,"regfile_MPORT_4_data", false,-1, 31,0);
    tracep->declBus(c+286,"regfile_MPORT_4_addr", false,-1, 4,0);
    tracep->declBus(c+372,"regfile_MPORT_data", false,-1, 31,0);
    tracep->declBus(c+287,"regfile_MPORT_addr", false,-1, 4,0);
    tracep->declBit(c+6,"regfile_MPORT_mask", false,-1);
    tracep->declBit(c+288,"regfile_MPORT_en", false,-1);
    tracep->declBus(c+7,"regfile_MPORT_2_data", false,-1, 31,0);
    tracep->declBus(c+8,"regfile_MPORT_2_addr", false,-1, 4,0);
    tracep->declBit(c+9,"regfile_MPORT_2_mask", false,-1);
    tracep->declBit(c+10,"regfile_MPORT_2_en", false,-1);
    tracep->declBit(c+60,"csr_clock", false,-1);
    tracep->declBit(c+201,"csr_reset", false,-1);
    tracep->declBus(c+289,"csr_io_rw_cmd", false,-1, 2,0);
    tracep->declBus(c+367,"csr_io_rw_rdata", false,-1, 31,0);
    tracep->declBus(c+356,"csr_io_rw_wdata", false,-1, 31,0);
    tracep->declBit(c+290,"csr_io_eret", false,-1);
    tracep->declBus(c+291,"csr_io_decode_csr", false,-1, 11,0);
    tracep->declBit(c+11,"csr_io_status_debug", false,-1);
    tracep->declBus(c+12,"csr_io_status_prv", false,-1, 1,0);
    tracep->declBit(c+13,"csr_io_status_sd", false,-1);
    tracep->declBus(c+14,"csr_io_status_zero1", false,-1, 7,0);
    tracep->declBit(c+15,"csr_io_status_tsr", false,-1);
    tracep->declBit(c+16,"csr_io_status_tw", false,-1);
    tracep->declBit(c+17,"csr_io_status_tvm", false,-1);
    tracep->declBit(c+18,"csr_io_status_mxr", false,-1);
    tracep->declBit(c+19,"csr_io_status_sum", false,-1);
    tracep->declBit(c+20,"csr_io_status_mprv", false,-1);
    tracep->declBus(c+21,"csr_io_status_xs", false,-1, 1,0);
    tracep->declBus(c+22,"csr_io_status_fs", false,-1, 1,0);
    tracep->declBus(c+23,"csr_io_status_mpp", false,-1, 1,0);
    tracep->declBus(c+24,"csr_io_status_hpp", false,-1, 1,0);
    tracep->declBit(c+25,"csr_io_status_spp", false,-1);
    tracep->declBit(c+102,"csr_io_status_mpie", false,-1);
    tracep->declBit(c+26,"csr_io_status_hpie", false,-1);
    tracep->declBit(c+27,"csr_io_status_spie", false,-1);
    tracep->declBit(c+28,"csr_io_status_upie", false,-1);
    tracep->declBit(c+103,"csr_io_status_mie", false,-1);
    tracep->declBit(c+29,"csr_io_status_hie", false,-1);
    tracep->declBit(c+30,"csr_io_status_sie", false,-1);
    tracep->declBit(c+31,"csr_io_status_uie", false,-1);
    tracep->declBus(c+368,"csr_io_evec", false,-1, 31,0);
    tracep->declBit(c+292,"csr_io_exception", false,-1);
    tracep->declBit(c+293,"csr_io_retire", false,-1);
    tracep->declBus(c+98,"csr_io_pc", false,-1, 31,0);
    tracep->declBus(c+104,"csr_io_time", false,-1, 31,0);
    tracep->declBus(c+369,"exception_target", false,-1, 31,0);
    tracep->declBus(c+99,"pc_reg", false,-1, 31,0);
    tracep->declBus(c+100,"pc_plus4", false,-1, 31,0);
    tracep->declBus(c+294,"rs1_addr", false,-1, 4,0);
    tracep->declBus(c+357,"rs1_data", false,-1, 31,0);
    tracep->declBus(c+295,"imm_i", false,-1, 11,0);
    tracep->declBus(c+296,"imm_i_sext", false,-1, 31,0);
    tracep->declBus(c+358,"jump_reg_target", false,-1, 31,0);
    tracep->declBus(c+297,"imm_j", false,-1, 19,0);
    tracep->declBus(c+298,"imm_j_sext", false,-1, 31,0);
    tracep->declBus(c+359,"jmp_target", false,-1, 31,0);
    tracep->declBus(c+299,"imm_b", false,-1, 11,0);
    tracep->declBus(c+300,"imm_b_sext", false,-1, 31,0);
    tracep->declBus(c+360,"br_target", false,-1, 31,0);
    tracep->declBus(c+301,"rs2_addr", false,-1, 4,0);
    tracep->declBus(c+302,"wb_addr", false,-1, 4,0);
    tracep->declBit(c+303,"wb_wen", false,-1);
    tracep->declBus(c+304,"imm_u", false,-1, 19,0);
    tracep->declBus(c+305,"imm_u_sext", false,-1, 31,0);
    tracep->declBus(c+306,"imm_z", false,-1, 31,0);
    tracep->declBus(c+361,"alu_op1", false,-1, 31,0);
    tracep->declBus(c+362,"rs2_data", false,-1, 31,0);
    tracep->declBus(c+307,"imm_s", false,-1, 11,0);
    tracep->declBus(c+308,"imm_s_sext", false,-1, 31,0);
    tracep->declBus(c+363,"alu_op2", false,-1, 31,0);
    tracep->declBus(c+364,"alu_shamt", false,-1, 4,0);
    tracep->declBus(c+365,"alu_out", false,-1, 31,0);
    tracep->declBus(c+373,"wb_data", false,-1, 31,0);
}

VL_ATTR_COLD void Vsodor_top___024root__trace_init_sub__TOP__sodor_top__sodor_core__d__csr__0(Vsodor_top___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vsodor_top__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vsodor_top___024root__trace_init_sub__TOP__sodor_top__sodor_core__d__csr__0\n"); );
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declBit(c+61,"clock", false,-1);
    tracep->declBit(c+202,"reset", false,-1);
    tracep->declBus(c+309,"io_rw_cmd", false,-1, 2,0);
    tracep->declBus(c+370,"io_rw_rdata", false,-1, 31,0);
    tracep->declBus(c+366,"io_rw_wdata", false,-1, 31,0);
    tracep->declBit(c+310,"io_eret", false,-1);
    tracep->declBus(c+311,"io_decode_csr", false,-1, 11,0);
    tracep->declBit(c+32,"io_status_debug", false,-1);
    tracep->declBus(c+33,"io_status_prv", false,-1, 1,0);
    tracep->declBit(c+34,"io_status_sd", false,-1);
    tracep->declBus(c+35,"io_status_zero1", false,-1, 7,0);
    tracep->declBit(c+36,"io_status_tsr", false,-1);
    tracep->declBit(c+37,"io_status_tw", false,-1);
    tracep->declBit(c+38,"io_status_tvm", false,-1);
    tracep->declBit(c+39,"io_status_mxr", false,-1);
    tracep->declBit(c+40,"io_status_sum", false,-1);
    tracep->declBit(c+41,"io_status_mprv", false,-1);
    tracep->declBus(c+42,"io_status_xs", false,-1, 1,0);
    tracep->declBus(c+43,"io_status_fs", false,-1, 1,0);
    tracep->declBus(c+44,"io_status_mpp", false,-1, 1,0);
    tracep->declBus(c+45,"io_status_hpp", false,-1, 1,0);
    tracep->declBit(c+46,"io_status_spp", false,-1);
    tracep->declBit(c+105,"io_status_mpie", false,-1);
    tracep->declBit(c+47,"io_status_hpie", false,-1);
    tracep->declBit(c+48,"io_status_spie", false,-1);
    tracep->declBit(c+49,"io_status_upie", false,-1);
    tracep->declBit(c+106,"io_status_mie", false,-1);
    tracep->declBit(c+50,"io_status_hie", false,-1);
    tracep->declBit(c+51,"io_status_sie", false,-1);
    tracep->declBit(c+52,"io_status_uie", false,-1);
    tracep->declBus(c+371,"io_evec", false,-1, 31,0);
    tracep->declBit(c+312,"io_exception", false,-1);
    tracep->declBit(c+313,"io_retire", false,-1);
    tracep->declBus(c+101,"io_pc", false,-1, 31,0);
    tracep->declBus(c+107,"io_time", false,-1, 31,0);
    tracep->declBit(c+108,"reg_mstatus_mpie", false,-1);
    tracep->declBit(c+109,"reg_mstatus_mie", false,-1);
    tracep->declBus(c+110,"reg_mepc", false,-1, 31,0);
    tracep->declBus(c+111,"reg_mcause", false,-1, 31,0);
    tracep->declBus(c+112,"reg_mtval", false,-1, 31,0);
    tracep->declBus(c+113,"reg_mscratch", false,-1, 31,0);
    tracep->declBus(c+114,"reg_medeleg", false,-1, 31,0);
    tracep->declBit(c+115,"reg_mip_mtip", false,-1);
    tracep->declBit(c+116,"reg_mip_msip", false,-1);
    tracep->declBit(c+117,"reg_mie_mtip", false,-1);
    tracep->declBit(c+118,"reg_mie_msip", false,-1);
    tracep->declBus(c+119,"REG", false,-1, 5,0);
    tracep->declQuad(c+120,"REG_1", false,-1, 57,0);
    tracep->declBus(c+122,"REG_2", false,-1, 5,0);
    tracep->declQuad(c+123,"REG_3", false,-1, 57,0);
    tracep->declQuad(c+125,"REG_4", false,-1, 39,0);
    tracep->declQuad(c+127,"REG_5", false,-1, 39,0);
    tracep->declQuad(c+129,"REG_6", false,-1, 39,0);
    tracep->declQuad(c+131,"REG_7", false,-1, 39,0);
    tracep->declQuad(c+133,"REG_8", false,-1, 39,0);
    tracep->declQuad(c+135,"REG_9", false,-1, 39,0);
    tracep->declQuad(c+137,"REG_10", false,-1, 39,0);
    tracep->declQuad(c+139,"REG_11", false,-1, 39,0);
    tracep->declQuad(c+141,"REG_12", false,-1, 39,0);
    tracep->declQuad(c+143,"REG_13", false,-1, 39,0);
    tracep->declQuad(c+145,"REG_14", false,-1, 39,0);
    tracep->declQuad(c+147,"REG_15", false,-1, 39,0);
    tracep->declQuad(c+149,"REG_16", false,-1, 39,0);
    tracep->declQuad(c+151,"REG_17", false,-1, 39,0);
    tracep->declQuad(c+153,"REG_18", false,-1, 39,0);
    tracep->declQuad(c+155,"REG_19", false,-1, 39,0);
    tracep->declQuad(c+157,"REG_20", false,-1, 39,0);
    tracep->declQuad(c+159,"REG_21", false,-1, 39,0);
    tracep->declQuad(c+161,"REG_22", false,-1, 39,0);
    tracep->declQuad(c+163,"REG_23", false,-1, 39,0);
    tracep->declQuad(c+165,"REG_24", false,-1, 39,0);
    tracep->declQuad(c+167,"REG_25", false,-1, 39,0);
    tracep->declQuad(c+169,"REG_26", false,-1, 39,0);
    tracep->declQuad(c+171,"REG_27", false,-1, 39,0);
    tracep->declQuad(c+173,"REG_28", false,-1, 39,0);
    tracep->declQuad(c+175,"REG_29", false,-1, 39,0);
    tracep->declQuad(c+177,"REG_30", false,-1, 39,0);
    tracep->declQuad(c+179,"REG_31", false,-1, 39,0);
    tracep->declQuad(c+181,"REG_32", false,-1, 39,0);
    tracep->declQuad(c+183,"REG_33", false,-1, 39,0);
    tracep->declQuad(c+185,"REG_34", false,-1, 39,0);
    tracep->declQuad(c+187,"REG_35", false,-1, 39,0);
    tracep->declBus(c+189,"reg_dpc", false,-1, 31,0);
    tracep->declBus(c+190,"reg_dscratch", false,-1, 31,0);
    tracep->declBit(c+191,"reg_dcsr_ebreakm", false,-1);
    tracep->declBit(c+192,"reg_dcsr_step", false,-1);
    tracep->declBit(c+314,"system_insn", false,-1);
    tracep->declBit(c+315,"cpu_ren", false,-1);
    tracep->declBus(c+193,"lo_lo", false,-1, 4,0);
    tracep->declBus(c+194,"lo", false,-1, 12,0);
    tracep->declBus(c+53,"hi_lo", false,-1, 7,0);
    tracep->declQuad(c+195,"read_mstatus", false,-1, 34,0);
    tracep->declBit(c+316,"read_only", false,-1);
    tracep->declBit(c+317,"cpu_wen", false,-1);
    tracep->declBit(c+318,"wen", false,-1);
    tracep->declBus(c+374,"wdata", false,-1, 31,0);
    tracep->declBus(c+319,"opcode", false,-1, 7,0);
    tracep->declBit(c+320,"insn_call", false,-1);
    tracep->declBit(c+321,"insn_break", false,-1);
    tracep->declBit(c+322,"insn_ret", false,-1);
}

VL_ATTR_COLD void Vsodor_top___024root__trace_init_top(Vsodor_top___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vsodor_top__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vsodor_top___024root__trace_init_top\n"); );
    // Body
    Vsodor_top___024root__trace_init_sub__TOP__0(vlSelf, tracep);
    tracep->pushNamePrefix("sodor_top ");
    Vsodor_top___024root__trace_init_sub__TOP__sodor_top__0(vlSelf, tracep);
    tracep->pushNamePrefix("memory_modelling_inst ");
    Vsodor_top___024root__trace_init_sub__TOP__sodor_top__memory_modelling_inst__0(vlSelf, tracep);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("sodor_core ");
    Vsodor_top___024root__trace_init_sub__TOP__sodor_top__sodor_core__0(vlSelf, tracep);
    tracep->pushNamePrefix("c ");
    Vsodor_top___024root__trace_init_sub__TOP__sodor_top__sodor_core__c__0(vlSelf, tracep);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("d ");
    Vsodor_top___024root__trace_init_sub__TOP__sodor_top__sodor_core__d__0(vlSelf, tracep);
    tracep->pushNamePrefix("csr ");
    Vsodor_top___024root__trace_init_sub__TOP__sodor_top__sodor_core__d__csr__0(vlSelf, tracep);
    tracep->popNamePrefix(4);
}

VL_ATTR_COLD void Vsodor_top___024root__trace_full_top_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vsodor_top___024root__trace_chg_top_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vsodor_top___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/);

VL_ATTR_COLD void Vsodor_top___024root__trace_register(Vsodor_top___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vsodor_top__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vsodor_top___024root__trace_register\n"); );
    // Body
    tracep->addFullCb(&Vsodor_top___024root__trace_full_top_0, vlSelf);
    tracep->addChgCb(&Vsodor_top___024root__trace_chg_top_0, vlSelf);
    tracep->addCleanupCb(&Vsodor_top___024root__trace_cleanup, vlSelf);
}

VL_ATTR_COLD void Vsodor_top___024root__trace_full_sub_0(Vsodor_top___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void Vsodor_top___024root__trace_full_top_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vsodor_top___024root__trace_full_top_0\n"); );
    // Init
    Vsodor_top___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vsodor_top___024root*>(voidSelf);
    Vsodor_top__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    Vsodor_top___024root__trace_full_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vsodor_top___024root__trace_full_sub_0(Vsodor_top___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    if (false && vlSelf) {}  // Prevent unused
    Vsodor_top__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vsodor_top___024root__trace_full_sub_0\n"); );
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    // Body
    bufp->fullCData(oldp+1,(vlSymsp->TOP__sodor_top__sodor_core.__PVT__d_io_ddpath_addr),5);
    bufp->fullIData(oldp+2,(vlSymsp->TOP__sodor_top__sodor_core.__PVT__d_io_ddpath_wdata),32);
    bufp->fullCData(oldp+3,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__io_ddpath_addr),5);
    bufp->fullIData(oldp+4,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__io_ddpath_wdata),32);
    bufp->fullCData(oldp+5,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__regfile_MPORT_1_addr),5);
    bufp->fullBit(oldp+6,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__regfile_MPORT_mask));
    bufp->fullIData(oldp+7,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__regfile_MPORT_2_data),32);
    bufp->fullCData(oldp+8,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__regfile_MPORT_2_addr),5);
    bufp->fullBit(oldp+9,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__regfile_MPORT_2_mask));
    bufp->fullBit(oldp+10,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__regfile_MPORT_2_en));
    bufp->fullBit(oldp+11,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__csr_io_status_debug));
    bufp->fullCData(oldp+12,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__csr_io_status_prv),2);
    bufp->fullBit(oldp+13,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__csr_io_status_sd));
    bufp->fullCData(oldp+14,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__csr_io_status_zero1),8);
    bufp->fullBit(oldp+15,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__csr_io_status_tsr));
    bufp->fullBit(oldp+16,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__csr_io_status_tw));
    bufp->fullBit(oldp+17,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__csr_io_status_tvm));
    bufp->fullBit(oldp+18,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__csr_io_status_mxr));
    bufp->fullBit(oldp+19,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__csr_io_status_sum));
    bufp->fullBit(oldp+20,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__csr_io_status_mprv));
    bufp->fullCData(oldp+21,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__csr_io_status_xs),2);
    bufp->fullCData(oldp+22,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__csr_io_status_fs),2);
    bufp->fullCData(oldp+23,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__csr_io_status_mpp),2);
    bufp->fullCData(oldp+24,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__csr_io_status_hpp),2);
    bufp->fullBit(oldp+25,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__csr_io_status_spp));
    bufp->fullBit(oldp+26,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__csr_io_status_hpie));
    bufp->fullBit(oldp+27,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__csr_io_status_spie));
    bufp->fullBit(oldp+28,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__csr_io_status_upie));
    bufp->fullBit(oldp+29,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__csr_io_status_hie));
    bufp->fullBit(oldp+30,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__csr_io_status_sie));
    bufp->fullBit(oldp+31,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__csr_io_status_uie));
    bufp->fullBit(oldp+32,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__io_status_debug));
    bufp->fullCData(oldp+33,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__io_status_prv),2);
    bufp->fullBit(oldp+34,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__io_status_sd));
    bufp->fullCData(oldp+35,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__io_status_zero1),8);
    bufp->fullBit(oldp+36,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__io_status_tsr));
    bufp->fullBit(oldp+37,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__io_status_tw));
    bufp->fullBit(oldp+38,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__io_status_tvm));
    bufp->fullBit(oldp+39,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__io_status_mxr));
    bufp->fullBit(oldp+40,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__io_status_sum));
    bufp->fullBit(oldp+41,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__io_status_mprv));
    bufp->fullCData(oldp+42,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__io_status_xs),2);
    bufp->fullCData(oldp+43,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__io_status_fs),2);
    bufp->fullCData(oldp+44,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__io_status_mpp),2);
    bufp->fullCData(oldp+45,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__io_status_hpp),2);
    bufp->fullBit(oldp+46,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__io_status_spp));
    bufp->fullBit(oldp+47,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__io_status_hpie));
    bufp->fullBit(oldp+48,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__io_status_spie));
    bufp->fullBit(oldp+49,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__io_status_upie));
    bufp->fullBit(oldp+50,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__io_status_hie));
    bufp->fullBit(oldp+51,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__io_status_sie));
    bufp->fullBit(oldp+52,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__io_status_uie));
    bufp->fullCData(oldp+53,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__hi_lo),8);
    bufp->fullBit(oldp+54,(vlSymsp->TOP__sodor_top.clk));
    bufp->fullBit(oldp+55,(vlSymsp->TOP__sodor_top.rst));
    bufp->fullBit(oldp+56,(vlSymsp->TOP__sodor_top__sodor_core.__PVT__clock));
    bufp->fullBit(oldp+57,(vlSymsp->TOP__sodor_top__sodor_core.__PVT__d_clock));
    bufp->fullBit(oldp+58,(vlSymsp->TOP__sodor_top__memory_modelling_inst.__PVT__clk));
    bufp->fullBit(oldp+59,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__clock));
    bufp->fullBit(oldp+60,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__csr_clock));
    bufp->fullBit(oldp+61,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__clock));
    bufp->fullIData(oldp+62,(vlSymsp->TOP__sodor_top.__PVT__imem_req_addr),32);
    bufp->fullIData(oldp+63,(vlSymsp->TOP__sodor_top__sodor_core.__PVT__io_imem_req_bits_addr),32);
    bufp->fullIData(oldp+64,(vlSymsp->TOP__sodor_top__sodor_core.__PVT__d_io_imem_req_bits_addr),32);
    bufp->fullIData(oldp+65,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__io_imem_req_bits_addr),32);
    bufp->fullIData(oldp+66,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__regfile[0]),32);
    bufp->fullIData(oldp+67,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__regfile[1]),32);
    bufp->fullIData(oldp+68,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__regfile[2]),32);
    bufp->fullIData(oldp+69,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__regfile[3]),32);
    bufp->fullIData(oldp+70,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__regfile[4]),32);
    bufp->fullIData(oldp+71,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__regfile[5]),32);
    bufp->fullIData(oldp+72,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__regfile[6]),32);
    bufp->fullIData(oldp+73,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__regfile[7]),32);
    bufp->fullIData(oldp+74,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__regfile[8]),32);
    bufp->fullIData(oldp+75,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__regfile[9]),32);
    bufp->fullIData(oldp+76,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__regfile[10]),32);
    bufp->fullIData(oldp+77,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__regfile[11]),32);
    bufp->fullIData(oldp+78,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__regfile[12]),32);
    bufp->fullIData(oldp+79,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__regfile[13]),32);
    bufp->fullIData(oldp+80,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__regfile[14]),32);
    bufp->fullIData(oldp+81,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__regfile[15]),32);
    bufp->fullIData(oldp+82,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__regfile[16]),32);
    bufp->fullIData(oldp+83,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__regfile[17]),32);
    bufp->fullIData(oldp+84,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__regfile[18]),32);
    bufp->fullIData(oldp+85,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__regfile[19]),32);
    bufp->fullIData(oldp+86,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__regfile[20]),32);
    bufp->fullIData(oldp+87,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__regfile[21]),32);
    bufp->fullIData(oldp+88,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__regfile[22]),32);
    bufp->fullIData(oldp+89,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__regfile[23]),32);
    bufp->fullIData(oldp+90,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__regfile[24]),32);
    bufp->fullIData(oldp+91,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__regfile[25]),32);
    bufp->fullIData(oldp+92,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__regfile[26]),32);
    bufp->fullIData(oldp+93,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__regfile[27]),32);
    bufp->fullIData(oldp+94,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__regfile[28]),32);
    bufp->fullIData(oldp+95,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__regfile[29]),32);
    bufp->fullIData(oldp+96,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__regfile[30]),32);
    bufp->fullIData(oldp+97,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__regfile[31]),32);
    bufp->fullIData(oldp+98,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__csr_io_pc),32);
    bufp->fullIData(oldp+99,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__pc_reg),32);
    bufp->fullIData(oldp+100,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__pc_plus4),32);
    bufp->fullIData(oldp+101,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__io_pc),32);
    bufp->fullBit(oldp+102,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__csr_io_status_mpie));
    bufp->fullBit(oldp+103,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__csr_io_status_mie));
    bufp->fullIData(oldp+104,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__csr_io_time),32);
    bufp->fullBit(oldp+105,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__io_status_mpie));
    bufp->fullBit(oldp+106,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__io_status_mie));
    bufp->fullIData(oldp+107,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__io_time),32);
    bufp->fullBit(oldp+108,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__reg_mstatus_mpie));
    bufp->fullBit(oldp+109,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__reg_mstatus_mie));
    bufp->fullIData(oldp+110,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__reg_mepc),32);
    bufp->fullIData(oldp+111,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__reg_mcause),32);
    bufp->fullIData(oldp+112,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__reg_mtval),32);
    bufp->fullIData(oldp+113,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__reg_mscratch),32);
    bufp->fullIData(oldp+114,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__reg_medeleg),32);
    bufp->fullBit(oldp+115,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__reg_mip_mtip));
    bufp->fullBit(oldp+116,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__reg_mip_msip));
    bufp->fullBit(oldp+117,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__reg_mie_mtip));
    bufp->fullBit(oldp+118,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__reg_mie_msip));
    bufp->fullCData(oldp+119,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__REG),6);
    bufp->fullQData(oldp+120,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__REG_1),58);
    bufp->fullCData(oldp+122,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__REG_2),6);
    bufp->fullQData(oldp+123,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__REG_3),58);
    bufp->fullQData(oldp+125,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__REG_4),40);
    bufp->fullQData(oldp+127,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__REG_5),40);
    bufp->fullQData(oldp+129,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__REG_6),40);
    bufp->fullQData(oldp+131,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__REG_7),40);
    bufp->fullQData(oldp+133,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__REG_8),40);
    bufp->fullQData(oldp+135,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__REG_9),40);
    bufp->fullQData(oldp+137,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__REG_10),40);
    bufp->fullQData(oldp+139,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__REG_11),40);
    bufp->fullQData(oldp+141,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__REG_12),40);
    bufp->fullQData(oldp+143,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__REG_13),40);
    bufp->fullQData(oldp+145,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__REG_14),40);
    bufp->fullQData(oldp+147,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__REG_15),40);
    bufp->fullQData(oldp+149,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__REG_16),40);
    bufp->fullQData(oldp+151,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__REG_17),40);
    bufp->fullQData(oldp+153,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__REG_18),40);
    bufp->fullQData(oldp+155,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__REG_19),40);
    bufp->fullQData(oldp+157,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__REG_20),40);
    bufp->fullQData(oldp+159,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__REG_21),40);
    bufp->fullQData(oldp+161,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__REG_22),40);
    bufp->fullQData(oldp+163,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__REG_23),40);
    bufp->fullQData(oldp+165,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__REG_24),40);
    bufp->fullQData(oldp+167,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__REG_25),40);
    bufp->fullQData(oldp+169,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__REG_26),40);
    bufp->fullQData(oldp+171,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__REG_27),40);
    bufp->fullQData(oldp+173,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__REG_28),40);
    bufp->fullQData(oldp+175,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__REG_29),40);
    bufp->fullQData(oldp+177,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__REG_30),40);
    bufp->fullQData(oldp+179,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__REG_31),40);
    bufp->fullQData(oldp+181,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__REG_32),40);
    bufp->fullQData(oldp+183,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__REG_33),40);
    bufp->fullQData(oldp+185,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__REG_34),40);
    bufp->fullQData(oldp+187,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__REG_35),40);
    bufp->fullIData(oldp+189,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__reg_dpc),32);
    bufp->fullIData(oldp+190,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__reg_dscratch),32);
    bufp->fullBit(oldp+191,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__reg_dcsr_ebreakm));
    bufp->fullBit(oldp+192,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__reg_dcsr_step));
    bufp->fullCData(oldp+193,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__lo_lo),5);
    bufp->fullSData(oldp+194,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__lo),13);
    bufp->fullQData(oldp+195,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__read_mstatus),35);
    bufp->fullBit(oldp+197,(vlSymsp->TOP__sodor_top.__PVT__reset));
    bufp->fullBit(oldp+198,(vlSymsp->TOP__sodor_top__sodor_core.__PVT__reset));
    bufp->fullBit(oldp+199,(vlSymsp->TOP__sodor_top__sodor_core.__PVT__d_reset));
    bufp->fullBit(oldp+200,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__reset));
    bufp->fullBit(oldp+201,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__csr_reset));
    bufp->fullBit(oldp+202,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__reset));
    bufp->fullIData(oldp+203,(vlSymsp->TOP__sodor_top.__PVT__imem_resp_data),32);
    bufp->fullBit(oldp+204,(vlSymsp->TOP__sodor_top.__PVT__dmem_resp_valid));
    bufp->fullBit(oldp+205,(vlSymsp->TOP__sodor_top.__PVT__dmem_req_valid));
    bufp->fullBit(oldp+206,(vlSymsp->TOP__sodor_top.__PVT__dmem_fcn_write_en));
    bufp->fullCData(oldp+207,(vlSymsp->TOP__sodor_top.__PVT__dmem_bit_typ),3);
    bufp->fullIData(oldp+208,(vlSymsp->TOP__sodor_top.__PVT__dmem_resp_data),32);
    bufp->fullIData(oldp+209,(vlSymsp->TOP__sodor_top__sodor_core.__PVT__io_imem_resp_bits_data),32);
    bufp->fullBit(oldp+210,(vlSymsp->TOP__sodor_top__sodor_core.__PVT__io_dmem_req_valid));
    bufp->fullBit(oldp+211,(vlSymsp->TOP__sodor_top__sodor_core.__PVT__io_dmem_req_bits_fcn));
    bufp->fullCData(oldp+212,(vlSymsp->TOP__sodor_top__sodor_core.__PVT__io_dmem_req_bits_typ),3);
    bufp->fullBit(oldp+213,(vlSymsp->TOP__sodor_top__sodor_core.__PVT__io_dmem_resp_valid));
    bufp->fullIData(oldp+214,(vlSymsp->TOP__sodor_top__sodor_core.__PVT__io_dmem_resp_bits_data),32);
    bufp->fullBit(oldp+215,(vlSymsp->TOP__sodor_top__sodor_core.__PVT__c_io_dmem_req_valid));
    bufp->fullBit(oldp+216,(vlSymsp->TOP__sodor_top__sodor_core.__PVT__c_io_dmem_req_bits_fcn));
    bufp->fullCData(oldp+217,(vlSymsp->TOP__sodor_top__sodor_core.__PVT__c_io_dmem_req_bits_typ),3);
    bufp->fullBit(oldp+218,(vlSymsp->TOP__sodor_top__sodor_core.__PVT__c_io_dmem_resp_valid));
    bufp->fullIData(oldp+219,(vlSymsp->TOP__sodor_top__sodor_core.__PVT__c_io_dat_inst),32);
    bufp->fullBit(oldp+220,(vlSymsp->TOP__sodor_top__sodor_core.__PVT__c_io_dat_csr_eret));
    bufp->fullBit(oldp+221,(vlSymsp->TOP__sodor_top__sodor_core.__PVT__c_io_ctl_stall));
    bufp->fullCData(oldp+222,(vlSymsp->TOP__sodor_top__sodor_core.__PVT__c_io_ctl_op1_sel),2);
    bufp->fullCData(oldp+223,(vlSymsp->TOP__sodor_top__sodor_core.__PVT__c_io_ctl_op2_sel),2);
    bufp->fullCData(oldp+224,(vlSymsp->TOP__sodor_top__sodor_core.__PVT__c_io_ctl_alu_fun),4);
    bufp->fullCData(oldp+225,(vlSymsp->TOP__sodor_top__sodor_core.__PVT__c_io_ctl_wb_sel),2);
    bufp->fullBit(oldp+226,(vlSymsp->TOP__sodor_top__sodor_core.__PVT__c_io_ctl_rf_wen));
    bufp->fullCData(oldp+227,(vlSymsp->TOP__sodor_top__sodor_core.__PVT__c_io_ctl_csr_cmd),3);
    bufp->fullBit(oldp+228,(vlSymsp->TOP__sodor_top__sodor_core.__PVT__c_io_ctl_exception));
    bufp->fullIData(oldp+229,(vlSymsp->TOP__sodor_top__sodor_core.__PVT__d_io_imem_resp_bits_data),32);
    bufp->fullIData(oldp+230,(vlSymsp->TOP__sodor_top__sodor_core.__PVT__d_io_dmem_resp_bits_data),32);
    bufp->fullBit(oldp+231,(vlSymsp->TOP__sodor_top__sodor_core.__PVT__d_io_ctl_stall));
    bufp->fullCData(oldp+232,(vlSymsp->TOP__sodor_top__sodor_core.__PVT__d_io_ctl_op1_sel),2);
    bufp->fullCData(oldp+233,(vlSymsp->TOP__sodor_top__sodor_core.__PVT__d_io_ctl_op2_sel),2);
    bufp->fullCData(oldp+234,(vlSymsp->TOP__sodor_top__sodor_core.__PVT__d_io_ctl_alu_fun),4);
    bufp->fullCData(oldp+235,(vlSymsp->TOP__sodor_top__sodor_core.__PVT__d_io_ctl_wb_sel),2);
    bufp->fullBit(oldp+236,(vlSymsp->TOP__sodor_top__sodor_core.__PVT__d_io_ctl_rf_wen));
    bufp->fullCData(oldp+237,(vlSymsp->TOP__sodor_top__sodor_core.__PVT__d_io_ctl_csr_cmd),3);
    bufp->fullBit(oldp+238,(vlSymsp->TOP__sodor_top__sodor_core.__PVT__d_io_ctl_exception));
    bufp->fullIData(oldp+239,(vlSymsp->TOP__sodor_top__sodor_core.__PVT__d_io_dat_inst),32);
    bufp->fullBit(oldp+240,(vlSymsp->TOP__sodor_top__sodor_core.__PVT__d_io_dat_csr_eret));
    bufp->fullIData(oldp+241,(vlSymsp->TOP__sodor_top__memory_modelling_inst.__PVT__imem_data),32);
    bufp->fullBit(oldp+242,(vlSymsp->TOP__sodor_top__memory_modelling_inst.__PVT__dmem_req_valid));
    bufp->fullBit(oldp+243,(vlSymsp->TOP__sodor_top__memory_modelling_inst.__PVT__dmem_req_write_en));
    bufp->fullCData(oldp+244,(vlSymsp->TOP__sodor_top__memory_modelling_inst.__PVT__dmem_req_bits_typ),3);
    bufp->fullBit(oldp+245,(vlSymsp->TOP__sodor_top__memory_modelling_inst.__PVT__dmem_resp_valid));
    bufp->fullIData(oldp+246,(vlSymsp->TOP__sodor_top__memory_modelling_inst.__PVT__dmem_resp_data),32);
    bufp->fullIData(oldp+247,(vlSymsp->TOP__sodor_top__memory_modelling_inst.__PVT__imem_read__Vstatic__mem_rdata),32);
    bufp->fullIData(oldp+248,(vlSymsp->TOP__sodor_top__memory_modelling_inst.__PVT__dmem_read__Vstatic__mem_rdata),32);
    bufp->fullIData(oldp+249,(vlSymsp->TOP__sodor_top__memory_modelling_inst.__PVT__dmem_write__Vstatic__m_addr),32);
    bufp->fullBit(oldp+250,(vlSymsp->TOP__sodor_top__sodor_core__c.__PVT__io_dmem_req_valid));
    bufp->fullBit(oldp+251,(vlSymsp->TOP__sodor_top__sodor_core__c.__PVT__io_dmem_req_bits_fcn));
    bufp->fullCData(oldp+252,(vlSymsp->TOP__sodor_top__sodor_core__c.__PVT__io_dmem_req_bits_typ),3);
    bufp->fullBit(oldp+253,(vlSymsp->TOP__sodor_top__sodor_core__c.__PVT__io_dmem_resp_valid));
    bufp->fullIData(oldp+254,(vlSymsp->TOP__sodor_top__sodor_core__c.__PVT__io_dat_inst),32);
    bufp->fullBit(oldp+255,(vlSymsp->TOP__sodor_top__sodor_core__c.__PVT__io_dat_csr_eret));
    bufp->fullBit(oldp+256,(vlSymsp->TOP__sodor_top__sodor_core__c.__PVT__io_ctl_stall));
    bufp->fullCData(oldp+257,(vlSymsp->TOP__sodor_top__sodor_core__c.__PVT__io_ctl_op1_sel),2);
    bufp->fullCData(oldp+258,(vlSymsp->TOP__sodor_top__sodor_core__c.__PVT__io_ctl_op2_sel),2);
    bufp->fullCData(oldp+259,(vlSymsp->TOP__sodor_top__sodor_core__c.__PVT__io_ctl_alu_fun),4);
    bufp->fullCData(oldp+260,(vlSymsp->TOP__sodor_top__sodor_core__c.__PVT__io_ctl_wb_sel),2);
    bufp->fullBit(oldp+261,(vlSymsp->TOP__sodor_top__sodor_core__c.__PVT__io_ctl_rf_wen));
    bufp->fullCData(oldp+262,(vlSymsp->TOP__sodor_top__sodor_core__c.__PVT__io_ctl_csr_cmd),3);
    bufp->fullBit(oldp+263,(vlSymsp->TOP__sodor_top__sodor_core__c.__PVT__io_ctl_exception));
    bufp->fullBit(oldp+264,(vlSymsp->TOP__sodor_top__sodor_core__c.__PVT__cs_val_inst));
    bufp->fullCData(oldp+265,(vlSymsp->TOP__sodor_top__sodor_core__c.__PVT__cs_br_type),4);
    bufp->fullBit(oldp+266,(vlSymsp->TOP__sodor_top__sodor_core__c.__PVT__cs0_2));
    bufp->fullBit(oldp+267,(vlSymsp->TOP__sodor_top__sodor_core__c.__PVT__cs0_3));
    bufp->fullCData(oldp+268,(vlSymsp->TOP__sodor_top__sodor_core__c.__PVT__cs0_6),3);
    bufp->fullBit(oldp+269,(vlSymsp->TOP__sodor_top__sodor_core__c.__PVT__stall));
    bufp->fullCData(oldp+270,(vlSymsp->TOP__sodor_top__sodor_core__c.__PVT__rs1_addr),5);
    bufp->fullBit(oldp+271,(vlSymsp->TOP__sodor_top__sodor_core__c.__PVT__csr_ren));
    bufp->fullCData(oldp+272,(vlSymsp->TOP__sodor_top__sodor_core__c.__PVT__csr_cmd),3);
    bufp->fullIData(oldp+273,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__io_imem_resp_bits_data),32);
    bufp->fullIData(oldp+274,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__io_dmem_resp_bits_data),32);
    bufp->fullBit(oldp+275,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__io_ctl_stall));
    bufp->fullCData(oldp+276,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__io_ctl_op1_sel),2);
    bufp->fullCData(oldp+277,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__io_ctl_op2_sel),2);
    bufp->fullCData(oldp+278,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__io_ctl_alu_fun),4);
    bufp->fullCData(oldp+279,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__io_ctl_wb_sel),2);
    bufp->fullBit(oldp+280,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__io_ctl_rf_wen));
    bufp->fullCData(oldp+281,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__io_ctl_csr_cmd),3);
    bufp->fullBit(oldp+282,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__io_ctl_exception));
    bufp->fullIData(oldp+283,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__io_dat_inst),32);
    bufp->fullBit(oldp+284,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__io_dat_csr_eret));
    bufp->fullCData(oldp+285,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__regfile_MPORT_3_addr),5);
    bufp->fullCData(oldp+286,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__regfile_MPORT_4_addr),5);
    bufp->fullCData(oldp+287,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__regfile_MPORT_addr),5);
    bufp->fullBit(oldp+288,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__regfile_MPORT_en));
    bufp->fullCData(oldp+289,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__csr_io_rw_cmd),3);
    bufp->fullBit(oldp+290,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__csr_io_eret));
    bufp->fullSData(oldp+291,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__csr_io_decode_csr),12);
    bufp->fullBit(oldp+292,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__csr_io_exception));
    bufp->fullBit(oldp+293,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__csr_io_retire));
    bufp->fullCData(oldp+294,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__rs1_addr),5);
    bufp->fullSData(oldp+295,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__imm_i),12);
    bufp->fullIData(oldp+296,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__imm_i_sext),32);
    bufp->fullIData(oldp+297,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__imm_j),20);
    bufp->fullIData(oldp+298,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__imm_j_sext),32);
    bufp->fullSData(oldp+299,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__imm_b),12);
    bufp->fullIData(oldp+300,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__imm_b_sext),32);
    bufp->fullCData(oldp+301,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__rs2_addr),5);
    bufp->fullCData(oldp+302,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__wb_addr),5);
    bufp->fullBit(oldp+303,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__wb_wen));
    bufp->fullIData(oldp+304,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__imm_u),20);
    bufp->fullIData(oldp+305,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__imm_u_sext),32);
    bufp->fullIData(oldp+306,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__imm_z),32);
    bufp->fullSData(oldp+307,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__imm_s),12);
    bufp->fullIData(oldp+308,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__imm_s_sext),32);
    bufp->fullCData(oldp+309,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__io_rw_cmd),3);
    bufp->fullBit(oldp+310,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__io_eret));
    bufp->fullSData(oldp+311,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__io_decode_csr),12);
    bufp->fullBit(oldp+312,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__io_exception));
    bufp->fullBit(oldp+313,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__io_retire));
    bufp->fullBit(oldp+314,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__system_insn));
    bufp->fullBit(oldp+315,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__cpu_ren));
    bufp->fullBit(oldp+316,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__read_only));
    bufp->fullBit(oldp+317,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__cpu_wen));
    bufp->fullBit(oldp+318,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__wen));
    bufp->fullCData(oldp+319,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__opcode),8);
    bufp->fullBit(oldp+320,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__insn_call));
    bufp->fullBit(oldp+321,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__insn_break));
    bufp->fullBit(oldp+322,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__insn_ret));
    bufp->fullIData(oldp+323,(vlSymsp->TOP__sodor_top__sodor_core.__PVT__io_ddpath_rdata),32);
    bufp->fullIData(oldp+324,(vlSymsp->TOP__sodor_top__sodor_core.__PVT__d_io_ddpath_rdata),32);
    bufp->fullIData(oldp+325,(vlSymsp->TOP__sodor_top__memory_modelling_inst.__PVT__imem_addr),32);
    bufp->fullIData(oldp+326,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__io_ddpath_rdata),32);
    bufp->fullIData(oldp+327,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__regfile_MPORT_1_data),32);
    bufp->fullIData(oldp+328,(vlSymsp->TOP__sodor_top.__PVT__dmem_req_addr),32);
    bufp->fullIData(oldp+329,(vlSymsp->TOP__sodor_top.__PVT__dmem_req_data),32);
    bufp->fullIData(oldp+330,(vlSymsp->TOP__sodor_top__sodor_core.__PVT__io_dmem_req_bits_addr),32);
    bufp->fullIData(oldp+331,(vlSymsp->TOP__sodor_top__sodor_core.__PVT__io_dmem_req_bits_data),32);
    bufp->fullBit(oldp+332,(vlSymsp->TOP__sodor_top__sodor_core.__PVT__c_io_dat_br_eq));
    bufp->fullBit(oldp+333,(vlSymsp->TOP__sodor_top__sodor_core.__PVT__c_io_dat_br_lt));
    bufp->fullBit(oldp+334,(vlSymsp->TOP__sodor_top__sodor_core.__PVT__c_io_dat_br_ltu));
    bufp->fullCData(oldp+335,(vlSymsp->TOP__sodor_top__sodor_core.__PVT__c_io_ctl_pc_sel),3);
    bufp->fullIData(oldp+336,(vlSymsp->TOP__sodor_top__sodor_core.__PVT__d_io_dmem_req_bits_addr),32);
    bufp->fullIData(oldp+337,(vlSymsp->TOP__sodor_top__sodor_core.__PVT__d_io_dmem_req_bits_data),32);
    bufp->fullCData(oldp+338,(vlSymsp->TOP__sodor_top__sodor_core.__PVT__d_io_ctl_pc_sel),3);
    bufp->fullBit(oldp+339,(vlSymsp->TOP__sodor_top__sodor_core.__PVT__d_io_dat_br_eq));
    bufp->fullBit(oldp+340,(vlSymsp->TOP__sodor_top__sodor_core.__PVT__d_io_dat_br_lt));
    bufp->fullBit(oldp+341,(vlSymsp->TOP__sodor_top__sodor_core.__PVT__d_io_dat_br_ltu));
    bufp->fullIData(oldp+342,(vlSymsp->TOP__sodor_top__memory_modelling_inst.__PVT__dmem_req_addr),32);
    bufp->fullIData(oldp+343,(vlSymsp->TOP__sodor_top__memory_modelling_inst.__PVT__dmem_req_data),32);
    bufp->fullBit(oldp+344,(vlSymsp->TOP__sodor_top__sodor_core__c.__PVT__io_dat_br_eq));
    bufp->fullBit(oldp+345,(vlSymsp->TOP__sodor_top__sodor_core__c.__PVT__io_dat_br_lt));
    bufp->fullBit(oldp+346,(vlSymsp->TOP__sodor_top__sodor_core__c.__PVT__io_dat_br_ltu));
    bufp->fullCData(oldp+347,(vlSymsp->TOP__sodor_top__sodor_core__c.__PVT__io_ctl_pc_sel),3);
    bufp->fullIData(oldp+348,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__io_dmem_req_bits_addr),32);
    bufp->fullIData(oldp+349,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__io_dmem_req_bits_data),32);
    bufp->fullCData(oldp+350,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__io_ctl_pc_sel),3);
    bufp->fullBit(oldp+351,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__io_dat_br_eq));
    bufp->fullBit(oldp+352,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__io_dat_br_lt));
    bufp->fullBit(oldp+353,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__io_dat_br_ltu));
    bufp->fullIData(oldp+354,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__regfile_MPORT_3_data),32);
    bufp->fullIData(oldp+355,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__regfile_MPORT_4_data),32);
    bufp->fullIData(oldp+356,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__csr_io_rw_wdata),32);
    bufp->fullIData(oldp+357,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__rs1_data),32);
    bufp->fullIData(oldp+358,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__jump_reg_target),32);
    bufp->fullIData(oldp+359,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__jmp_target),32);
    bufp->fullIData(oldp+360,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__br_target),32);
    bufp->fullIData(oldp+361,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__alu_op1),32);
    bufp->fullIData(oldp+362,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__rs2_data),32);
    bufp->fullIData(oldp+363,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__alu_op2),32);
    bufp->fullCData(oldp+364,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__alu_shamt),5);
    bufp->fullIData(oldp+365,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__alu_out),32);
    bufp->fullIData(oldp+366,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__io_rw_wdata),32);
    bufp->fullIData(oldp+367,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__csr_io_rw_rdata),32);
    bufp->fullIData(oldp+368,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__csr_io_evec),32);
    bufp->fullIData(oldp+369,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__exception_target),32);
    bufp->fullIData(oldp+370,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__io_rw_rdata),32);
    bufp->fullIData(oldp+371,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__io_evec),32);
    bufp->fullIData(oldp+372,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__regfile_MPORT_data),32);
    bufp->fullIData(oldp+373,(vlSymsp->TOP__sodor_top__sodor_core__d.__PVT__wb_data),32);
    bufp->fullIData(oldp+374,(vlSymsp->TOP__sodor_top__sodor_core__d__csr.__PVT__wdata),32);
    bufp->fullBit(oldp+375,(vlSelf->clk));
    bufp->fullBit(oldp+376,(vlSelf->rst));
    bufp->fullCData(oldp+377,(vlSymsp->TOP__sodor_top.__PVT__ddpath_addr),5);
    bufp->fullCData(oldp+378,(vlSymsp->TOP__sodor_top__sodor_core.__PVT__io_ddpath_addr),5);
    bufp->fullIData(oldp+379,(vlSymsp->TOP__sodor_top__sodor_core.__PVT__io_ddpath_wdata),32);
}
