// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_c.h"
#include "Vpicorv32core__Syms.h"


VL_ATTR_COLD void Vpicorv32core___024root__trace_init_sub__TOP__picorv32core__0(Vpicorv32core___024root* vlSelf, VerilatedVcd* tracep);

VL_ATTR_COLD void Vpicorv32core___024root__trace_init_sub__TOP__0(Vpicorv32core___024root* vlSelf, VerilatedVcd* tracep) {
    (void)vlSelf;  // Prevent unused variable warning
    Vpicorv32core__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vpicorv32core___024root__trace_init_sub__TOP__0\n"); );
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->pushPrefix("picorv32core", VerilatedTracePrefixType::SCOPE_MODULE);
    Vpicorv32core___024root__trace_init_sub__TOP__picorv32core__0(vlSelf, tracep);
    tracep->popPrefix();
    tracep->declBit(c+293,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+294,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
}

VL_ATTR_COLD void Vpicorv32core___024root__trace_init_sub__TOP__picorv32core__picorv32_core__0(Vpicorv32core___024root* vlSelf, VerilatedVcd* tracep);
VL_ATTR_COLD void Vpicorv32core___024root__trace_init_sub__TOP__picorv32core__memory_modelling_inst__0(Vpicorv32core___024root* vlSelf, VerilatedVcd* tracep);

VL_ATTR_COLD void Vpicorv32core___024root__trace_init_sub__TOP__picorv32core__0(Vpicorv32core___024root* vlSelf, VerilatedVcd* tracep) {
    (void)vlSelf;  // Prevent unused variable warning
    Vpicorv32core__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vpicorv32core___024root__trace_init_sub__TOP__picorv32core__0\n"); );
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declBit(c+16,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+17,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+52,0,"mem_valid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+53,0,"mem_instr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+258,0,"mem_ready",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+54,0,"mem_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+55,0,"mem_wdata",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+56,0,"mem_wstrb",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+259,0,"mem_rdata",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+275,0,"mem_la_read",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+276,0,"mem_la_write",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+57,0,"mem_la_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+283,0,"mem_la_wdata",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+284,0,"mem_la_wstrb",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+295,0,"resetn",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->pushPrefix("picorv32_core", VerilatedTracePrefixType::SCOPE_MODULE);
    Vpicorv32core___024root__trace_init_sub__TOP__picorv32core__picorv32_core__0(vlSelf, tracep);
    tracep->popPrefix();
    tracep->pushPrefix("memory_modelling_inst", VerilatedTracePrefixType::SCOPE_MODULE);
    Vpicorv32core___024root__trace_init_sub__TOP__picorv32core__memory_modelling_inst__0(vlSelf, tracep);
    tracep->popPrefix();
}

VL_ATTR_COLD void Vpicorv32core___024root__trace_init_sub__TOP__picorv32core__memory_modelling_inst__0(Vpicorv32core___024root* vlSelf, VerilatedVcd* tracep) {
    (void)vlSelf;  // Prevent unused variable warning
    Vpicorv32core__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vpicorv32core___024root__trace_init_sub__TOP__picorv32core__memory_modelling_inst__0\n"); );
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declBit(c+18,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+285,0,"mem_la_wstrb",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+286,0,"mem_la_wdata",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+296,0,"mem_la_addr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+277,0,"mem_la_read",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+278,0,"mem_la_write",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+58,0,"mem_instr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+59,0,"mem_valid",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+260,0,"mem_ready",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+261,0,"mem_rdata",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+299,0,"file_handle",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+262,0,"mem_read__Vstatic__mem_rdata",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+263,0,"mem_write__Vstatic__m_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
}

VL_ATTR_COLD void Vpicorv32core___024root__trace_init_sub__TOP__picorv32core__picorv32_core__cpuregs__0(Vpicorv32core___024root* vlSelf, VerilatedVcd* tracep);

VL_ATTR_COLD void Vpicorv32core___024root__trace_init_sub__TOP__picorv32core__picorv32_core__0(Vpicorv32core___024root* vlSelf, VerilatedVcd* tracep) {
    (void)vlSelf;  // Prevent unused variable warning
    Vpicorv32core__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vpicorv32core___024root__trace_init_sub__TOP__picorv32core__picorv32_core__0\n"); );
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declBus(c+300,0,"ENABLE_COUNTERS",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+300,0,"ENABLE_COUNTERS64",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+300,0,"ENABLE_REGS_16_31",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+300,0,"ENABLE_REGS_DUALPORT",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+301,0,"LATCHED_MEM_RDATA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+300,0,"TWO_STAGE_SHIFT",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+301,0,"BARREL_SHIFTER",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+301,0,"TWO_CYCLE_COMPARE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+301,0,"TWO_CYCLE_ALU",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+301,0,"COMPRESSED_ISA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+300,0,"CATCH_MISALIGN",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+300,0,"CATCH_ILLINSN",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+301,0,"ENABLE_PCPI",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+301,0,"ENABLE_MUL",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+301,0,"ENABLE_FAST_MUL",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+301,0,"ENABLE_DIV",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+301,0,"ENABLE_IRQ",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+300,0,"ENABLE_IRQ_QREGS",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+300,0,"ENABLE_IRQ_TIMER",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+301,0,"ENABLE_TRACE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+301,0,"REGS_INIT_ZERO",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+302,0,"MASKED_IRQ",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+303,0,"LATCHED_IRQ",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+302,0,"PROGADDR_RESET",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+304,0,"PROGADDR_IRQ",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+303,0,"STACKADDR",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+19,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+297,0,"resetn",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+60,0,"trap",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+61,0,"mem_valid",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+62,0,"mem_instr",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+264,0,"mem_ready",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+63,0,"mem_addr",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+64,0,"mem_wdata",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+65,0,"mem_wstrb",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+265,0,"mem_rdata",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+279,0,"mem_la_read",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+280,0,"mem_la_write",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+66,0,"mem_la_addr",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+287,0,"mem_la_wdata",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+288,0,"mem_la_wstrb",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+67,0,"pcpi_valid",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+68,0,"pcpi_insn",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+69,0,"pcpi_rs1",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+70,0,"pcpi_rs2",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+305,0,"pcpi_wr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+306,0,"pcpi_rd",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+307,0,"pcpi_wait",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+308,0,"pcpi_ready",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+309,0,"irq",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+71,0,"eoi",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+72,0,"trace_valid",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declQuad(c+73,0,"trace_data",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 35,0);
    tracep->declBus(c+310,0,"irq_timer",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBus(c+311,0,"irq_ebreak",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBus(c+312,0,"irq_buserror",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBus(c+313,0,"irqregs_offset",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBus(c+313,0,"regfile_size",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBus(c+314,0,"regindex_bits",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBus(c+301,0,"WITH_PCPI",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declQuad(c+315,0,"TRACE_BRANCH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 35,0);
    tracep->declQuad(c+317,0,"TRACE_ADDR",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 35,0);
    tracep->declQuad(c+319,0,"TRACE_IRQ",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 35,0);
    tracep->declQuad(c+75,0,"count_cycle",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 63,0);
    tracep->declQuad(c+77,0,"count_instr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 63,0);
    tracep->declBus(c+79,0,"reg_pc",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+80,0,"reg_next_pc",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+81,0,"reg_op1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+82,0,"reg_op2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+83,0,"reg_out",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+84,0,"reg_sh",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+85,0,"next_insn_opcode",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+86,0,"dbg_insn_opcode",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+87,0,"dbg_insn_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+88,0,"dbg_mem_valid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+89,0,"dbg_mem_instr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+266,0,"dbg_mem_ready",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+90,0,"dbg_mem_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+91,0,"dbg_mem_wdata",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+92,0,"dbg_mem_wstrb",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+267,0,"dbg_mem_rdata",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+93,0,"next_pc",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+94,0,"irq_delay",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+95,0,"irq_active",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+96,0,"irq_mask",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+97,0,"irq_pending",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+98,0,"timer",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+1,0,"pcpi_mul_wr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+2,0,"pcpi_mul_rd",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+3,0,"pcpi_mul_wait",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+4,0,"pcpi_mul_ready",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+5,0,"pcpi_div_wr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+6,0,"pcpi_div_rd",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+7,0,"pcpi_div_wait",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+8,0,"pcpi_div_ready",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+9,0,"pcpi_int_wr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+10,0,"pcpi_int_rd",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+11,0,"pcpi_int_wait",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+12,0,"pcpi_int_ready",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+99,0,"mem_state",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+100,0,"mem_wordsize",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+289,0,"mem_rdata_word",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+101,0,"mem_rdata_q",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+102,0,"mem_do_prefetch",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+103,0,"mem_do_rinst",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+104,0,"mem_do_rdata",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+105,0,"mem_do_wdata",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+290,0,"mem_xfer",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+106,0,"mem_la_secondword",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+107,0,"mem_la_firstword_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+108,0,"last_mem_valid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+13,0,"mem_la_firstword",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+14,0,"mem_la_firstword_xfer",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+109,0,"prefetched_high_word",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+281,0,"clear_prefetched_high_word",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+321,0,"mem_16bit_buffer",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+291,0,"mem_rdata_latched_noshuffle",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+292,0,"mem_rdata_latched",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+15,0,"mem_la_use_prefetched_high_word",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+110,0,"mem_busy",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+298,0,"mem_done",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+111,0,"instr_lui",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+112,0,"instr_auipc",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+113,0,"instr_jal",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+114,0,"instr_jalr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+115,0,"instr_beq",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+116,0,"instr_bne",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+117,0,"instr_blt",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+118,0,"instr_bge",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+119,0,"instr_bltu",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+120,0,"instr_bgeu",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+121,0,"instr_lb",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+122,0,"instr_lh",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+123,0,"instr_lw",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+124,0,"instr_lbu",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+125,0,"instr_lhu",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+126,0,"instr_sb",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+127,0,"instr_sh",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+128,0,"instr_sw",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+129,0,"instr_addi",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+130,0,"instr_slti",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+131,0,"instr_sltiu",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+132,0,"instr_xori",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+133,0,"instr_ori",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+134,0,"instr_andi",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+135,0,"instr_slli",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+136,0,"instr_srli",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+137,0,"instr_srai",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+138,0,"instr_add",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+139,0,"instr_sub",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+140,0,"instr_sll",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+141,0,"instr_slt",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+142,0,"instr_sltu",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+143,0,"instr_xor",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+144,0,"instr_srl",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+145,0,"instr_sra",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+146,0,"instr_or",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+147,0,"instr_and",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+148,0,"instr_rdcycle",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+149,0,"instr_rdcycleh",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+150,0,"instr_rdinstr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+151,0,"instr_rdinstrh",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+152,0,"instr_ecall_ebreak",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+153,0,"instr_getq",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+154,0,"instr_setq",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+155,0,"instr_retirq",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+156,0,"instr_maskirq",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+157,0,"instr_waitirq",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+158,0,"instr_timer",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+159,0,"instr_trap",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+160,0,"decoded_rd",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+161,0,"decoded_rs1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+162,0,"decoded_rs2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+163,0,"decoded_imm",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+164,0,"decoded_imm_j",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+165,0,"decoder_trigger",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+166,0,"decoder_trigger_q",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+167,0,"decoder_pseudo_trigger",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+168,0,"decoder_pseudo_trigger_q",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+169,0,"compressed_instr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+170,0,"is_lui_auipc_jal",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+171,0,"is_lb_lh_lw_lbu_lhu",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+172,0,"is_slli_srli_srai",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+173,0,"is_jalr_addi_slti_sltiu_xori_ori_andi",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+174,0,"is_sb_sh_sw",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+175,0,"is_sll_srl_sra",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+176,0,"is_lui_auipc_jal_jalr_addi_add_sub",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+177,0,"is_slti_blt_slt",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+178,0,"is_sltiu_bltu_sltu",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+179,0,"is_beq_bne_blt_bge_bltu_bgeu",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+180,0,"is_lbu_lhu_lw",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+181,0,"is_alu_reg_imm",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+182,0,"is_alu_reg_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+183,0,"is_compare",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+184,0,"is_rdcycle_rdcycleh_rdinstr_rdinstrh",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declQuad(c+185,0,"new_ascii_instr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 63,0);
    tracep->declQuad(c+187,0,"dbg_ascii_instr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 63,0);
    tracep->declBus(c+189,0,"dbg_insn_imm",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+190,0,"dbg_insn_rs1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+191,0,"dbg_insn_rs2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+192,0,"dbg_insn_rd",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+193,0,"dbg_rs1val",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+194,0,"dbg_rs2val",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+195,0,"dbg_rs1val_valid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+196,0,"dbg_rs2val_valid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declQuad(c+197,0,"q_ascii_instr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 63,0);
    tracep->declBus(c+199,0,"q_insn_imm",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+200,0,"q_insn_opcode",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+201,0,"q_insn_rs1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+202,0,"q_insn_rs2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+203,0,"q_insn_rd",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBit(c+204,0,"dbg_next",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+205,0,"launch_next_insn",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+206,0,"dbg_valid_insn",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declQuad(c+207,0,"cached_ascii_instr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 63,0);
    tracep->declBus(c+209,0,"cached_insn_imm",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+210,0,"cached_insn_opcode",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+211,0,"cached_insn_rs1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+212,0,"cached_insn_rs2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+213,0,"cached_insn_rd",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+322,0,"cpu_state_trap",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+323,0,"cpu_state_fetch",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+324,0,"cpu_state_ld_rs1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+325,0,"cpu_state_ld_rs2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+326,0,"cpu_state_exec",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+327,0,"cpu_state_shift",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+328,0,"cpu_state_stmem",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+329,0,"cpu_state_ldmem",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+214,0,"cpu_state",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+215,0,"irq_state",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declArray(c+216,0,"dbg_ascii_state",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declBit(c+220,0,"set_mem_do_rinst",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+221,0,"set_mem_do_rdata",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+222,0,"set_mem_do_wdata",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+223,0,"latched_store",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+224,0,"latched_stalu",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+225,0,"latched_branch",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+226,0,"latched_compr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+227,0,"latched_trace",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+228,0,"latched_is_lu",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+229,0,"latched_is_lh",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+230,0,"latched_is_lb",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+231,0,"latched_rd",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+232,0,"current_pc",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+330,0,"pcpi_timeout_counter",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+233,0,"pcpi_timeout",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+234,0,"next_irq_pending",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+235,0,"do_waitirq",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+236,0,"alu_out",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+237,0,"alu_out_q",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+238,0,"alu_out_0",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+239,0,"alu_out_0_q",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+240,0,"alu_wait",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+241,0,"alu_wait_2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+242,0,"alu_add_sub",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+243,0,"alu_shl",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+244,0,"alu_shr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+245,0,"alu_eq",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+246,0,"alu_ltu",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+247,0,"alu_lts",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+248,0,"clear_prefetched_high_word_q",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+249,0,"cpuregs_write",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+250,0,"cpuregs_wrdata",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+268,0,"cpuregs_rs1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+269,0,"cpuregs_rs2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+270,0,"decoded_rs",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+271,0,"cpuregs_rdata1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+272,0,"cpuregs_rdata2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+251,0,"cpuregs_waddr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+252,0,"cpuregs_raddr1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+253,0,"cpuregs_raddr2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->pushPrefix("cpuregs", VerilatedTracePrefixType::SCOPE_MODULE);
    Vpicorv32core___024root__trace_init_sub__TOP__picorv32core__picorv32_core__cpuregs__0(vlSelf, tracep);
    tracep->popPrefix();
}

VL_ATTR_COLD void Vpicorv32core___024root__trace_init_sub__TOP__picorv32core__picorv32_core__cpuregs__0(Vpicorv32core___024root* vlSelf, VerilatedVcd* tracep) {
    (void)vlSelf;  // Prevent unused variable warning
    Vpicorv32core__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vpicorv32core___024root__trace_init_sub__TOP__picorv32core__picorv32_core__cpuregs__0\n"); );
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declBit(c+20,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+282,0,"wen",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+254,0,"waddr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+255,0,"raddr1",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+256,0,"raddr2",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+257,0,"wdata",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+273,0,"rdata1",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+274,0,"rdata2",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->pushPrefix("regs", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 31; ++i) {
        tracep->declBus(c+21+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, true,(i+0), 31,0);
    }
    tracep->popPrefix();
}

VL_ATTR_COLD void Vpicorv32core___024root__trace_init_top(Vpicorv32core___024root* vlSelf, VerilatedVcd* tracep) {
    (void)vlSelf;  // Prevent unused variable warning
    Vpicorv32core__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vpicorv32core___024root__trace_init_top\n"); );
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    Vpicorv32core___024root__trace_init_sub__TOP__0(vlSelf, tracep);
}

VL_ATTR_COLD void Vpicorv32core___024root__trace_const_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
VL_ATTR_COLD void Vpicorv32core___024root__trace_full_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vpicorv32core___024root__trace_chg_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vpicorv32core___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/);

VL_ATTR_COLD void Vpicorv32core___024root__trace_register(Vpicorv32core___024root* vlSelf, VerilatedVcd* tracep) {
    (void)vlSelf;  // Prevent unused variable warning
    Vpicorv32core__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vpicorv32core___024root__trace_register\n"); );
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    tracep->addConstCb(&Vpicorv32core___024root__trace_const_0, 0U, vlSelf);
    tracep->addFullCb(&Vpicorv32core___024root__trace_full_0, 0U, vlSelf);
    tracep->addChgCb(&Vpicorv32core___024root__trace_chg_0, 0U, vlSelf);
    tracep->addCleanupCb(&Vpicorv32core___024root__trace_cleanup, vlSelf);
}

VL_ATTR_COLD void Vpicorv32core___024root__trace_const_0_sub_0(Vpicorv32core___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void Vpicorv32core___024root__trace_const_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vpicorv32core___024root__trace_const_0\n"); );
    // Init
    Vpicorv32core___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vpicorv32core___024root*>(voidSelf);
    Vpicorv32core__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    Vpicorv32core___024root__trace_const_0_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vpicorv32core___024root__trace_const_0_sub_0(Vpicorv32core___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    (void)vlSelf;  // Prevent unused variable warning
    Vpicorv32core__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vpicorv32core___024root__trace_const_0_sub_0\n"); );
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    // Body
    bufp->fullIData(oldp+299,(vlSymsp->TOP__picorv32core__memory_modelling_inst.__PVT__file_handle),32);
    bufp->fullBit(oldp+300,(1U));
    bufp->fullBit(oldp+301,(0U));
    bufp->fullIData(oldp+302,(0U),32);
    bufp->fullIData(oldp+303,(0xffffffffU),32);
    bufp->fullIData(oldp+304,(0x10U),32);
    bufp->fullBit(oldp+305,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__pcpi_wr));
    bufp->fullIData(oldp+306,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__pcpi_rd),32);
    bufp->fullBit(oldp+307,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__pcpi_wait));
    bufp->fullBit(oldp+308,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__pcpi_ready));
    bufp->fullIData(oldp+309,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__irq),32);
    bufp->fullIData(oldp+310,(0U),32);
    bufp->fullIData(oldp+311,(1U),32);
    bufp->fullIData(oldp+312,(2U),32);
    bufp->fullIData(oldp+313,(0x20U),32);
    bufp->fullIData(oldp+314,(5U),32);
    bufp->fullQData(oldp+315,(0x100000000ULL),36);
    bufp->fullQData(oldp+317,(0x200000000ULL),36);
    bufp->fullQData(oldp+319,(0x800000000ULL),36);
    bufp->fullSData(oldp+321,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__mem_16bit_buffer),16);
    bufp->fullCData(oldp+322,(0x80U),8);
    bufp->fullCData(oldp+323,(0x40U),8);
    bufp->fullCData(oldp+324,(0x20U),8);
    bufp->fullCData(oldp+325,(0x10U),8);
    bufp->fullCData(oldp+326,(8U),8);
    bufp->fullCData(oldp+327,(4U),8);
    bufp->fullCData(oldp+328,(2U),8);
    bufp->fullCData(oldp+329,(1U),8);
    bufp->fullCData(oldp+330,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__pcpi_timeout_counter),4);
}

VL_ATTR_COLD void Vpicorv32core___024root__trace_full_0_sub_0(Vpicorv32core___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void Vpicorv32core___024root__trace_full_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vpicorv32core___024root__trace_full_0\n"); );
    // Init
    Vpicorv32core___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vpicorv32core___024root*>(voidSelf);
    Vpicorv32core__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    Vpicorv32core___024root__trace_full_0_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vpicorv32core___024root__trace_full_0_sub_0(Vpicorv32core___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    (void)vlSelf;  // Prevent unused variable warning
    Vpicorv32core__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vpicorv32core___024root__trace_full_0_sub_0\n"); );
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    // Body
    bufp->fullBit(oldp+1,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__pcpi_mul_wr));
    bufp->fullIData(oldp+2,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__pcpi_mul_rd),32);
    bufp->fullBit(oldp+3,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__pcpi_mul_wait));
    bufp->fullBit(oldp+4,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__pcpi_mul_ready));
    bufp->fullBit(oldp+5,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__pcpi_div_wr));
    bufp->fullIData(oldp+6,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__pcpi_div_rd),32);
    bufp->fullBit(oldp+7,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__pcpi_div_wait));
    bufp->fullBit(oldp+8,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__pcpi_div_ready));
    bufp->fullBit(oldp+9,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__pcpi_int_wr));
    bufp->fullIData(oldp+10,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__pcpi_int_rd),32);
    bufp->fullBit(oldp+11,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__pcpi_int_wait));
    bufp->fullBit(oldp+12,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__pcpi_int_ready));
    bufp->fullBit(oldp+13,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__mem_la_firstword));
    bufp->fullBit(oldp+14,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__mem_la_firstword_xfer));
    bufp->fullBit(oldp+15,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__mem_la_use_prefetched_high_word));
    bufp->fullBit(oldp+16,(vlSymsp->TOP__picorv32core.clk));
    bufp->fullBit(oldp+17,(vlSymsp->TOP__picorv32core.rst));
    bufp->fullBit(oldp+18,(vlSymsp->TOP__picorv32core__memory_modelling_inst.__PVT__clk));
    bufp->fullBit(oldp+19,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__clk));
    bufp->fullBit(oldp+20,(vlSymsp->TOP__picorv32core__picorv32_core__cpuregs.__PVT__clk));
    bufp->fullIData(oldp+21,(vlSymsp->TOP__picorv32core__picorv32_core__cpuregs.__PVT__regs[0]),32);
    bufp->fullIData(oldp+22,(vlSymsp->TOP__picorv32core__picorv32_core__cpuregs.__PVT__regs[1]),32);
    bufp->fullIData(oldp+23,(vlSymsp->TOP__picorv32core__picorv32_core__cpuregs.__PVT__regs[2]),32);
    bufp->fullIData(oldp+24,(vlSymsp->TOP__picorv32core__picorv32_core__cpuregs.__PVT__regs[3]),32);
    bufp->fullIData(oldp+25,(vlSymsp->TOP__picorv32core__picorv32_core__cpuregs.__PVT__regs[4]),32);
    bufp->fullIData(oldp+26,(vlSymsp->TOP__picorv32core__picorv32_core__cpuregs.__PVT__regs[5]),32);
    bufp->fullIData(oldp+27,(vlSymsp->TOP__picorv32core__picorv32_core__cpuregs.__PVT__regs[6]),32);
    bufp->fullIData(oldp+28,(vlSymsp->TOP__picorv32core__picorv32_core__cpuregs.__PVT__regs[7]),32);
    bufp->fullIData(oldp+29,(vlSymsp->TOP__picorv32core__picorv32_core__cpuregs.__PVT__regs[8]),32);
    bufp->fullIData(oldp+30,(vlSymsp->TOP__picorv32core__picorv32_core__cpuregs.__PVT__regs[9]),32);
    bufp->fullIData(oldp+31,(vlSymsp->TOP__picorv32core__picorv32_core__cpuregs.__PVT__regs[10]),32);
    bufp->fullIData(oldp+32,(vlSymsp->TOP__picorv32core__picorv32_core__cpuregs.__PVT__regs[11]),32);
    bufp->fullIData(oldp+33,(vlSymsp->TOP__picorv32core__picorv32_core__cpuregs.__PVT__regs[12]),32);
    bufp->fullIData(oldp+34,(vlSymsp->TOP__picorv32core__picorv32_core__cpuregs.__PVT__regs[13]),32);
    bufp->fullIData(oldp+35,(vlSymsp->TOP__picorv32core__picorv32_core__cpuregs.__PVT__regs[14]),32);
    bufp->fullIData(oldp+36,(vlSymsp->TOP__picorv32core__picorv32_core__cpuregs.__PVT__regs[15]),32);
    bufp->fullIData(oldp+37,(vlSymsp->TOP__picorv32core__picorv32_core__cpuregs.__PVT__regs[16]),32);
    bufp->fullIData(oldp+38,(vlSymsp->TOP__picorv32core__picorv32_core__cpuregs.__PVT__regs[17]),32);
    bufp->fullIData(oldp+39,(vlSymsp->TOP__picorv32core__picorv32_core__cpuregs.__PVT__regs[18]),32);
    bufp->fullIData(oldp+40,(vlSymsp->TOP__picorv32core__picorv32_core__cpuregs.__PVT__regs[19]),32);
    bufp->fullIData(oldp+41,(vlSymsp->TOP__picorv32core__picorv32_core__cpuregs.__PVT__regs[20]),32);
    bufp->fullIData(oldp+42,(vlSymsp->TOP__picorv32core__picorv32_core__cpuregs.__PVT__regs[21]),32);
    bufp->fullIData(oldp+43,(vlSymsp->TOP__picorv32core__picorv32_core__cpuregs.__PVT__regs[22]),32);
    bufp->fullIData(oldp+44,(vlSymsp->TOP__picorv32core__picorv32_core__cpuregs.__PVT__regs[23]),32);
    bufp->fullIData(oldp+45,(vlSymsp->TOP__picorv32core__picorv32_core__cpuregs.__PVT__regs[24]),32);
    bufp->fullIData(oldp+46,(vlSymsp->TOP__picorv32core__picorv32_core__cpuregs.__PVT__regs[25]),32);
    bufp->fullIData(oldp+47,(vlSymsp->TOP__picorv32core__picorv32_core__cpuregs.__PVT__regs[26]),32);
    bufp->fullIData(oldp+48,(vlSymsp->TOP__picorv32core__picorv32_core__cpuregs.__PVT__regs[27]),32);
    bufp->fullIData(oldp+49,(vlSymsp->TOP__picorv32core__picorv32_core__cpuregs.__PVT__regs[28]),32);
    bufp->fullIData(oldp+50,(vlSymsp->TOP__picorv32core__picorv32_core__cpuregs.__PVT__regs[29]),32);
    bufp->fullIData(oldp+51,(vlSymsp->TOP__picorv32core__picorv32_core__cpuregs.__PVT__regs[30]),32);
    bufp->fullBit(oldp+52,(vlSymsp->TOP__picorv32core.__PVT__mem_valid));
    bufp->fullBit(oldp+53,(vlSymsp->TOP__picorv32core.__PVT__mem_instr));
    bufp->fullIData(oldp+54,(vlSymsp->TOP__picorv32core.__PVT__mem_addr),32);
    bufp->fullIData(oldp+55,(vlSymsp->TOP__picorv32core.__PVT__mem_wdata),32);
    bufp->fullCData(oldp+56,(vlSymsp->TOP__picorv32core.__PVT__mem_wstrb),4);
    bufp->fullIData(oldp+57,(vlSymsp->TOP__picorv32core.__PVT__mem_la_addr),32);
    bufp->fullBit(oldp+58,(vlSymsp->TOP__picorv32core__memory_modelling_inst.__PVT__mem_instr));
    bufp->fullBit(oldp+59,(vlSymsp->TOP__picorv32core__memory_modelling_inst.__PVT__mem_valid));
    bufp->fullBit(oldp+60,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__trap));
    bufp->fullBit(oldp+61,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__mem_valid));
    bufp->fullBit(oldp+62,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__mem_instr));
    bufp->fullIData(oldp+63,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__mem_addr),32);
    bufp->fullIData(oldp+64,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__mem_wdata),32);
    bufp->fullCData(oldp+65,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__mem_wstrb),4);
    bufp->fullIData(oldp+66,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__mem_la_addr),32);
    bufp->fullBit(oldp+67,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__pcpi_valid));
    bufp->fullIData(oldp+68,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__pcpi_insn),32);
    bufp->fullIData(oldp+69,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__pcpi_rs1),32);
    bufp->fullIData(oldp+70,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__pcpi_rs2),32);
    bufp->fullIData(oldp+71,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__eoi),32);
    bufp->fullBit(oldp+72,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__trace_valid));
    bufp->fullQData(oldp+73,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__trace_data),36);
    bufp->fullQData(oldp+75,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__count_cycle),64);
    bufp->fullQData(oldp+77,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__count_instr),64);
    bufp->fullIData(oldp+79,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__reg_pc),32);
    bufp->fullIData(oldp+80,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__reg_next_pc),32);
    bufp->fullIData(oldp+81,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__reg_op1),32);
    bufp->fullIData(oldp+82,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__reg_op2),32);
    bufp->fullIData(oldp+83,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__reg_out),32);
    bufp->fullCData(oldp+84,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__reg_sh),5);
    bufp->fullIData(oldp+85,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__next_insn_opcode),32);
    bufp->fullIData(oldp+86,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__dbg_insn_opcode),32);
    bufp->fullIData(oldp+87,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__dbg_insn_addr),32);
    bufp->fullBit(oldp+88,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__dbg_mem_valid));
    bufp->fullBit(oldp+89,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__dbg_mem_instr));
    bufp->fullIData(oldp+90,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__dbg_mem_addr),32);
    bufp->fullIData(oldp+91,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__dbg_mem_wdata),32);
    bufp->fullCData(oldp+92,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__dbg_mem_wstrb),4);
    bufp->fullIData(oldp+93,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__next_pc),32);
    bufp->fullBit(oldp+94,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__irq_delay));
    bufp->fullBit(oldp+95,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__irq_active));
    bufp->fullIData(oldp+96,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__irq_mask),32);
    bufp->fullIData(oldp+97,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__irq_pending),32);
    bufp->fullIData(oldp+98,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__timer),32);
    bufp->fullCData(oldp+99,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__mem_state),2);
    bufp->fullCData(oldp+100,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__mem_wordsize),2);
    bufp->fullIData(oldp+101,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__mem_rdata_q),32);
    bufp->fullBit(oldp+102,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__mem_do_prefetch));
    bufp->fullBit(oldp+103,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__mem_do_rinst));
    bufp->fullBit(oldp+104,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__mem_do_rdata));
    bufp->fullBit(oldp+105,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__mem_do_wdata));
    bufp->fullBit(oldp+106,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__mem_la_secondword));
    bufp->fullBit(oldp+107,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__mem_la_firstword_reg));
    bufp->fullBit(oldp+108,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__last_mem_valid));
    bufp->fullBit(oldp+109,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__prefetched_high_word));
    bufp->fullBit(oldp+110,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__mem_busy));
    bufp->fullBit(oldp+111,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__instr_lui));
    bufp->fullBit(oldp+112,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__instr_auipc));
    bufp->fullBit(oldp+113,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__instr_jal));
    bufp->fullBit(oldp+114,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__instr_jalr));
    bufp->fullBit(oldp+115,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__instr_beq));
    bufp->fullBit(oldp+116,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__instr_bne));
    bufp->fullBit(oldp+117,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__instr_blt));
    bufp->fullBit(oldp+118,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__instr_bge));
    bufp->fullBit(oldp+119,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__instr_bltu));
    bufp->fullBit(oldp+120,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__instr_bgeu));
    bufp->fullBit(oldp+121,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__instr_lb));
    bufp->fullBit(oldp+122,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__instr_lh));
    bufp->fullBit(oldp+123,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__instr_lw));
    bufp->fullBit(oldp+124,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__instr_lbu));
    bufp->fullBit(oldp+125,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__instr_lhu));
    bufp->fullBit(oldp+126,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__instr_sb));
    bufp->fullBit(oldp+127,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__instr_sh));
    bufp->fullBit(oldp+128,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__instr_sw));
    bufp->fullBit(oldp+129,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__instr_addi));
    bufp->fullBit(oldp+130,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__instr_slti));
    bufp->fullBit(oldp+131,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__instr_sltiu));
    bufp->fullBit(oldp+132,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__instr_xori));
    bufp->fullBit(oldp+133,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__instr_ori));
    bufp->fullBit(oldp+134,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__instr_andi));
    bufp->fullBit(oldp+135,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__instr_slli));
    bufp->fullBit(oldp+136,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__instr_srli));
    bufp->fullBit(oldp+137,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__instr_srai));
    bufp->fullBit(oldp+138,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__instr_add));
    bufp->fullBit(oldp+139,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__instr_sub));
    bufp->fullBit(oldp+140,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__instr_sll));
    bufp->fullBit(oldp+141,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__instr_slt));
    bufp->fullBit(oldp+142,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__instr_sltu));
    bufp->fullBit(oldp+143,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__instr_xor));
    bufp->fullBit(oldp+144,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__instr_srl));
    bufp->fullBit(oldp+145,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__instr_sra));
    bufp->fullBit(oldp+146,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__instr_or));
    bufp->fullBit(oldp+147,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__instr_and));
    bufp->fullBit(oldp+148,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__instr_rdcycle));
    bufp->fullBit(oldp+149,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__instr_rdcycleh));
    bufp->fullBit(oldp+150,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__instr_rdinstr));
    bufp->fullBit(oldp+151,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__instr_rdinstrh));
    bufp->fullBit(oldp+152,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__instr_ecall_ebreak));
    bufp->fullBit(oldp+153,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__instr_getq));
    bufp->fullBit(oldp+154,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__instr_setq));
    bufp->fullBit(oldp+155,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__instr_retirq));
    bufp->fullBit(oldp+156,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__instr_maskirq));
    bufp->fullBit(oldp+157,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__instr_waitirq));
    bufp->fullBit(oldp+158,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__instr_timer));
    bufp->fullBit(oldp+159,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__instr_trap));
    bufp->fullCData(oldp+160,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__decoded_rd),5);
    bufp->fullCData(oldp+161,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__decoded_rs1),5);
    bufp->fullCData(oldp+162,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__decoded_rs2),5);
    bufp->fullIData(oldp+163,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__decoded_imm),32);
    bufp->fullIData(oldp+164,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__decoded_imm_j),32);
    bufp->fullBit(oldp+165,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__decoder_trigger));
    bufp->fullBit(oldp+166,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__decoder_trigger_q));
    bufp->fullBit(oldp+167,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__decoder_pseudo_trigger));
    bufp->fullBit(oldp+168,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__decoder_pseudo_trigger_q));
    bufp->fullBit(oldp+169,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__compressed_instr));
    bufp->fullBit(oldp+170,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__is_lui_auipc_jal));
    bufp->fullBit(oldp+171,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__is_lb_lh_lw_lbu_lhu));
    bufp->fullBit(oldp+172,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__is_slli_srli_srai));
    bufp->fullBit(oldp+173,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__is_jalr_addi_slti_sltiu_xori_ori_andi));
    bufp->fullBit(oldp+174,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__is_sb_sh_sw));
    bufp->fullBit(oldp+175,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__is_sll_srl_sra));
    bufp->fullBit(oldp+176,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__is_lui_auipc_jal_jalr_addi_add_sub));
    bufp->fullBit(oldp+177,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__is_slti_blt_slt));
    bufp->fullBit(oldp+178,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__is_sltiu_bltu_sltu));
    bufp->fullBit(oldp+179,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__is_beq_bne_blt_bge_bltu_bgeu));
    bufp->fullBit(oldp+180,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__is_lbu_lhu_lw));
    bufp->fullBit(oldp+181,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__is_alu_reg_imm));
    bufp->fullBit(oldp+182,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__is_alu_reg_reg));
    bufp->fullBit(oldp+183,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__is_compare));
    bufp->fullBit(oldp+184,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__is_rdcycle_rdcycleh_rdinstr_rdinstrh));
    bufp->fullQData(oldp+185,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__new_ascii_instr),64);
    bufp->fullQData(oldp+187,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__dbg_ascii_instr),64);
    bufp->fullIData(oldp+189,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__dbg_insn_imm),32);
    bufp->fullCData(oldp+190,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__dbg_insn_rs1),5);
    bufp->fullCData(oldp+191,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__dbg_insn_rs2),5);
    bufp->fullCData(oldp+192,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__dbg_insn_rd),5);
    bufp->fullIData(oldp+193,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__dbg_rs1val),32);
    bufp->fullIData(oldp+194,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__dbg_rs2val),32);
    bufp->fullBit(oldp+195,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__dbg_rs1val_valid));
    bufp->fullBit(oldp+196,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__dbg_rs2val_valid));
    bufp->fullQData(oldp+197,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__q_ascii_instr),64);
    bufp->fullIData(oldp+199,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__q_insn_imm),32);
    bufp->fullIData(oldp+200,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__q_insn_opcode),32);
    bufp->fullCData(oldp+201,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__q_insn_rs1),5);
    bufp->fullCData(oldp+202,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__q_insn_rs2),5);
    bufp->fullCData(oldp+203,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__q_insn_rd),5);
    bufp->fullBit(oldp+204,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__dbg_next));
    bufp->fullBit(oldp+205,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__launch_next_insn));
    bufp->fullBit(oldp+206,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__dbg_valid_insn));
    bufp->fullQData(oldp+207,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__cached_ascii_instr),64);
    bufp->fullIData(oldp+209,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__cached_insn_imm),32);
    bufp->fullIData(oldp+210,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__cached_insn_opcode),32);
    bufp->fullCData(oldp+211,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__cached_insn_rs1),5);
    bufp->fullCData(oldp+212,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__cached_insn_rs2),5);
    bufp->fullCData(oldp+213,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__cached_insn_rd),5);
    bufp->fullCData(oldp+214,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__cpu_state),8);
    bufp->fullCData(oldp+215,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__irq_state),2);
    bufp->fullWData(oldp+216,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__dbg_ascii_state),128);
    bufp->fullBit(oldp+220,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__set_mem_do_rinst));
    bufp->fullBit(oldp+221,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__set_mem_do_rdata));
    bufp->fullBit(oldp+222,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__set_mem_do_wdata));
    bufp->fullBit(oldp+223,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__latched_store));
    bufp->fullBit(oldp+224,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__latched_stalu));
    bufp->fullBit(oldp+225,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__latched_branch));
    bufp->fullBit(oldp+226,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__latched_compr));
    bufp->fullBit(oldp+227,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__latched_trace));
    bufp->fullBit(oldp+228,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__latched_is_lu));
    bufp->fullBit(oldp+229,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__latched_is_lh));
    bufp->fullBit(oldp+230,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__latched_is_lb));
    bufp->fullCData(oldp+231,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__latched_rd),5);
    bufp->fullIData(oldp+232,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__current_pc),32);
    bufp->fullBit(oldp+233,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__pcpi_timeout));
    bufp->fullIData(oldp+234,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__next_irq_pending),32);
    bufp->fullBit(oldp+235,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__do_waitirq));
    bufp->fullIData(oldp+236,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__alu_out),32);
    bufp->fullIData(oldp+237,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__alu_out_q),32);
    bufp->fullBit(oldp+238,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__alu_out_0));
    bufp->fullBit(oldp+239,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__alu_out_0_q));
    bufp->fullBit(oldp+240,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__alu_wait));
    bufp->fullBit(oldp+241,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__alu_wait_2));
    bufp->fullIData(oldp+242,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__alu_add_sub),32);
    bufp->fullIData(oldp+243,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__alu_shl),32);
    bufp->fullIData(oldp+244,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__alu_shr),32);
    bufp->fullBit(oldp+245,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__alu_eq));
    bufp->fullBit(oldp+246,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__alu_ltu));
    bufp->fullBit(oldp+247,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__alu_lts));
    bufp->fullBit(oldp+248,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__clear_prefetched_high_word_q));
    bufp->fullBit(oldp+249,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__cpuregs_write));
    bufp->fullIData(oldp+250,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__cpuregs_wrdata),32);
    bufp->fullCData(oldp+251,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__cpuregs_waddr),6);
    bufp->fullCData(oldp+252,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__cpuregs_raddr1),6);
    bufp->fullCData(oldp+253,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__cpuregs_raddr2),6);
    bufp->fullCData(oldp+254,(vlSymsp->TOP__picorv32core__picorv32_core__cpuregs.__PVT__waddr),6);
    bufp->fullCData(oldp+255,(vlSymsp->TOP__picorv32core__picorv32_core__cpuregs.__PVT__raddr1),6);
    bufp->fullCData(oldp+256,(vlSymsp->TOP__picorv32core__picorv32_core__cpuregs.__PVT__raddr2),6);
    bufp->fullIData(oldp+257,(vlSymsp->TOP__picorv32core__picorv32_core__cpuregs.__PVT__wdata),32);
    bufp->fullBit(oldp+258,(vlSymsp->TOP__picorv32core.__PVT__mem_ready));
    bufp->fullIData(oldp+259,(vlSymsp->TOP__picorv32core.__PVT__mem_rdata),32);
    bufp->fullBit(oldp+260,(vlSymsp->TOP__picorv32core__memory_modelling_inst.__PVT__mem_ready));
    bufp->fullIData(oldp+261,(vlSymsp->TOP__picorv32core__memory_modelling_inst.__PVT__mem_rdata),32);
    bufp->fullIData(oldp+262,(vlSymsp->TOP__picorv32core__memory_modelling_inst.__PVT__mem_read__Vstatic__mem_rdata),32);
    bufp->fullIData(oldp+263,(vlSymsp->TOP__picorv32core__memory_modelling_inst.__PVT__mem_write__Vstatic__m_addr),32);
    bufp->fullBit(oldp+264,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__mem_ready));
    bufp->fullIData(oldp+265,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__mem_rdata),32);
    bufp->fullBit(oldp+266,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__dbg_mem_ready));
    bufp->fullIData(oldp+267,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__dbg_mem_rdata),32);
    bufp->fullIData(oldp+268,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__cpuregs_rs1),32);
    bufp->fullIData(oldp+269,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__cpuregs_rs2),32);
    bufp->fullCData(oldp+270,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__decoded_rs),5);
    bufp->fullIData(oldp+271,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__cpuregs_rdata1),32);
    bufp->fullIData(oldp+272,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__cpuregs_rdata2),32);
    bufp->fullIData(oldp+273,(vlSymsp->TOP__picorv32core__picorv32_core__cpuregs.__PVT__rdata1),32);
    bufp->fullIData(oldp+274,(vlSymsp->TOP__picorv32core__picorv32_core__cpuregs.__PVT__rdata2),32);
    bufp->fullBit(oldp+275,(vlSymsp->TOP__picorv32core.__PVT__mem_la_read));
    bufp->fullBit(oldp+276,(vlSymsp->TOP__picorv32core.__PVT__mem_la_write));
    bufp->fullBit(oldp+277,(vlSymsp->TOP__picorv32core__memory_modelling_inst.__PVT__mem_la_read));
    bufp->fullBit(oldp+278,(vlSymsp->TOP__picorv32core__memory_modelling_inst.__PVT__mem_la_write));
    bufp->fullBit(oldp+279,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__mem_la_read));
    bufp->fullBit(oldp+280,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__mem_la_write));
    bufp->fullBit(oldp+281,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__clear_prefetched_high_word));
    bufp->fullBit(oldp+282,(vlSymsp->TOP__picorv32core__picorv32_core__cpuregs.__PVT__wen));
    bufp->fullIData(oldp+283,(vlSymsp->TOP__picorv32core.__PVT__mem_la_wdata),32);
    bufp->fullCData(oldp+284,(vlSymsp->TOP__picorv32core.__PVT__mem_la_wstrb),4);
    bufp->fullCData(oldp+285,(vlSymsp->TOP__picorv32core__memory_modelling_inst.__PVT__mem_la_wstrb),4);
    bufp->fullIData(oldp+286,(vlSymsp->TOP__picorv32core__memory_modelling_inst.__PVT__mem_la_wdata),32);
    bufp->fullIData(oldp+287,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__mem_la_wdata),32);
    bufp->fullCData(oldp+288,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__mem_la_wstrb),4);
    bufp->fullIData(oldp+289,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__mem_rdata_word),32);
    bufp->fullBit(oldp+290,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__mem_xfer));
    bufp->fullIData(oldp+291,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__mem_rdata_latched_noshuffle),32);
    bufp->fullIData(oldp+292,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__mem_rdata_latched),32);
    bufp->fullBit(oldp+293,(vlSelfRef.clk));
    bufp->fullBit(oldp+294,(vlSelfRef.rst));
    bufp->fullBit(oldp+295,(vlSymsp->TOP__picorv32core.__PVT__resetn));
    bufp->fullIData(oldp+296,(vlSymsp->TOP__picorv32core__memory_modelling_inst.__PVT__mem_la_addr),32);
    bufp->fullBit(oldp+297,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__resetn));
    bufp->fullBit(oldp+298,(vlSymsp->TOP__picorv32core__picorv32_core.__PVT__mem_done));
}
