// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vpicorv32core.h for the primary calling header

#ifndef VERILATED_VPICORV32CORE_PICORV32_H_
#define VERILATED_VPICORV32CORE_PICORV32_H_  // guard

#include "verilated.h"
class Vpicorv32core_picorv32_regs;


class Vpicorv32core__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vpicorv32core_picorv32 final : public VerilatedModule {
  public:
    // CELLS
    Vpicorv32core_picorv32_regs* __PVT__cpuregs;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(__PVT__clk,0,0);
        VL_IN8(__PVT__resetn,0,0);
        VL_OUT8(__PVT__trap,0,0);
        VL_OUT8(__PVT__mem_valid,0,0);
        VL_OUT8(__PVT__mem_instr,0,0);
        VL_IN8(__PVT__mem_ready,0,0);
        VL_OUT8(__PVT__mem_wstrb,3,0);
        VL_OUT8(__PVT__mem_la_read,0,0);
        VL_OUT8(__PVT__mem_la_write,0,0);
        VL_OUT8(__PVT__mem_la_wstrb,3,0);
        VL_OUT8(__PVT__pcpi_valid,0,0);
        VL_IN8(__PVT__pcpi_wr,0,0);
        VL_IN8(__PVT__pcpi_wait,0,0);
        VL_IN8(__PVT__pcpi_ready,0,0);
        VL_OUT8(__PVT__trace_valid,0,0);
        CData/*4:0*/ __PVT__reg_sh;
        CData/*0:0*/ __PVT__dbg_mem_valid;
        CData/*0:0*/ __PVT__dbg_mem_instr;
        CData/*0:0*/ __PVT__dbg_mem_ready;
        CData/*3:0*/ __PVT__dbg_mem_wstrb;
        CData/*0:0*/ __PVT__irq_delay;
        CData/*0:0*/ __PVT__irq_active;
        CData/*0:0*/ __PVT__pcpi_mul_wr;
        CData/*0:0*/ __PVT__pcpi_mul_wait;
        CData/*0:0*/ __PVT__pcpi_mul_ready;
        CData/*0:0*/ __PVT__pcpi_div_wr;
        CData/*0:0*/ __PVT__pcpi_div_wait;
        CData/*0:0*/ __PVT__pcpi_div_ready;
        CData/*0:0*/ __PVT__pcpi_int_wr;
        CData/*0:0*/ __PVT__pcpi_int_wait;
        CData/*0:0*/ __PVT__pcpi_int_ready;
        CData/*1:0*/ __PVT__mem_state;
        CData/*1:0*/ __PVT__mem_wordsize;
        CData/*0:0*/ __PVT__mem_do_prefetch;
        CData/*0:0*/ __PVT__mem_do_rinst;
        CData/*0:0*/ __PVT__mem_do_rdata;
        CData/*0:0*/ __PVT__mem_do_wdata;
        CData/*0:0*/ __PVT__mem_xfer;
        CData/*0:0*/ __PVT__mem_la_secondword;
        CData/*0:0*/ __PVT__mem_la_firstword_reg;
        CData/*0:0*/ __PVT__last_mem_valid;
        CData/*0:0*/ __PVT__mem_la_firstword;
        CData/*0:0*/ __PVT__mem_la_firstword_xfer;
        CData/*0:0*/ __PVT__prefetched_high_word;
        CData/*0:0*/ __PVT__clear_prefetched_high_word;
        CData/*0:0*/ __PVT__mem_la_use_prefetched_high_word;
        CData/*0:0*/ __PVT__mem_busy;
        CData/*0:0*/ __PVT__mem_done;
        CData/*0:0*/ __PVT__instr_lui;
        CData/*0:0*/ __PVT__instr_auipc;
        CData/*0:0*/ __PVT__instr_jal;
        CData/*0:0*/ __PVT__instr_jalr;
        CData/*0:0*/ __PVT__instr_beq;
        CData/*0:0*/ __PVT__instr_bne;
        CData/*0:0*/ __PVT__instr_blt;
        CData/*0:0*/ __PVT__instr_bge;
        CData/*0:0*/ __PVT__instr_bltu;
        CData/*0:0*/ __PVT__instr_bgeu;
        CData/*0:0*/ __PVT__instr_lb;
        CData/*0:0*/ __PVT__instr_lh;
        CData/*0:0*/ __PVT__instr_lw;
        CData/*0:0*/ __PVT__instr_lbu;
        CData/*0:0*/ __PVT__instr_lhu;
        CData/*0:0*/ __PVT__instr_sb;
    };
    struct {
        CData/*0:0*/ __PVT__instr_sh;
        CData/*0:0*/ __PVT__instr_sw;
        CData/*0:0*/ __PVT__instr_addi;
        CData/*0:0*/ __PVT__instr_slti;
        CData/*0:0*/ __PVT__instr_sltiu;
        CData/*0:0*/ __PVT__instr_xori;
        CData/*0:0*/ __PVT__instr_ori;
        CData/*0:0*/ __PVT__instr_andi;
        CData/*0:0*/ __PVT__instr_slli;
        CData/*0:0*/ __PVT__instr_srli;
        CData/*0:0*/ __PVT__instr_srai;
        CData/*0:0*/ __PVT__instr_add;
        CData/*0:0*/ __PVT__instr_sub;
        CData/*0:0*/ __PVT__instr_sll;
        CData/*0:0*/ __PVT__instr_slt;
        CData/*0:0*/ __PVT__instr_sltu;
        CData/*0:0*/ __PVT__instr_xor;
        CData/*0:0*/ __PVT__instr_srl;
        CData/*0:0*/ __PVT__instr_sra;
        CData/*0:0*/ __PVT__instr_or;
        CData/*0:0*/ __PVT__instr_and;
        CData/*0:0*/ __PVT__instr_rdcycle;
        CData/*0:0*/ __PVT__instr_rdcycleh;
        CData/*0:0*/ __PVT__instr_rdinstr;
        CData/*0:0*/ __PVT__instr_rdinstrh;
        CData/*0:0*/ __PVT__instr_ecall_ebreak;
        CData/*0:0*/ __PVT__instr_getq;
        CData/*0:0*/ __PVT__instr_setq;
        CData/*0:0*/ __PVT__instr_retirq;
        CData/*0:0*/ __PVT__instr_maskirq;
        CData/*0:0*/ __PVT__instr_waitirq;
        CData/*0:0*/ __PVT__instr_timer;
        CData/*0:0*/ __PVT__instr_trap;
        CData/*4:0*/ __PVT__decoded_rd;
        CData/*4:0*/ __PVT__decoded_rs1;
        CData/*4:0*/ __PVT__decoded_rs2;
        CData/*0:0*/ __PVT__decoder_trigger;
        CData/*0:0*/ __PVT__decoder_trigger_q;
        CData/*0:0*/ __PVT__decoder_pseudo_trigger;
        CData/*0:0*/ __PVT__decoder_pseudo_trigger_q;
        CData/*0:0*/ __PVT__compressed_instr;
        CData/*0:0*/ __PVT__is_lui_auipc_jal;
        CData/*0:0*/ __PVT__is_lb_lh_lw_lbu_lhu;
        CData/*0:0*/ __PVT__is_slli_srli_srai;
        CData/*0:0*/ __PVT__is_jalr_addi_slti_sltiu_xori_ori_andi;
        CData/*0:0*/ __PVT__is_sb_sh_sw;
        CData/*0:0*/ __PVT__is_sll_srl_sra;
        CData/*0:0*/ __PVT__is_lui_auipc_jal_jalr_addi_add_sub;
        CData/*0:0*/ __PVT__is_slti_blt_slt;
        CData/*0:0*/ __PVT__is_sltiu_bltu_sltu;
        CData/*0:0*/ __PVT__is_beq_bne_blt_bge_bltu_bgeu;
        CData/*0:0*/ __PVT__is_lbu_lhu_lw;
        CData/*0:0*/ __PVT__is_alu_reg_imm;
        CData/*0:0*/ __PVT__is_alu_reg_reg;
        CData/*0:0*/ __PVT__is_compare;
        CData/*0:0*/ __PVT__is_rdcycle_rdcycleh_rdinstr_rdinstrh;
        CData/*4:0*/ __PVT__dbg_insn_rs1;
        CData/*4:0*/ __PVT__dbg_insn_rs2;
        CData/*4:0*/ __PVT__dbg_insn_rd;
        CData/*0:0*/ __PVT__dbg_rs1val_valid;
        CData/*0:0*/ __PVT__dbg_rs2val_valid;
        CData/*4:0*/ __PVT__q_insn_rs1;
        CData/*4:0*/ __PVT__q_insn_rs2;
        CData/*4:0*/ __PVT__q_insn_rd;
    };
    struct {
        CData/*0:0*/ __PVT__dbg_next;
        CData/*0:0*/ __PVT__launch_next_insn;
        CData/*0:0*/ __PVT__dbg_valid_insn;
        CData/*4:0*/ __PVT__cached_insn_rs1;
        CData/*4:0*/ __PVT__cached_insn_rs2;
        CData/*4:0*/ __PVT__cached_insn_rd;
        CData/*7:0*/ __PVT__cpu_state;
        CData/*1:0*/ __PVT__irq_state;
        CData/*0:0*/ __PVT__set_mem_do_rinst;
        CData/*0:0*/ __PVT__set_mem_do_rdata;
        CData/*0:0*/ __PVT__set_mem_do_wdata;
        CData/*0:0*/ __PVT__latched_store;
        CData/*0:0*/ __PVT__latched_stalu;
        CData/*0:0*/ __PVT__latched_branch;
        CData/*0:0*/ __PVT__latched_compr;
        CData/*0:0*/ __PVT__latched_trace;
        CData/*0:0*/ __PVT__latched_is_lu;
        CData/*0:0*/ __PVT__latched_is_lh;
        CData/*0:0*/ __PVT__latched_is_lb;
        CData/*4:0*/ __PVT__latched_rd;
        CData/*3:0*/ __PVT__pcpi_timeout_counter;
        CData/*0:0*/ __PVT__pcpi_timeout;
        CData/*0:0*/ __PVT__do_waitirq;
        CData/*0:0*/ __PVT__alu_out_0;
        CData/*0:0*/ __PVT__alu_out_0_q;
        CData/*0:0*/ __PVT__alu_wait;
        CData/*0:0*/ __PVT__alu_wait_2;
        CData/*0:0*/ __PVT__alu_eq;
        CData/*0:0*/ __PVT__alu_ltu;
        CData/*0:0*/ __PVT__alu_lts;
        CData/*0:0*/ __PVT__clear_prefetched_high_word_q;
        CData/*0:0*/ __PVT__cpuregs_write;
        CData/*4:0*/ __PVT__decoded_rs;
        CData/*5:0*/ __PVT__cpuregs_waddr;
        CData/*5:0*/ __PVT__cpuregs_raddr1;
        CData/*5:0*/ __PVT__cpuregs_raddr2;
        CData/*0:0*/ __Vcellinp__cpuregs__wen;
        CData/*0:0*/ __Vdly__mem_la_firstword_reg;
        CData/*0:0*/ __Vdly__last_mem_valid;
        CData/*1:0*/ __Vdly__mem_state;
        CData/*0:0*/ __Vdly__mem_valid;
        CData/*0:0*/ __Vdly__mem_la_secondword;
        CData/*0:0*/ __Vdly__prefetched_high_word;
        CData/*3:0*/ __Vdly__mem_wstrb;
        CData/*0:0*/ __Vdly__mem_instr;
        CData/*4:0*/ __Vdly__q_insn_rs1;
        CData/*4:0*/ __Vdly__q_insn_rs2;
        CData/*4:0*/ __Vdly__q_insn_rd;
        CData/*0:0*/ __Vdly__dbg_next;
        CData/*0:0*/ __Vdly__dbg_valid_insn;
        CData/*4:0*/ __Vdly__cached_insn_rs1;
        CData/*4:0*/ __Vdly__cached_insn_rs2;
        CData/*4:0*/ __Vdly__cached_insn_rd;
        CData/*0:0*/ __Vdly__is_lui_auipc_jal;
        CData/*0:0*/ __Vdly__is_lui_auipc_jal_jalr_addi_add_sub;
        CData/*0:0*/ __Vdly__is_slti_blt_slt;
        CData/*0:0*/ __Vdly__is_sltiu_bltu_sltu;
        CData/*0:0*/ __Vdly__is_lbu_lhu_lw;
        CData/*0:0*/ __Vdly__is_compare;
        CData/*0:0*/ __Vdly__instr_lui;
        CData/*0:0*/ __Vdly__instr_auipc;
        CData/*0:0*/ __Vdly__instr_jal;
        CData/*0:0*/ __Vdly__instr_jalr;
        CData/*0:0*/ __Vdly__instr_retirq;
    };
    struct {
        CData/*0:0*/ __Vdly__instr_waitirq;
        CData/*0:0*/ __Vdly__is_beq_bne_blt_bge_bltu_bgeu;
        CData/*0:0*/ __Vdly__is_lb_lh_lw_lbu_lhu;
        CData/*0:0*/ __Vdly__is_sb_sh_sw;
        CData/*0:0*/ __Vdly__is_alu_reg_imm;
        CData/*0:0*/ __Vdly__is_alu_reg_reg;
        CData/*4:0*/ __Vdly__decoded_rd;
        CData/*4:0*/ __Vdly__decoded_rs1;
        CData/*4:0*/ __Vdly__decoded_rs2;
        CData/*0:0*/ __Vdly__compressed_instr;
        CData/*0:0*/ __Vdly__instr_beq;
        CData/*0:0*/ __Vdly__instr_bne;
        CData/*0:0*/ __Vdly__instr_blt;
        CData/*0:0*/ __Vdly__instr_bge;
        CData/*0:0*/ __Vdly__instr_bltu;
        CData/*0:0*/ __Vdly__instr_bgeu;
        CData/*0:0*/ __Vdly__instr_lb;
        CData/*0:0*/ __Vdly__instr_lh;
        CData/*0:0*/ __Vdly__instr_lw;
        CData/*0:0*/ __Vdly__instr_lbu;
        CData/*0:0*/ __Vdly__instr_lhu;
        CData/*0:0*/ __Vdly__instr_sb;
        CData/*0:0*/ __Vdly__instr_sh;
        CData/*0:0*/ __Vdly__instr_sw;
        CData/*0:0*/ __Vdly__instr_addi;
        CData/*0:0*/ __Vdly__instr_slti;
        CData/*0:0*/ __Vdly__instr_sltiu;
        CData/*0:0*/ __Vdly__instr_xori;
        CData/*0:0*/ __Vdly__instr_ori;
        CData/*0:0*/ __Vdly__instr_andi;
        CData/*0:0*/ __Vdly__instr_slli;
        CData/*0:0*/ __Vdly__instr_srli;
        CData/*0:0*/ __Vdly__instr_srai;
        CData/*0:0*/ __Vdly__instr_add;
        CData/*0:0*/ __Vdly__instr_sub;
        CData/*0:0*/ __Vdly__instr_sll;
        CData/*0:0*/ __Vdly__instr_slt;
        CData/*0:0*/ __Vdly__instr_sltu;
        CData/*0:0*/ __Vdly__instr_xor;
        CData/*0:0*/ __Vdly__instr_srl;
        CData/*0:0*/ __Vdly__instr_sra;
        CData/*0:0*/ __Vdly__instr_or;
        CData/*0:0*/ __Vdly__instr_and;
        CData/*0:0*/ __Vdly__instr_rdcycle;
        CData/*0:0*/ __Vdly__instr_rdcycleh;
        CData/*0:0*/ __Vdly__instr_rdinstr;
        CData/*0:0*/ __Vdly__instr_rdinstrh;
        CData/*0:0*/ __Vdly__instr_ecall_ebreak;
        CData/*0:0*/ __Vdly__instr_getq;
        CData/*0:0*/ __Vdly__instr_setq;
        CData/*0:0*/ __Vdly__instr_maskirq;
        CData/*0:0*/ __Vdly__instr_timer;
        CData/*0:0*/ __Vdly__is_slli_srli_srai;
        CData/*0:0*/ __Vdly__is_jalr_addi_slti_sltiu_xori_ori_andi;
        CData/*0:0*/ __Vdly__is_sll_srl_sra;
        CData/*0:0*/ __Vdly__clear_prefetched_high_word_q;
        CData/*0:0*/ __Vdly__trap;
        CData/*4:0*/ __Vdly__reg_sh;
        CData/*0:0*/ __Vdly__alu_out_0_q;
        CData/*0:0*/ __Vdly__alu_wait;
        CData/*0:0*/ __Vdly__alu_wait_2;
        CData/*0:0*/ __Vdly__dbg_rs1val_valid;
        CData/*0:0*/ __Vdly__dbg_rs2val_valid;
        CData/*0:0*/ __Vdly__decoder_trigger;
    };
    struct {
        CData/*0:0*/ __Vdly__decoder_trigger_q;
        CData/*0:0*/ __Vdly__decoder_pseudo_trigger;
        CData/*0:0*/ __Vdly__decoder_pseudo_trigger_q;
        CData/*0:0*/ __Vdly__do_waitirq;
        CData/*0:0*/ __Vdly__trace_valid;
        CData/*0:0*/ __Vdly__mem_do_rinst;
        CData/*1:0*/ __Vdly__mem_wordsize;
        CData/*0:0*/ __Vdly__latched_store;
        CData/*0:0*/ __Vdly__latched_stalu;
        CData/*0:0*/ __Vdly__latched_branch;
        CData/*0:0*/ __Vdly__latched_is_lu;
        CData/*0:0*/ __Vdly__latched_is_lh;
        CData/*0:0*/ __Vdly__latched_is_lb;
        CData/*4:0*/ __Vdly__latched_rd;
        CData/*0:0*/ __Vdly__latched_compr;
        CData/*0:0*/ __Vdly__irq_delay;
        CData/*0:0*/ __Vdly__mem_do_prefetch;
        CData/*7:0*/ __Vdly__cpu_state;
        CData/*0:0*/ __Vdly__latched_trace;
        CData/*0:0*/ __Vdly__pcpi_valid;
        CData/*0:0*/ __Vdly__pcpi_timeout;
        CData/*0:0*/ __Vdly__irq_active;
        CData/*1:0*/ __Vdly__irq_state;
        CData/*0:0*/ __Vdly__mem_do_rdata;
        CData/*0:0*/ __Vdly__mem_do_wdata;
        SData/*15:0*/ __PVT__mem_16bit_buffer;
        VL_OUT(__PVT__mem_addr,31,0);
        VL_OUT(__PVT__mem_wdata,31,0);
        VL_IN(__PVT__mem_rdata,31,0);
        VL_OUT(__PVT__mem_la_addr,31,0);
        VL_OUT(__PVT__mem_la_wdata,31,0);
        VL_OUT(__PVT__pcpi_insn,31,0);
        VL_OUT(__PVT__pcpi_rs1,31,0);
        VL_OUT(__PVT__pcpi_rs2,31,0);
        VL_IN(__PVT__pcpi_rd,31,0);
        VL_IN(__PVT__irq,31,0);
        VL_OUT(__PVT__eoi,31,0);
        IData/*31:0*/ __PVT__reg_pc;
        IData/*31:0*/ __PVT__reg_next_pc;
        IData/*31:0*/ __PVT__reg_op1;
        IData/*31:0*/ __PVT__reg_op2;
        IData/*31:0*/ __PVT__reg_out;
        IData/*31:0*/ __PVT__next_insn_opcode;
        IData/*31:0*/ __PVT__dbg_insn_opcode;
        IData/*31:0*/ __PVT__dbg_insn_addr;
        IData/*31:0*/ __PVT__dbg_mem_addr;
        IData/*31:0*/ __PVT__dbg_mem_wdata;
        IData/*31:0*/ __PVT__dbg_mem_rdata;
        IData/*31:0*/ __PVT__next_pc;
        IData/*31:0*/ __PVT__irq_mask;
        IData/*31:0*/ __PVT__irq_pending;
        IData/*31:0*/ __PVT__timer;
        IData/*31:0*/ __PVT__pcpi_mul_rd;
        IData/*31:0*/ __PVT__pcpi_div_rd;
        IData/*31:0*/ __PVT__pcpi_int_rd;
        IData/*31:0*/ __PVT__mem_rdata_word;
        IData/*31:0*/ __PVT__mem_rdata_q;
        IData/*31:0*/ __PVT__mem_rdata_latched_noshuffle;
        IData/*31:0*/ __PVT__mem_rdata_latched;
        IData/*31:0*/ __PVT__decoded_imm;
        IData/*31:0*/ __PVT__decoded_imm_j;
        IData/*31:0*/ __PVT__dbg_insn_imm;
        IData/*31:0*/ __PVT__dbg_rs1val;
        IData/*31:0*/ __PVT__dbg_rs2val;
    };
    struct {
        IData/*31:0*/ __PVT__q_insn_imm;
        IData/*31:0*/ __PVT__q_insn_opcode;
        IData/*31:0*/ __PVT__cached_insn_imm;
        IData/*31:0*/ __PVT__cached_insn_opcode;
        VlWide<4>/*127:0*/ __PVT__dbg_ascii_state;
        IData/*31:0*/ __PVT__current_pc;
        IData/*31:0*/ __PVT__next_irq_pending;
        IData/*31:0*/ __PVT__alu_out;
        IData/*31:0*/ __PVT__alu_out_q;
        IData/*31:0*/ __PVT__alu_add_sub;
        IData/*31:0*/ __PVT__alu_shl;
        IData/*31:0*/ __PVT__alu_shr;
        IData/*31:0*/ __PVT__cpuregs_wrdata;
        IData/*31:0*/ __PVT__cpuregs_rs1;
        IData/*31:0*/ __PVT__cpuregs_rs2;
        IData/*31:0*/ __PVT__cpuregs_rdata1;
        IData/*31:0*/ __PVT__cpuregs_rdata2;
        IData/*31:0*/ __Vdly__mem_rdata_q;
        IData/*31:0*/ __Vdly__next_insn_opcode;
        IData/*31:0*/ __Vdly__mem_addr;
        IData/*31:0*/ __Vdly__mem_wdata;
        IData/*31:0*/ __Vdly__q_insn_imm;
        IData/*31:0*/ __Vdly__q_insn_opcode;
        IData/*31:0*/ __Vdly__cached_insn_imm;
        IData/*31:0*/ __Vdly__cached_insn_opcode;
        IData/*31:0*/ __Vdly__dbg_insn_addr;
        IData/*31:0*/ __Vdly__decoded_imm_j;
        IData/*31:0*/ __Vdly__pcpi_insn;
        IData/*31:0*/ __Vdly__decoded_imm;
        IData/*31:0*/ __Vdly__reg_out;
        IData/*31:0*/ __Vdly__alu_out_q;
        IData/*31:0*/ __Vdly__dbg_rs1val;
        IData/*31:0*/ __Vdly__dbg_rs2val;
        IData/*31:0*/ __Vdly__reg_pc;
        IData/*31:0*/ __Vdly__reg_next_pc;
        IData/*31:0*/ __Vdly__reg_op1;
        IData/*31:0*/ __Vdly__reg_op2;
        IData/*31:0*/ __Vdly__timer;
        IData/*31:0*/ __Vdly__irq_mask;
        IData/*31:0*/ __Vdly__eoi;
        IData/*31:0*/ __Vdly__irq_pending;
        VL_OUT64(__PVT__trace_data,35,0);
        QData/*63:0*/ __PVT__count_cycle;
        QData/*63:0*/ __PVT__count_instr;
        QData/*63:0*/ __PVT__new_ascii_instr;
        QData/*63:0*/ __PVT__dbg_ascii_instr;
        QData/*63:0*/ __PVT__q_ascii_instr;
        QData/*63:0*/ __PVT__cached_ascii_instr;
        QData/*63:0*/ __Vdly__q_ascii_instr;
        QData/*63:0*/ __Vdly__cached_ascii_instr;
        QData/*63:0*/ __Vdly__count_cycle;
        QData/*35:0*/ __Vdly__trace_data;
        QData/*63:0*/ __Vdly__count_instr;
    };

    // INTERNAL VARIABLES
    Vpicorv32core__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vpicorv32core_picorv32(Vpicorv32core__Syms* symsp, const char* v__name);
    ~Vpicorv32core_picorv32();
    VL_UNCOPYABLE(Vpicorv32core_picorv32);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
