// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vaquila_top.h for the primary calling header

#ifndef VERILATED_VAQUILA_TOP_BPU_H_
#define VERILATED_VAQUILA_TOP_BPU_H_  // guard

#include "verilated.h"
class Vaquila_top_distri_ram__E40;


class Vaquila_top__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vaquila_top_bpu final : public VerilatedModule {
  public:
    // CELLS
    Vaquila_top_distri_ram__E40* __PVT__bpu_pc_history;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(__PVT__clk_i,0,0);
        VL_IN8(__PVT__rst_i,0,0);
        VL_IN8(__PVT__stall_i,0,0);
        VL_IN8(__PVT__is_jal_i,0,0);
        VL_IN8(__PVT__is_cond_branch_i,0,0);
        VL_IN8(__PVT__exe_is_branch_i,0,0);
        VL_IN8(__PVT__branch_taken_i,0,0);
        VL_IN8(__PVT__branch_misprediction_i,0,0);
        VL_OUT8(__PVT__branch_hit_o,0,0);
        VL_OUT8(__PVT__branch_decision_o,0,0);
        CData/*0:0*/ __PVT__we;
        CData/*5:0*/ __PVT__read_addr;
        CData/*5:0*/ __PVT__write_addr;
        CData/*5:0*/ __PVT__update_addr;
        CData/*5:0*/ __Vdly__write_addr;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v0;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v1;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v2;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v3;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v4;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v5;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v6;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v7;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v8;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v9;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v10;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v11;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v12;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v13;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v14;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v15;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v16;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v17;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v18;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v19;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v20;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v21;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v22;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v23;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v24;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v25;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v26;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v27;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v28;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v29;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v30;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v31;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v32;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v33;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v34;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v35;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v36;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v37;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v38;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v39;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v40;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v41;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v42;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v43;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v44;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v45;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v46;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v47;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v48;
    };
    struct {
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v49;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v50;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v51;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v52;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v53;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v54;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v55;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v56;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v57;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v58;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v59;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v60;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v61;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v62;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v63;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v64;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v65;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v66;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v67;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v68;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v69;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v70;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v71;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v72;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v73;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v74;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v75;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v76;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v77;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v78;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v79;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v80;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v81;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v82;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v83;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v84;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v85;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v86;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v87;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v88;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v89;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v90;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v91;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v92;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v93;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v94;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v95;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v96;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v97;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v98;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v99;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v100;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v101;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v102;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v103;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v104;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v105;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v106;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v107;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v108;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v109;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v110;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v111;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v112;
    };
    struct {
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v113;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v114;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v115;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v116;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v117;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v118;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v119;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v120;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v121;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v122;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v123;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v124;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v125;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v126;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v127;
        CData/*5:0*/ __Vdlyvdim0__branch_pc_table__v128;
        CData/*0:0*/ __Vdlyvset__branch_pc_table__v128;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v0;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v1;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v2;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v3;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v4;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v5;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v6;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v7;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v8;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v9;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v10;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v11;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v12;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v13;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v14;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v15;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v16;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v17;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v18;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v19;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v20;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v21;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v22;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v23;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v24;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v25;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v26;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v27;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v28;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v29;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v30;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v31;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v32;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v33;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v34;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v35;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v36;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v37;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v38;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v39;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v40;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v41;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v42;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v43;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v44;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v45;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v46;
    };
    struct {
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v47;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v48;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v49;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v50;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v51;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v52;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v53;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v54;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v55;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v56;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v57;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v58;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v59;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v60;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v61;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v62;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v63;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v64;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v64;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v65;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v65;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v66;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v66;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v67;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v67;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v68;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v68;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v69;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v69;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v70;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v70;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v71;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v71;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v72;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v72;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v73;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v73;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v74;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v74;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v75;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v75;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v76;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v76;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v77;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v77;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v78;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v78;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v79;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v79;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v80;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v80;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v81;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v81;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v82;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v82;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v83;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v83;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v84;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v84;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v85;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v85;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v86;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v86;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v87;
    };
    struct {
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v87;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v88;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v88;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v89;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v89;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v90;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v90;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v91;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v91;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v92;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v92;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v93;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v93;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v94;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v94;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v95;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v95;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v96;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v96;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v97;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v97;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v98;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v98;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v99;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v99;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v100;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v100;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v101;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v101;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v102;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v102;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v103;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v103;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v104;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v104;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v105;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v105;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v106;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v106;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v107;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v107;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v108;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v108;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v109;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v109;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v110;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v110;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v111;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v111;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v112;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v112;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v113;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v113;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v114;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v114;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v115;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v115;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v116;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v116;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v117;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v117;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v118;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v118;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v119;
    };
    struct {
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v119;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v120;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v120;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v121;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v121;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v122;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v122;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v123;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v123;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v124;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v124;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v125;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v125;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v126;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v126;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v127;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v127;
        CData/*5:0*/ __Vdlyvdim0__branch_likelihood__v128;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v128;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v128;
        CData/*5:0*/ __Vdlyvdim0__branch_likelihood__v129;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v129;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v129;
        CData/*5:0*/ __Vdlyvdim0__branch_likelihood__v130;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v130;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v130;
        CData/*5:0*/ __Vdlyvdim0__branch_likelihood__v131;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v131;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v131;
        CData/*5:0*/ __Vdlyvdim0__branch_likelihood__v132;
        CData/*1:0*/ __Vdlyvval__branch_likelihood__v132;
        CData/*0:0*/ __Vdlyvset__branch_likelihood__v132;
        VL_IN(__PVT__pc_i,31,0);
        VL_IN(__PVT__dec_pc_i,31,0);
        VL_IN(__PVT__branch_target_addr_i,31,0);
        VL_OUT(__PVT__branch_target_addr_o,31,0);
        IData/*31:0*/ __PVT__predicted_pc;
        IData/*31:0*/ __PVT__idx;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v64;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v65;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v66;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v67;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v68;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v69;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v70;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v71;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v72;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v73;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v74;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v75;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v76;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v77;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v78;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v79;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v80;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v81;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v82;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v83;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v84;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v85;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v86;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v87;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v88;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v89;
    };
    struct {
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v90;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v91;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v92;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v93;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v94;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v95;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v96;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v97;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v98;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v99;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v100;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v101;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v102;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v103;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v104;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v105;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v106;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v107;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v108;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v109;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v110;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v111;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v112;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v113;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v114;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v115;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v116;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v117;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v118;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v119;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v120;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v121;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v122;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v123;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v124;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v125;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v126;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v127;
        IData/*31:0*/ __Vdlyvval__branch_pc_table__v128;
        QData/*63:0*/ __PVT__addr_hit_PCU;
        QData/*63:0*/ __PVT__addr_hit_DEC;
        VlUnpacked<IData/*31:0*/, 64> __PVT__branch_pc_table;
        VlUnpacked<CData/*1:0*/, 64> __PVT__branch_likelihood;
    };

    // INTERNAL VARIABLES
    Vaquila_top__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vaquila_top_bpu(Vaquila_top__Syms* symsp, const char* v__name);
    ~Vaquila_top_bpu();
    VL_UNCOPYABLE(Vaquila_top_bpu);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
